
    -- Generated by Oracle SQL Developer Data Modeler 24.3.1.351.0831
    --   at:        2026-06-15 23:10:57 VET
    --   site:      Oracle Database 11g
    --   type:      Oracle Database 11g

    -- predefined type, no DDL - MDSYS.SDO_GEOMETRY

    -- predefined type, no DDL - XMLTYPE

    /* CREATE DE LAS TABLAS */

    CREATE TABLE Ambiente (
        idAmbiente  NUMERIC(1000)  NOT NULL UNIQUE,
        nombre      VARCHAR(150)  NOT NULL,
        descripcion VARCHAR(600)  NOT NULL,

        CONSTRAINT pk_ambiente_01 PRIMARY KEY (idAmbiente)
    );

    CREATE TABLE AsignacionMeta (
        idAsignacionMeta              NUMERIC  NOT NULL UNIQUE,
        metaCumplida                  CHAR(1)  NOT NULL ,
        MetaMensual_idMetaMensual     NUMERIC  NOT NULL ,
        Empleado_idEmpleado                 NUMERIC  NOT NULL ,
        ComisionVenta_idComisionVenta NUMERIC  NOT NULL,

        CONSTRAINT pk_asignacion_meta_01 PRIMARY KEY (idAsignacionMeta, MetaMensual_idMetaMensual, Empleado_idEmpleado)
    );

    CREATE TABLE Asistencia (
         idAsistencia        NUMERIC NOT NULL ,
         fecha               DATE NOT NULL ,
         horaEntrada         TIME NOT NULL ,
         horaSalida          TIME NOT NULL ,
         Empleado_idEmpleado NUMERIC NOT NULL,

         CONSTRAINT pk_asistencia_01 PRIMARY KEY ( idAsistencia )
    );

    CREATE TABLE AutorDiseño (
         idAutorDiseño                   NUMERIC  NOT NULL UNIQUE,
         Diseño_idDiseño                 NUMERIC  NOT NULL,
         Empleado_id                     NUMERIC  NOT NULL,
         Regalia_idRegalia               NUMERIC  NOT NULL,
         ObjetivoGlobal_idObjetivoGlobal NUMERIC  NOT NULL,

        CONSTRAINT pk_autor_diseño_01 PRIMARY KEY (idAutorDiseño, Diseño_idDiseño, Empleado_id)
    );

    CREATE TABLE BackOrder(
         idBackOrder           NUMERIC  NOT NULL UNIQUE,
         cantidadPendiente     NUMERIC  NOT NULL,
         precioOriginalPactado NUMERIC  NOT NULL,
         fechaGeneracion       DATE  NOT NULL,
         estatus               NUMERIC NOT NULL,

        CONSTRAINT pk_backorder_01 PRIMARY KEY (idBackOrder)
    );

    CREATE TABLE ChequeCorporativo (
         idMetodoPago            NUMERIC  NOT NULL UNIQUE,
         numeroCheque        NUMERIC  NOT NULL,
         numeroCuentaEmisora NUMERIC  NOT NULL,
         bancoEmisor         NUMERIC  NOT NULL,

        CONSTRAINT pk_cheque_corporativo_01 PRIMARY KEY (idMetodoPago)
    );

    CREATE TABLE ClasificacionExclusividad (
         idClasificacionExclusividad NUMERIC  NOT NULL UNIQUE,
         nombre VARCHAR(150)  NOT NULL ,
         descripcion VARCHAR(600)  NOT NULL,

        CONSTRAINT pk_clasificacion_exclusividad_01 PRIMARY KEY (idClasificacionExclusividad)
    );

    CREATE TABLE ClasificacionHistorica (
         idClasificacionHistorica NUMERIC  NOT NULL ,
         nombre                   VARCHAR(150)  NOT NULL ,
         descripcion              VARCHAR(600)  NOT NULL,

        CONSTRAINT pk_clasificacion_historica_01 PRIMARY KEY (idClasificacionHistorica)
    );

    CREATE TABLE ClienteJuridico (
         idClienteJuridico NUMERIC  NOT NULL ,
         rif               NUMERIC  NOT NULL ,
         razonSocial       VARCHAR(150)  NOT NULL ,
         nombre            VARCHAR(150)  NOT NULL ,
         direccionJuridica VARCHAR(150)  NOT NULL ,
         limiteCredito     NUMERIC  NOT NULL,
         Lugar_idLugar NUMERIC NOT NULL,

        CONSTRAINT pk_cliente_juridico_01 PRIMARY KEY (idClienteJuridico)
    );

    CREATE TABLE ClienteNatural (
         idClienteNatural                                      NUMERIC  NOT NULL,
         cedula                                                NUMERIC  NOT NULL,
         pNombre                                               VARCHAR(150)  NOT NULL,
         sNombre                                               VARCHAR(150),
         pApellido                                             VARCHAR(150)  NOT NULL,
         sApellido                                             VARCHAR(150),
         direccion                                             VARCHAR(150)  NOT NULL,
         MonitorActividadSopechosa_idMonitorActividadSopechosa NUMERIC  NOT NULL,
         Lugar_idLugar NUMERIC NOT NULL,

        CONSTRAINT pk_cliente_natural_01 PRIMARY KEY (idClienteNatural)
    );

    CREATE TABLE Color (
         idColor           NUMERIC  NOT NULL UNIQUE,
         codigoHexadecimal VARCHAR(150)  NOT NULL ,
         nombre            VARCHAR(150)  NOT NULL,

        CONSTRAINT pk_color_01 PRIMARY KEY (idColor)
    );

    CREATE TABLE ComisionVenta (
         idComisionVenta           NUMERIC  NOT NULL UNIQUE,
         montoComision             NUMERIC  NOT NULL,
         fecha                     DATE  NOT NULL,
         OrdenCompra_idOrdenCompra NUMERIC  NOT NULL,

        CONSTRAINT pk_comision_venta_01 PRIMARY KEY (idComisionVenta)
    );

    CREATE TABLE Compra (
         idCompra                                NUMERIC  NOT NULL ,
         fechaHora                               DATE  NOT NULL ,
         numeroCompra                            NUMERIC  NOT NULL ,
         totalPagar                              NUMERIC  NOT NULL ,
         subTotal                                NUMERIC  NOT NULL ,
         ClienteNatural_idClienteNatural         NUMERIC  NOT NULL ,
         TipoUbicacionStock_idTipoUbicacionStock NUMERIC  NOT NULL,

        CONSTRAINT pk_compra_01 PRIMARY KEY (idCompra)
    );

    CREATE TABLE CompraDescuento (
         idCompraDescuento     NUMERIC  NOT NULL ,
         monto NUMERIC NOT NULL,
         Compra_idCompra       NUMERIC  NOT NULL ,
         Descuento_idDescuento NUMERIC  NOT NULL,

        CONSTRAINT pk_compra_descuento_01 PRIMARY KEY (idCompraDescuento, Compra_idCompra, Descuento_idDescuento)
    );

    CREATE TABLE Conciliacion (
        idConciliacion            NUMERIC NOT NULL,
        montoAplicado             NUMERIC NOT NULL,
        fechaAplicacion           DATE NOT NULL,
        OrdenCompra_idOrdenCompra NUMERIC NOT NULL,
        PagoJuridico_idPago       NUMERIC NOT NULL,

        CONSTRAINT pk_conciliacion_01 PRIMARY KEY (idConciliacion, OrdenCompra_idOrdenCompra, PagoJuridico_idPago)
    );

    CREATE TABLE CondicionFisica (
         idCondicionFisica NUMERIC  NOT NULL ,
         nombre            VARCHAR(150)  NOT NULL ,
         descripcion       VARCHAR(600)  NOT NULL,

        CONSTRAINT pk_condicion_fisica_01 PRIMARY KEY (idCondicionFisica)
    );

    CREATE TABLE Courier (
         idCourier NUMERIC  NOT NULL ,
         nombre    VARCHAR(150)  NOT NULL,

        CONSTRAINT pk_courier_01 PRIMARY KEY (idCourier)
    );

    CREATE TABLE CriptoActivo (
         idMetodoPago  NUMERIC  NOT NULL UNIQUE,
         hashTransaccion VARCHAR(200)  NOT NULL ,
         redBlockchain   VARCHAR(200)  NOT NULL ,
         billeteraOrigen VARCHAR(200)  NOT NULL,

        CONSTRAINT pk_cripto_activo_01 PRIMARY KEY (idMetodoPago)
    );

    CREATE TABLE CurriculumVitae (
        idCurriculumVitae     NUMERIC  NOT NULL UNIQUE,
        añoDeAsignacion       NUMERIC  NOT NULL ,
        Profesion_idProfesion NUMERIC  NOT NULL ,
        Diseño_idDiseño       NUMERIC  NOT NULL,

        CONSTRAINT pk_curriculum_vitae_01 PRIMARY KEY (idCurriculumVitae, Profesion_idProfesion, Diseño_idDiseño)
    );

    CREATE TABLE Departamento (
         idDepartamento NUMERIC  NOT NULL ,
         nombre         VARCHAR(150)  NOT NULL ,
         direccion      VARCHAR(150)  NOT NULL,

        CONSTRAINT pk_departamento_01 PRIMARY KEY (idDepartamento)
    );

    CREATE TABLE Descuento (
         idDescuento       NUMERIC  NOT NULL ,
         nombre            VARCHAR(150)  NOT NULL ,
         descripcion       VARCHAR(600)  NOT NULL ,
         porcentaje        NUMERIC  NOT NULL ,

        CONSTRAINT pk_descuento_01 PRIMARY KEY (idDescuento)
    );

    CREATE TABLE DespachoNatural (
        idDespachoNatural NUMERIC  NOT NULL ,
        numeroTracking    NUMERIC  NOT NULL ,
        alto              NUMERIC  NOT NULL ,
        ancho             NUMERIC  NOT NULL ,
        largo             NUMERIC  NOT NULL ,
        costoEnvio        NUMERIC  NOT NULL ,
        Compra_idCompra   NUMERIC  NOT NULL ,
        Courier_idCourier NUMERIC  NOT NULL,

        CONSTRAINT pk_despacho_natural_01 PRIMARY KEY (idDespachoNatural)
    );

    CREATE TABLE DetalleCompraJuridico (
         idDetalleCompraJuridico     NUMERIC  NOT NULL,
         precioUnitario              NUMERIC  NOT NULL,
         cantidad                    NUMERIC  NOT NULL,
         estado                      VARCHAR(150)  NOT NULL,
         Departamento_idDepartamento NUMERIC  NOT NULL,
         OrdenCompra_idOrdenCompra   NUMERIC  NOT NULL,
         Caja_idCaja                 NUMERIC  NOT NULL,
         BackOrder_idBackOrder       NUMERIC  NOT NULL,

        CONSTRAINT pk_detalle_compra_juridico_01 PRIMARY KEY (idDetalleCompraJuridico, OrdenCompra_idOrdenCompra)
    );

    CREATE UNIQUE INDEX DetalleCompraJuridico__IDX ON DetalleCompraJuridico ( BackOrder_idBackOrder ASC );

    CREATE TABLE DetalleCompraNatural (
         idDetalleCompraNatural             NUMERIC  NOT NULL UNIQUE ,
         precioUnitario                     NUMERIC  NOT NULL,
         UnidadProducida_idUnidadProducidad NUMERIC  NOT NULL,
         Compra_idCompra                    NUMERIC  NOT NULL,

        CONSTRAINT pk_detalle_compra_natural_01 PRIMARY KEY (idDetalleCompraNatural, UnidadProducida_idUnidadProducidad, Compra_idCompra)
    );

    CREATE TABLE DevolucionJuridica (
        idDevolucionJuridica      NUMERIC  NOT NULL UNIQUE,
        fechaDevolucion           DATE  NOT NULL ,
        motivo                    VARCHAR(600)  NOT NULL ,
        OrdenCompra_idOrdenCompra NUMERIC  NOT NULL,

        CONSTRAINT pk_devolucion_juridica_01 PRIMARY KEY (idDevolucionJuridica)
    );

    CREATE TABLE DevolucionNatural (
         idDevolucionNatural NUMERIC  NOT NULL ,
         fechaDevolucion     DATE  NOT NULL ,
         motivo              VARCHAR(600)  NOT NULL ,
         Compra_idCompra     NUMERIC  NOT NULL,

        CONSTRAINT pk_devolucion_natural_01 PRIMARY KEY (idDevolucionNatural)
    );

    CREATE TABLE Diseño (
        idDiseño                                              NUMERIC  NOT NULL ,
        nombre                                                VARCHAR(150)  NOT NULL ,
        descripcion                                           VARCHAR(600)  NOT NULL ,
        ClasificacionHistorica_idClasificacionHistorica       NUMERIC  NOT NULL,
        ClasificacionExclusividad_idClasificacionExclusividad NUMERIC  NOT NULL,
        TonoPiel_idTonoPiel                                   NUMERIC  NOT NULL,
        MoldeRostro_idMoldeRostro                             NUMERIC  NOT NULL,
        Diseño_idDiseño                                       NUMERIC,
        TipoDiseño_idTipoDiseño                               NUMERIC  NOT NULL,

        CONSTRAINT pk_diseño_01 PRIMARY KEY (idDiseño)
    );

    CREATE TABLE DiseñoAmbiente (
         idDiseñoAmbiente    NUMERIC  NOT NULL UNIQUE,
         interactivo         CHAR(1),
         Diseño_idDiseño     NUMERIC  NOT NULL,
         Ambiente_idAmbiente NUMERIC  NOT NULL,

        CONSTRAINT pk_diseño_ambiente_01 PRIMARY KEY (idDiseñoAmbiente, Diseño_idDiseño, Ambiente_idAmbiente)
    );

    CREATE TABLE Efectivo (
        idMetodoPago                 NUMERIC  NOT NULL UNIQUE,
        numeroSerie                VARCHAR(200)  NOT NULL,
        letraNumeroReservaFederal1 VARCHAR(200)  NOT NULL,

        CONSTRAINT pk_efectivo_01 PRIMARY KEY (idMetodoPago)
    );

    CREATE TABLE Empleado (
         idEmpleado              NUMERIC  NOT NULL UNIQUE ,
         cedula          NUMERIC  NOT NULL ,
         pNombre         VARCHAR(150)  NOT NULL ,
         sNombre         VARCHAR(150) ,
         pApellido       VARCHAR(150)  NOT NULL ,
         sApellido       VARCHAR(150) ,
         fechaNacimiento DATE  NOT NULL ,
         direccion       VARCHAR(200)  NOT NULL ,
         Lugar_idLugar   NUMERIC  NOT NULL,

        CONSTRAINT pk_empleado_01 PRIMARY KEY (idEmpleado)
    );

    CREATE TABLE EstadoOrden (
         idEstadoOrden NUMERIC  NOT NULL UNIQUE,
         nombre        VARCHAR(150)  NOT NULL ,
         descripcion   VARCHAR(600)  NOT NULL,

        CONSTRAINT pk_estado_orden_01 PRIMARY KEY (idEstadoOrden)
    );

    CREATE TABLE Estatus (
         idEstatus   NUMERIC NOT NULL ,
         nombre      VARCHAR(150) NOT NULL ,
         tipoEstatus VARCHAR(150) NOT NULL,
         CONSTRAINT pk_estatus_01 PRIMARY KEY ( idEstatus )
    );

    CREATE TABLE Fase (
         idFase          NUMERIC NOT NULL ,
         nombreFase      VARCHAR(150) NOT NULL ,
         descripcionFase VARCHAR(600) ,
         Diseño_idDiseño NUMERIC NOT NULL,

        CONSTRAINT pk_fase_01 PRIMARY KEY ( idFase )
    );

    CREATE TABLE FaseEmpleado (
         idFaseEmpleado      NUMERIC NOT NULL ,
         fechaInicio         DATE NOT NULL ,
         fechaFin            DATE ,
         Empleado_idEmpleado NUMERIC NOT NULL ,
         Fase_idFase         NUMERIC NOT NULL,

        CONSTRAINT pk_fase_empleado_01 PRIMARY KEY (idFaseEmpleado, Empleado_idEmpleado, Fase_idFase)
    );

    CREATE TABLE HistoricoEmpleado (
         idHistoricoEmpleado                     NUMERIC  NOT NULL UNIQUE,
         fechaInicio                             DATE  NOT NULL ,
         fechaFin                                DATE,
         salarioBase                             NUMERIC  NOT NULL ,
         Empleado_idEmpleado                             NUMERIC  NOT NULL ,
         Departamento_idDepartamento             NUMERIC  NOT NULL ,
         PuestoTrabajo_id                        NUMERIC  NOT NULL ,
         TipoUbicacionStock_idTipoUbicacionStock NUMERIC  NOT NULL,

        CONSTRAINT pk_historico_empleado_01 PRIMARY KEY (idHistoricoEmpleado, Empleado_idEmpleado, Departamento_idDepartamento)
    );

    CREATE TABLE HistoricoEstado (
        idHistoricoEstado         NUMERIC  NOT NULL,
        fechaHora                 TIMESTAMP  NOT NULL,
        OrdenCompra_idOrdenCompra NUMERIC,          -- Permite NULL (CHECK exige que una de las dos sea NULL)
        EstadoOrden_idEstadoOrden NUMERIC  NOT NULL,
        Compra_idCompra           NUMERIC,          -- Permite NULL (CHECK exige que una de las dos sea NULL)

        CONSTRAINT arc_historico_estado_01 CHECK ( ( (OrdenCompra_idOrdenCompra IS NOT NULL) AND (Compra_idCompra IS NULL) ) OR ( (Compra_idCompra IS NOT NULL) AND (OrdenCompra_idOrdenCompra IS NULL) ) ),
        CONSTRAINT pk_historico_estado_01 PRIMARY KEY (idHistoricoEstado, EstadoOrden_idEstadoOrden)
    );

    CREATE TABLE HistoricoEstatus (
         idHistoricoEstatus      NUMERIC NOT NULL ,
         fechaHoraInicio         DATE NOT NULL ,
         Estatus_idEstatus       NUMERIC NOT NULL ,
         fechaHoraFin            DATE ,
         Subasta_idSubasta       NUMERIC ,
         Puja_idPuja             NUMERIC ,
         Puja_idClienteNatural   NUMERIC ,
         Puja_idSubasta          NUMERIC ,
         OrdenVenta_idOrdenVenta NUMERIC ,
         Compra_idCompra         NUMERIC,

        CONSTRAINT arc_historico_estatus_01 CHECK ( (  (Compra_idCompra IS NOT NULL) AND
             (Puja_idPuja IS NULL)  AND
             (Puja_idClienteNatural IS NULL)  AND
             (Puja_idSubasta IS NULL)  AND
             (Subasta_idSubasta IS NULL)  AND
             (OrdenVenta_idOrdenVenta IS NULL) ) OR
             ( (Puja_idPuja IS NOT NULL) AND
             (Puja_idClienteNatural IS NOT NULL) AND
             (Puja_idSubasta IS NOT NULL) AND
             (Compra_idCompra IS NULL)  AND
             (Subasta_idSubasta IS NULL)  AND
             (OrdenVenta_idOrdenVenta IS NULL) ) OR
             ( (Subasta_idSubasta IS NOT NULL) AND
             (Compra_idCompra IS NULL)  AND
             (Puja_idPuja IS NULL)  AND
             (Puja_idClienteNatural IS NULL)  AND
             (Puja_idSubasta IS NULL)  AND
             (OrdenVenta_idOrdenVenta IS NULL) ) OR
             ( (OrdenVenta_idOrdenVenta IS NOT NULL) AND
             (Compra_idCompra IS NULL)  AND
             (Puja_idPuja IS NULL)  AND
             (Puja_idClienteNatural IS NULL)  AND
             (Puja_idSubasta IS NULL)  AND
             (Subasta_idSubasta IS NULL) ) ),

        CONSTRAINT pk_historico_estatus_01 PRIMARY KEY ( idHistoricoEstatus, Estatus_idEstatus )
    );

    CREATE TABLE Horario (
        idHorario  NUMERIC  NOT NULL UNIQUE,
        dia        VARCHAR(150) NOT NULL,
        horaInicio TIME  NOT NULL,
        horaFin    TIME  NOT NULL,

        CONSTRAINT pk_horario_01 PRIMARY KEY (idHorario)
    );

    CREATE TABLE InsumoProduccion (
        idInsumoProduccion                  NUMERIC  NOT NULL UNIQUE,
        cantidad                            NUMERIC  NOT NULL,
        LoteMateriaPrima_idLoteMateriaPrima NUMERIC  NOT NULL,
        LoteProduccion_idLote               NUMERIC  NOT NULL,

        CONSTRAINT pk_insumo_produccion_01 PRIMARY KEY (idInsumoProduccion, LoteMateriaPrima_idLoteMateriaPrima, LoteProduccion_idLote)
    );

    CREATE TABLE ListaPrecioMayorista (
        idListaPrecioMayorista             NUMERIC  NOT NULL,
        precioUnitario                     NUMERIC  NOT NULL,
        fecha                              DATE  NOT NULL,
        ClienteJuridico_idClienteJuridico  NUMERIC  NOT NULL,
        UnidadProducida_idUnidadProducidad NUMERIC  NOT NULL,

        CONSTRAINT pk_lista_precio_mayorista_01 PRIMARY KEY (idListaPrecioMayorista, ClienteJuridico_idClienteJuridico, UnidadProducida_idUnidadProducidad)
    );

    CREATE TABLE LoteMateriaPrima (
         idLoteMateriaPrima  NUMERIC  NOT NULL UNIQUE,
         costoAdquisicion    NUMERIC  NOT NULL,
         nombre              VARCHAR(150)  NOT NULL,
         descripcion         VARCHAR(600)  NOT NULL,
         Material_idMaterial NUMERIC  NOT NULL,

        CONSTRAINT pk_lote_materia_prima_01 PRIMARY KEY (idLoteMateriaPrima)
    );

    CREATE TABLE LoteProduccion (
        idLote      NUMERIC  NOT NULL,
        fechaInicio DATE  NOT NULL,
        fechaFin    DATE  NOT NULL,

        CONSTRAINT pk_lote_produccion_01 PRIMARY KEY (idLote)
    );

    CREATE TABLE Lugar (
         idLugar       NUMERIC  NOT NULL UNIQUE,
         nombre        VARCHAR(150)  NOT NULL,
         tipo          VARCHAR(150)  NOT NULL,
         codigoPostal  NUMERIC  NOT NULL,
         Lugar_idLugar NUMERIC,

        CONSTRAINT pk_lugar_01 PRIMARY KEY (idLugar)
    );

    CREATE TABLE ManifiestoCarga (
         idManifiestoCarga         NUMERIC  NOT NULL UNIQUE,
         cantidadPaletas           NUMERIC  NOT NULL,
         cantidadCajasMaster       NUMERIC  NOT NULL,
         OrdenCompra_idOrdenCompra NUMERIC  NOT NULL,
         Transporte_idTransporte   NUMERIC  NOT NULL,

        CONSTRAINT pk_manifiesto_carga_01 PRIMARY KEY (idManifiestoCarga)
    );

    CREATE TABLE Material (
         idMaterial  NUMERIC  NOT NULL UNIQUE,
         nombre      VARCHAR(150)  NOT NULL,
         descripcion VARCHAR(600)  NOT NULL,

        CONSTRAINT pk_material_01 PRIMARY KEY (idMaterial)
    );

    CREATE TABLE MaterialDiseño (
        idMaterialDiseño    NUMERIC  NOT NULL UNIQUE,
        cantidad            NUMERIC  NOT NULL,
        Diseño_idDiseño     NUMERIC  NOT NULL,
        Pieza_idPieza       NUMERIC  NOT NULL,
        Material_idMaterial NUMERIC  NOT NULL,

        CONSTRAINT pk_material_diseño_01 PRIMARY KEY (idMaterialDiseño, Diseño_idDiseño)
    );

    CREATE TABLE Membresia (
        idMembresia                     NUMERIC  NOT NULL UNIQUE,
        nombre                          VARCHAR(150)  NOT NULL,
        descripcion                     VARCHAR(600)  NOT NULL,
        ClienteNatural_idClienteNatural NUMERIC  NOT NULL,

        CONSTRAINT pk_membresia_01 PRIMARY KEY (idMembresia)
    );

    CREATE TABLE MetaMensual (
         idMetaMensual      NUMERIC  NOT NULL UNIQUE,
         fechaInicio        DATE  NOT NULL,
         fechaFin           DATE  NOT NULL,
         porcentajeComision NUMERIC  NOT NULL,

        CONSTRAINT pk_meta_mensual_01 PRIMARY KEY (idMetaMensual)
    );

    CREATE TABLE MoldeRostro (
         idMoldeRostro NUMERIC  NOT NULL UNIQUE,
         nombre        VARCHAR(150)  NOT NULL,
         descripcion   VARCHAR(600)  NOT NULL,
         añoPatente    DATE  NOT NULL,

        CONSTRAINT pk_molde_rostro_01 PRIMARY KEY (idMoldeRostro)
    );

    CREATE TABLE MonitorActividadSopechosa (
         idMonitorActividadSopechosa NUMERIC  NOT NULL UNIQUE,
         fechaHora                   DATE  NOT NULL,
         ClienteNatural_idClienteNatural NUMERIC NOT NULL,

        CONSTRAINT pk_monitor_actividad_sospechosa_01 PRIMARY KEY (idMonitorActividadSopechosa)
    );

    CREATE TABLE ObjetivoGlobal (
         idObjetivoGlobal  NUMERIC  NOT NULL UNIQUE,
         volumenVentas     NUMERIC  NOT NULL,
         porcentajeRegalia NUMERIC  NOT NULL,

        CONSTRAINT pk_objetivo_global_01 PRIMARY KEY (idObjetivoGlobal)
    );

    CREATE TABLE ObjetivoGlobalProducto (
         idObjetivoGlobalProducto        NUMERIC  NOT NULL UNIQUE,
         objetivoSuperado                CHAR(1)  NOT NULL ,
         Producto_idProducto             NUMERIC  NOT NULL ,
         ObjetivoGlobal_idObjetivoGlobal NUMERIC  NOT NULL,

        CONSTRAINT pk_objetivo_global_producto_01 PRIMARY KEY (idObjetivoGlobalProducto, Producto_idProducto, ObjetivoGlobal_idObjetivoGlobal)
    );

    CREATE TABLE OrdenCompra (
         idOrdenCompra                     NUMERIC  NOT NULL UNIQUE,
         fechaEmision                      DATE  NOT NULL ,
         fechaVencimiento                  DATE  NOT NULL ,
         especificacionesTecnicas          VARCHAR(600)  NOT NULL ,
         precioUnitario                    NUMERIC  NOT NULL ,
         subTotal                          NUMERIC  NOT NULL ,
         impuestos                         NUMERIC  NOT NULL ,
         ClienteJuridico_idClienteJuridico NUMERIC  NOT NULL ,
         BackOrder_idBackOrder             NUMERIC  NOT NULL,

        CONSTRAINT pk_orden_compra_01 PRIMARY KEY (idOrdenCompra)
    );
    CREATE UNIQUE INDEX OrdenCompra__IDX ON OrdenCompra (
         BackOrder_idBackOrder ASC
    );

    CREATE TABLE OrdenCompraDescuento (
         idOrdenCompraDescuento    NUMERIC  NOT NULL UNIQUE,
         monto                     NUMERIC NOT NULL,
         OrdenCompra_idOrdenCompra NUMERIC  NOT NULL ,
         Descuento_idDescuento     NUMERIC  NOT NULL,

        CONSTRAINT pk_orden_compra_descuento_01 PRIMARY KEY (idOrdenCompraDescuento, OrdenCompra_idOrdenCompra, Descuento_idDescuento)
    );

    CREATE TABLE OrdenVenta (
         idOrdenVenta         NUMERIC  NOT NULL UNIQUE,
         fechaHoraEmision     DATE  NOT NULL ,
         fechaHoraVencimiento DATE  NOT NULL ,
         estatusPendientePago CHAR (1)  NOT NULL,

        CONSTRAINT pk_orden_venta_01 PRIMARY KEY (idOrdenVenta)
    );

    CREATE TABLE Pack (
         idPack               NUMERIC  NOT NULL UNIQUE,
         Producto_idProducto  NUMERIC  NOT NULL ,
         Producto_idProducto2 NUMERIC  NOT NULL,

        CONSTRAINT pk_pack_01 PRIMARY KEY (idPack, Producto_idProducto, Producto_idProducto2)
    );

    CREATE TABLE PagoJuridico (
        idPago      NUMERIC NOT NULL UNIQUE,
        monto       NUMERIC NOT NULL,
        fechaHora   DATE NOT NULL,

        Cheque_id   NUMERIC,
        Cripto_id   NUMERIC,
        Efectivo_id NUMERIC,
        PayPal_id   NUMERIC,
        Swift_id    NUMERIC,
        TarjCred_id NUMERIC,
        TarjDeb_id  NUMERIC,

        CONSTRAINT pk_pago_juridico_01 PRIMARY KEY (idPago),

        CONSTRAINT arc_pago_juridico_metodo CHECK (
          (Cheque_id IS NOT NULL AND Cripto_id IS NULL AND Efectivo_id IS NULL AND PayPal_id IS NULL AND Swift_id IS NULL AND TarjCred_id IS NULL AND TarjDeb_id IS NULL) OR
          (Cripto_id IS NOT NULL AND Cheque_id IS NULL AND Efectivo_id IS NULL AND PayPal_id IS NULL AND Swift_id IS NULL AND TarjCred_id IS NULL AND TarjDeb_id IS NULL) OR
          (Efectivo_id IS NOT NULL AND Cheque_id IS NULL AND Cripto_id IS NULL AND PayPal_id IS NULL AND Swift_id IS NULL AND TarjCred_id IS NULL AND TarjDeb_id IS NULL) OR
          (PayPal_id IS NOT NULL AND Cheque_id IS NULL AND Cripto_id IS NULL AND Efectivo_id IS NULL AND Swift_id IS NULL AND TarjCred_id IS NULL AND TarjDeb_id IS NULL) OR
          (Swift_id IS NOT NULL AND Cheque_id IS NULL AND Cripto_id IS NULL AND Efectivo_id IS NULL AND PayPal_id IS NULL AND TarjCred_id IS NULL AND TarjDeb_id IS NULL) OR
          (TarjCred_id IS NOT NULL AND Cheque_id IS NULL AND Cripto_id IS NULL AND Efectivo_id IS NULL AND PayPal_id IS NULL AND Swift_id IS NULL AND TarjDeb_id IS NULL) OR
          (TarjDeb_id IS NOT NULL AND Cheque_id IS NULL AND Cripto_id IS NULL AND Efectivo_id IS NULL AND PayPal_id IS NULL AND Swift_id IS NULL AND TarjCred_id IS NULL)
          )
    );

    CREATE TABLE PagoNatural (
        idPagoNatural   NUMERIC NOT NULL UNIQUE,
        Compra_idCompra NUMERIC NOT NULL,

        Cheque_id       NUMERIC,
        Cripto_id       NUMERIC,
        Efectivo_id     NUMERIC,
        PayPal_id       NUMERIC,
        Swift_id        NUMERIC,
        TarjCred_id     NUMERIC,
        TarjDeb_id      NUMERIC,

        CONSTRAINT pk_pago_natural_01 PRIMARY KEY (idPagoNatural, Compra_idCompra),

        CONSTRAINT arc_pago_natural_metodo CHECK (
         (Cheque_id IS NOT NULL AND Cripto_id IS NULL AND Efectivo_id IS NULL AND PayPal_id IS NULL AND Swift_id IS NULL AND TarjCred_id IS NULL AND TarjDeb_id IS NULL) OR
         (Cripto_id IS NOT NULL AND Cheque_id IS NULL AND Efectivo_id IS NULL AND PayPal_id IS NULL AND Swift_id IS NULL AND TarjCred_id IS NULL AND TarjDeb_id IS NULL) OR
         (Efectivo_id IS NOT NULL AND Cheque_id IS NULL AND Cripto_id IS NULL AND PayPal_id IS NULL AND Swift_id IS NULL AND TarjCred_id IS NULL AND TarjDeb_id IS NULL) OR
         (PayPal_id IS NOT NULL AND Cheque_id IS NULL AND Cripto_id IS NULL AND Efectivo_id IS NULL AND Swift_id IS NULL AND TarjCred_id IS NULL AND TarjDeb_id IS NULL) OR
         (Swift_id IS NOT NULL AND Cheque_id IS NULL AND Cripto_id IS NULL AND Efectivo_id IS NULL AND PayPal_id IS NULL AND TarjCred_id IS NULL AND TarjDeb_id IS NULL) OR
         (TarjCred_id IS NOT NULL AND Cheque_id IS NULL AND Cripto_id IS NULL AND Efectivo_id IS NULL AND PayPal_id IS NULL AND Swift_id IS NULL AND TarjDeb_id IS NULL) OR
         (TarjDeb_id IS NOT NULL AND Cheque_id IS NULL AND Cripto_id IS NULL AND Efectivo_id IS NULL AND PayPal_id IS NULL AND Swift_id IS NULL AND TarjCred_id IS NULL)
         )
    );

    CREATE TABLE PayPal (
         idMetodoPago        NUMERIC  NOT NULL UNIQUE,
         comisionRetenida  NUMERIC  NOT NULL ,
         codigoTransaccion VARCHAR(200)  NOT NULL ,
         correoAsociado    VARCHAR(200)  NOT NULL,

        CONSTRAINT pk_paypal_01 PRIMARY KEY (idMetodoPago)
    );

    CREATE TABLE Permiso (
         idPermiso NUMERIC  NOT NULL UNIQUE,
         nombre    VARCHAR(150)  NOT NULL,
        CONSTRAINT pk_permiso_01 PRIMARY KEY (idPermiso)
    );

    CREATE TABLE Pieza (
         idPieza               NUMERIC  NOT NULL UNIQUE,
         nombre                VARCHAR(150)  NOT NULL ,
         descripcion           VARCHAR(600)  NOT NULL ,
         Color_idColor         NUMERIC  NOT NULL ,
         TipoPieza_idTipoPieza NUMERIC  NOT NULL,

        CONSTRAINT pk_pieza_01 PRIMARY KEY (idPieza)
    );

    CREATE TABLE PiezaProducto (
         idPiezaProducto     NUMERIC  NOT NULL UNIQUE,
         Pieza_idPieza       NUMERIC  NOT NULL ,
         Producto_idProducto NUMERIC  NOT NULL,

        CONSTRAINT pk_pieza_producto_01 PRIMARY KEY (idPiezaProducto, Pieza_idPieza, Producto_idProducto)
    );

    CREATE TABLE Producto (
         idProducto                      NUMERIC  NOT NULL UNIQUE,
         nombre                          VARCHAR(150)  NOT NULL ,
         descripcion                     VARCHAR(600)  NOT NULL ,
         fechaSalida                     DATE  NOT NULL ,
         Diseño_idDiseño                 NUMERIC  NOT NULL ,
         LoteProduccion_idLote           NUMERIC  NOT NULL ,
         precioLanzamiento               NUMERIC  NOT NULL ,
         limiteCompraPorUsuario          NUMERIC  NOT NULL ,
         BackOrder_idBackOrder           NUMERIC,

        CONSTRAINT pk_producto_01 PRIMARY KEY (idProducto)
    );

    CREATE TABLE Profesion (
         idProfesion NUMERIC  NOT NULL UNIQUE,
         nombre      VARCHAR(150)  NOT NULL ,
         descripcion VARCHAR(600)  NOT NULL,

        CONSTRAINT pk_profesion_01 PRIMARY KEY (idProfesion)
    );

    CREATE TABLE Prueba (
         idPrueba          NUMERIC NOT NULL ,
         nombrePrueba      VARCHAR(150) NOT NULL ,
         descripcionPrueba VARCHAR(600) NOT NULL ,
         resultado         VARCHAR(150) ,
         tipoPrueba        VARCHAR(150) NOT NULL ,
         Diseño_idDiseño   NUMERIC NOT NULL,

        CONSTRAINT pk_prueba_01 PRIMARY KEY (idPrueba)
    ) ;

    CREATE TABLE PruebaEmpleado (
         idPruebaEmpleado    NUMERIC NOT NULL ,
         fechaInicio         DATE NOT NULL ,
         fechaFin            DATE ,
         Prueba_idPrueba     NUMERIC NOT NULL ,
         Empleado_idEmpleado NUMERIC NOT NULL,

        CONSTRAINT pk_prueba_empleado_01 PRIMARY KEY (idPruebaEmpleado, Prueba_idPrueba, Empleado_idEmpleado)
    );

    CREATE TABLE PuestoTrabajo (
         id          NUMERIC  NOT NULL UNIQUE,
         nombre      VARCHAR(150)  NOT NULL ,
         descripcion VARCHAR(600)  NOT NULL,

        CONSTRAINT pk_puesto_trabajo_01 PRIMARY KEY (id)
    );

    CREATE TABLE Puja (
         idPuja                          NUMERIC  NOT NULL UNIQUE,
         fechaHora                       DATE  NOT NULL ,
         monto                           NUMERIC  NOT NULL ,
         ClienteNatural_idClienteNatural NUMERIC  NOT NULL ,
         Subasta_idSubasta               NUMERIC  NOT NULL ,

        CONSTRAINT pk_puja_01 PRIMARY KEY (idPuja, ClienteNatural_idClienteNatural, Subasta_idSubasta)
    );

    CREATE TABLE Regalia (
         idRegalia NUMERIC  NOT NULL UNIQUE,
         monto     NUMERIC  NOT NULL ,
         fechaHora DATE  NOT NULL,

        CONSTRAINT pk_regalia_01 PRIMARY KEY (idRegalia)
    );

    CREATE TABLE Restriccion (
         idRestriccion NUMERIC  NOT NULL UNIQUE,
         nombre        VARCHAR(150)  NOT NULL ,
         descripcion   VARCHAR(600)  NOT NULL,

        CONSTRAINT pk_restriccion_01 PRIMARY KEY (idRestriccion)
    );

    CREATE TABLE RestriccionDiseño (
         idRestriccionDiseño       NUMERIC  NOT NULL UNIQUE,
         nombre                    VARCHAR(150)  NOT NULL ,
         descripcion               VARCHAR(600)  NOT NULL ,
         Diseño_idDiseño           NUMERIC  NOT NULL ,
         Restriccion_idRestriccion NUMERIC  NOT NULL ,
         TipoCuerpo_idTipoCuerpo   NUMERIC  NOT NULL,

        CONSTRAINT pk_restriccion_diseño_01 PRIMARY KEY (idRestriccionDiseño, Diseño_idDiseño)
    );

    CREATE TABLE Rol (
         idRol       NUMERIC  NOT NULL UNIQUE,
         nombre      VARCHAR(150)  NOT NULL ,
         descripcion VARCHAR(150)  NOT NULL ,

        CONSTRAINT pk_rol_01 PRIMARY KEY (idRol)
    );

    CREATE TABLE RolPermiso (
         idRolPermiso       NUMERIC  NOT NULL UNIQUE,
         Rol_idRol          NUMERIC  NOT NULL ,
         Permisos_idPermiso NUMERIC  NOT NULL,

        CONSTRAINT pk_rol_permiso_01 PRIMARY KEY (idRolPermiso, Rol_idRol, Permisos_idPermiso)
    );

    CREATE TABLE Sancion (
         idSancion                       NUMERIC  NOT NULL UNIQUE,
         fechaHoraInicio                 DATE  NOT NULL ,
         fechaHoraDin                    DATE  NOT NULL ,
         nombre                          VARCHAR(150)  NOT NULL ,
         descripcion                     VARCHAR(600)  NOT NULL ,
         ClienteNatural_idClienteNatural NUMERIC  NOT NULL,

        CONSTRAINT pk_sancion_01 PRIMARY KEY (idSancion)
    );

    CREATE TABLE StockClienteNatural (
         idStockClienteNatural              NUMERIC  NOT NULL UNIQUE,
         UnidadProducida_idUnidadProducidad NUMERIC  NOT NULL ,
         ClienteNatural_idClienteNatural    NUMERIC  NOT NULL ,
         condicionFisica_idCondicionFisica  NUMERIC  NOT NULL ,
         Subasta_idSubasta                  NUMERIC  NOT NULL ,

        CONSTRAINT pk_stock_cliente_natural_01 PRIMARY KEY (idStockClienteNatural, UnidadProducida_idUnidadProducidad, ClienteNatural_idClienteNatural)
    );

    CREATE TABLE Subasta (
         idSubasta               NUMERIC  NOT NULL UNIQUE,
         fechaHoraInicio         DATE  NOT NULL ,
         fechaHoraFin            DATE  NOT NULL ,
         precioBase              NUMERIC  NOT NULL ,
         incrementoMinimo        NUMERIC  NOT NULL ,
         OrdenVenta_idOrdenVenta NUMERIC  NOT NULL ,

        CONSTRAINT pk_subasta_01 PRIMARY KEY (idSubasta)
    );

    CREATE TABLE SubEnsamblaje (
         idSubEnsamblaje NUMERIC  NOT NULL UNIQUE,
         cantidad        NUMERIC  NOT NULL ,
         Pieza_idPieza   NUMERIC  NOT NULL ,
         Pieza_idPieza2  NUMERIC  NOT NULL,

        CONSTRAINT pk_sub_ensamblaje_01 PRIMARY KEY (idSubEnsamblaje, Pieza_idPieza, Pieza_idPieza2)
    );

    CREATE TABLE Swift (
         idMetodoPago           NUMERIC  NOT NULL UNIQUE,
         codigoReferencia  VARCHAR(200)  NOT NULL ,
         codigoSwiftOrigen VARCHAR(200)  NOT NULL,

        CONSTRAINT pk_swift_01 PRIMARY KEY (idMetodoPago)
    );

    CREATE TABLE TarjetaCredito (
         idMetodoPago     NUMERIC  NOT NULL UNIQUE,
         numeroTarjeta        NUMERIC  NOT NULL ,
         hashTarjeta          VARCHAR(200)  NOT NULL ,
         ultimosCuatroDigitos NUMERIC  NOT NULL ,
         franquicia           VARCHAR(200)  NOT NULL ,
         nombreTitular        VARCHAR(200)  NOT NULL,

        CONSTRAINT pk_tarjeta_credito_01 PRIMARY KEY (idMetodoPago)
    );

    CREATE TABLE TarjetaDebito (
         idMetodoPago NUMERIC  NOT NULL UNIQUE ,
         numeroTarjeta    NUMERIC  NOT NULL ,
         hashTarjeta      VARCHAR(200)  NOT NULL ,
         nombreTitular    VARCHAR(200)  NOT NULL,

        CONSTRAINT pk_tarjeta_debito_01 PRIMARY KEY (idMetodoPago)
    );

    CREATE TABLE Telefono (
         idTelefono                        NUMERIC  NOT NULL UNIQUE,
         codigoPais                        NUMERIC  NOT NULL ,
         codigoOperadora                   NUMERIC  NOT NULL ,
         numeroAbonado                     NUMERIC  NOT NULL ,
         ClienteJuridico_idClienteJuridico NUMERIC,
         ClienteNatural_idClienteNatural   NUMERIC,

        CONSTRAINT arc_telefono_01 CHECK ( (  (ClienteNatural_idClienteNatural IS NOT NULL
                                   AND (ClienteJuridico_idClienteJuridico IS NULL) ) OR (  (ClienteJuridico_idClienteJuridico IS NOT NULL)
                                   AND (ClienteNatural_idClienteNatural IS NULL) ) ) ),
        CONSTRAINT pk_telefono_01 PRIMARY KEY (idTelefono)
    );

    CREATE TABLE TipoCuerpo (
         idTipoCuerpo NUMERIC  NOT NULL UNIQUE,
         nombre       VARCHAR(150)  NOT NULL ,
         descripcion  VARCHAR(600)  NOT NULL,

        CONSTRAINT pk_tipo_cuerpo_01 PRIMARY KEY (idTipoCuerpo)
    );

    CREATE TABLE TipoDiseño (
         idTipoDiseño NUMERIC  NOT NULL UNIQUE,
         nombre       VARCHAR(150)  NOT NULL,

        CONSTRAINT pk_tipo_diseño_01 PRIMARY KEY (idTipoDiseño)
    );

    CREATE TABLE TipoPieza (
         idTipoPieza NUMERIC  NOT NULL UNIQUE,
         nombre      VARCHAR(150)  NOT NULL,

        CONSTRAINT pk_tipo_pieza_01 PRIMARY KEY (idTipoPieza)
    );

    CREATE TABLE TipoRelacion (
         idTipoRelacion   NUMERIC  NOT NULL UNIQUE,
         nombreRelacion   VARCHAR(150)  NOT NULL ,
         Diseño_idDiseño  NUMERIC  NOT NULL ,
         Diseño_idDiseño2 NUMERIC  NOT NULL,

        CONSTRAINT pk_tipo_relacion_01 PRIMARY KEY (idTipoRelacion, Diseño_idDiseño, Diseño_idDiseño2)
    );

    CREATE TABLE TipoUbicacionStock (
         idTipoUbicacionStock NUMERIC  NOT NULL UNIQUE,
         nombre               VARCHAR(150)  NOT NULL,
         direccion            VARCHAR(150)  NOT NULL,
         Lugar_idLugar        NUMERIC  NOT NULL,
         UnidadProducida_idUnidadProducidad NUMERIC NOT NULL,

        CONSTRAINT pk_tipo_ubicacion_stock_01 PRIMARY KEY (idTipoUbicacionStock)
    );

    CREATE TABLE TonoPiel (
         idTonoPiel        NUMERIC  NOT NULL UNIQUE,
         nombre            VARCHAR(150)  NOT NULL ,
         escalaFitzpatrick DATE  NOT NULL ,
         valorClaridad     VARCHAR(50)  NOT NULL ,
         luminosidad       NUMERIC  NOT NULL,

        CONSTRAINT pk_tono_piel_01 PRIMARY KEY (idTonoPiel)
    );

    CREATE TABLE Transporte (
         idTransporte      NUMERIC  NOT NULL UNIQUE,
         matricula         VARCHAR(150)  NOT NULL ,
         nombreConductor   VARCHAR(150)  NOT NULL ,
         apellidoConductor VARCHAR(150)  NOT NULL ,

        CONSTRAINT pk_transporte_01 PRIMARY KEY (idTransporte)
    );

    CREATE TABLE Turno (
         idTurno           NUMERIC  NOT NULL UNIQUE,
         porcentajeRecargo NUMERIC  NOT NULL ,
         nombre            VARCHAR(150)  NOT NULL ,

        CONSTRAINT pk_turno_01 PRIMARY KEY (idTurno)
    );

    CREATE TABLE TurnoEmpleado (
         idTurnoEmpleado NUMERIC  NOT NULL UNIQUE,
         fecha           DATE  NOT NULL ,
         feriado         CHAR(1)  NOT NULL ,
         Empleado_idEmpleado     NUMERIC  NOT NULL ,
         Turno_idTurno   NUMERIC  NOT NULL,

        CONSTRAINT pk_turno_empleado_01 PRIMARY KEY (idTurnoEmpleado, Empleado_idEmpleado, Turno_idTurno)
    );

    CREATE TABLE TurnoHorario (
         idTurnoHorario    NUMERIC NOT NULL ,
         Horario_idHorario NUMERIC NOT NULL ,
         Turno_idTurno     NUMERIC NOT NULL,

        CONSTRAINT pk_turno_horario_01 PRIMARY KEY (idTurnoHorario, Horario_idHorario, Turno_idTurno)
    );

    CREATE TABLE UnidadProducida (
         idUnidadProducidad                 NUMERIC  NOT NULL UNIQUE,
         fechaSalida                        DATE  NOT NULL ,
         nombre                             VARCHAR(150)  NOT NULL ,
         LoteProduccion_idLote              NUMERIC  NOT NULL ,

        CONSTRAINT pk_unidad_producida_01 PRIMARY KEY (idUnidadProducidad)
    );

    CREATE TABLE Usuario (
         idUsuario                       NUMERIC  NOT NULL UNIQUE,
         nombreUsuario                   VARCHAR(50)  NOT NULL ,
         correoElectronico               VARCHAR(100)  NOT NULL ,
         contraseña                      VARCHAR(255)  NOT NULL ,
         estado                          VARCHAR(20)  NOT NULL ,
         fechaRegistro                   DATE  NOT NULL ,
         Empleado_idEmpleado             NUMERIC NOT NULL,
         Rol_idRol NUMERIC NOT NULL,
         ClienteNatural_idClienteNatural NUMERIC,

        CONSTRAINT pk_usuario_01 PRIMARY KEY (idUsuario)
    );

    CREATE TABLE ValoracionMercado (
         idValoracionMercado                NUMERIC  NOT NULL UNIQUE,
         fechaValoracion                    DATE  NOT NULL ,
         precioDelMercado                   NUMERIC  NOT NULL ,
         UnidadProducida_idUnidadProducidad NUMERIC  NOT NULL,

        CONSTRAINT pk_valoracion_mercado_01 PRIMARY KEY (idValoracionMercado)
    );

    CREATE TABLE Caja (
        idCaja    NUMERIC  NOT NULL,
        nombre    VARCHAR(150)  NOT NULL,
        capacidad NUMERIC  NOT NULL,

        CONSTRAINT pk_caja_01 PRIMARY KEY (idCaja)
    );

    /* CREATE DE LAS SECUENCIAS */

    CREATE SEQUENCE Caja_SEQ START WITH 1 INCREMENT BY 1;
    CREATE SEQUENCE Ambiente_SEQ START WITH 1 INCREMENT BY 1;
    CREATE SEQUENCE AsignacionMeta_SEQ START WITH 1 INCREMENT BY 1;
    CREATE SEQUENCE Asistencia_SEQ START WITH 1 INCREMENT BY 1;
    CREATE SEQUENCE AutorDiseño_SEQ START WITH 1 INCREMENT BY 1;
    CREATE SEQUENCE BackOrder_SEQ START WITH 1 INCREMENT BY 1;
    CREATE SEQUENCE ChequeCorporativo_SEQ START WITH 1 INCREMENT BY 1;
    CREATE SEQUENCE ClasificacionExclusividad_SEQ START WITH 1 INCREMENT BY 1;
    CREATE SEQUENCE ClasificacionHistorica_SEQ START WITH 1 INCREMENT BY 1;
    CREATE SEQUENCE ClienteJuridico_SEQ START WITH 1 INCREMENT BY 1;
    CREATE SEQUENCE ClienteNatural_SEQ START WITH 1 INCREMENT BY 1;
    CREATE SEQUENCE Color_SEQ START WITH 1 INCREMENT BY 1;
    CREATE SEQUENCE ComisionVenta_SEQ START WITH 1 INCREMENT BY 1;
    CREATE SEQUENCE Compra_SEQ START WITH 1 INCREMENT BY 1;
    CREATE SEQUENCE CompraDescuento_SEQ START WITH 1 INCREMENT BY 1;
    CREATE SEQUENCE Conciliacion_SEQ START WITH 1 INCREMENT BY 1;
    CREATE SEQUENCE CondicionFisica_SEQ START WITH 1 INCREMENT BY 1;
    CREATE SEQUENCE Courier_SEQ START WITH 1 INCREMENT BY 1;
    CREATE SEQUENCE CriptoActivo_SEQ START WITH 1 INCREMENT BY 1;
    CREATE SEQUENCE CurriculumVitae_SEQ START WITH 1 INCREMENT BY 1;
    CREATE SEQUENCE Departamento_SEQ START WITH 1 INCREMENT BY 1;
    CREATE SEQUENCE Descuento_SEQ START WITH 1 INCREMENT BY 1;
    CREATE SEQUENCE DespachoNatural_SEQ START WITH 1 INCREMENT BY 1;
    CREATE SEQUENCE DetalleCompraJuridico_SEQ START WITH 1 INCREMENT BY 1;
    CREATE SEQUENCE DetalleCompraNatural_SEQ START WITH 1 INCREMENT BY 1;
    CREATE SEQUENCE DevolucionJuridica_SEQ START WITH 1 INCREMENT BY 1;
    CREATE SEQUENCE DevolucionNatural_SEQ START WITH 1 INCREMENT BY 1;
    CREATE SEQUENCE Diseño_SEQ START WITH 1 INCREMENT BY 1;
    CREATE SEQUENCE DiseñoAmbiente_SEQ START WITH 1 INCREMENT BY 1;
    CREATE SEQUENCE Efectivo_SEQ START WITH 1 INCREMENT BY 1;
    CREATE SEQUENCE Empleado_SEQ START WITH 1 INCREMENT BY 1;
    CREATE SEQUENCE EstadoOrden_SEQ START WITH 1 INCREMENT BY 1;
    CREATE SEQUENCE Estatus_SEQ START WITH 1 INCREMENT BY 1;
    CREATE SEQUENCE Fase_SEQ START WITH 1 INCREMENT BY 1;
    CREATE SEQUENCE FaseEmpleado_SEQ START WITH 1 INCREMENT BY 1;
    CREATE SEQUENCE HistoricoEmpleado_SEQ START WITH 1 INCREMENT BY 1;
    CREATE SEQUENCE HistoricoEstado_SEQ START WITH 1 INCREMENT BY 1;
    CREATE SEQUENCE HistoricoEstatus_SEQ START WITH 1 INCREMENT BY 1;
    CREATE SEQUENCE Horario_SEQ START WITH 1 INCREMENT BY 1;
    CREATE SEQUENCE InsumoProduccion_SEQ START WITH 1 INCREMENT BY 1;
    CREATE SEQUENCE ListaPrecioMayorista_SEQ START WITH 1 INCREMENT BY 1;
    CREATE SEQUENCE LoteMateriaPrima_SEQ START WITH 1 INCREMENT BY 1;
    CREATE SEQUENCE LoteProduccion_SEQ START WITH 1 INCREMENT BY 1;
    CREATE SEQUENCE Lugar_SEQ START WITH 1 INCREMENT BY 1;
    CREATE SEQUENCE ManifiestoCarga_SEQ START WITH 1 INCREMENT BY 1;
    CREATE SEQUENCE Material_SEQ START WITH 1 INCREMENT BY 1;
    CREATE SEQUENCE MaterialDiseño_SEQ START WITH 1 INCREMENT BY 1;
    CREATE SEQUENCE Membresia_SEQ START WITH 1 INCREMENT BY 1;
    CREATE SEQUENCE MetaMensual_SEQ START WITH 1 INCREMENT BY 1;
    CREATE SEQUENCE MoldeRostro_SEQ START WITH 1 INCREMENT BY 1;
    CREATE SEQUENCE MonitorActividadSopechosa_SEQ START WITH 1 INCREMENT BY 1;
    CREATE SEQUENCE ObjetivoGlobal_SEQ START WITH 1 INCREMENT BY 1;
    CREATE SEQUENCE ObjetivoGlobalProducto_SEQ START WITH 1 INCREMENT BY 1;
    CREATE SEQUENCE OrdenCompra_SEQ START WITH 1 INCREMENT BY 1;
    CREATE SEQUENCE OrdenCompraDescuento_SEQ START WITH 1 INCREMENT BY 1;
    CREATE SEQUENCE OrdenVenta_SEQ START WITH 1 INCREMENT BY 1;
    CREATE SEQUENCE Pack_SEQ START WITH 1 INCREMENT BY 1;
    CREATE SEQUENCE PagoJuridico_SEQ START WITH 1 INCREMENT BY 1;
    CREATE SEQUENCE PagoNatural_SEQ START WITH 1 INCREMENT BY 1;
    CREATE SEQUENCE PayPal_SEQ START WITH 1 INCREMENT BY 1;
    CREATE SEQUENCE Permiso_SEQ START WITH 1 INCREMENT BY 1;
    CREATE SEQUENCE Pieza_SEQ START WITH 1 INCREMENT BY 1;
    CREATE SEQUENCE PiezaProducto_SEQ START WITH 1 INCREMENT BY 1;
    CREATE SEQUENCE Producto_SEQ START WITH 1 INCREMENT BY 1;
    CREATE SEQUENCE Profesion_SEQ START WITH 1 INCREMENT BY 1;
    CREATE SEQUENCE Prueba_SEQ START WITH 1 INCREMENT BY 1;
    CREATE SEQUENCE PruebaEmpleado_SEQ START WITH 1 INCREMENT BY 1;
    CREATE SEQUENCE PuestoTrabajo_SEQ START WITH 1 INCREMENT BY 1;
    CREATE SEQUENCE Puja_SEQ START WITH 1 INCREMENT BY 1;
    CREATE SEQUENCE Regalia_SEQ START WITH 1 INCREMENT BY 1;
    CREATE SEQUENCE Restriccion_SEQ START WITH 1 INCREMENT BY 1;
    CREATE SEQUENCE RestriccionDiseño_SEQ START WITH 1 INCREMENT BY 1;
    CREATE SEQUENCE Rol_SEQ START WITH 1 INCREMENT BY 1;
    CREATE SEQUENCE RolPermiso_SEQ START WITH 1 INCREMENT BY 1;
    CREATE SEQUENCE Sancion_SEQ START WITH 1 INCREMENT BY 1;
    CREATE SEQUENCE StockClienteNatural_SEQ START WITH 1 INCREMENT BY 1;
    CREATE SEQUENCE Subasta_SEQ START WITH 1 INCREMENT BY 1;
    CREATE SEQUENCE SubEnsamblaje_SEQ START WITH 1 INCREMENT BY 1;
    CREATE SEQUENCE Swift_SEQ START WITH 1 INCREMENT BY 1;
    CREATE SEQUENCE TarjetaCredito_SEQ START WITH 1 INCREMENT BY 1;
    CREATE SEQUENCE TarjetaDebito_SEQ START WITH 1 INCREMENT BY 1;
    CREATE SEQUENCE Telefono_SEQ START WITH 1 INCREMENT BY 1;
    CREATE SEQUENCE TipoCuerpo_SEQ START WITH 1 INCREMENT BY 1;
    CREATE SEQUENCE TipoDiseño_SEQ START WITH 1 INCREMENT BY 1;
    CREATE SEQUENCE TipoPieza_SEQ START WITH 1 INCREMENT BY 1;
    CREATE SEQUENCE TipoRelacion_SEQ START WITH 1 INCREMENT BY 1;
    CREATE SEQUENCE TipoUbicacionStock_SEQ START WITH 1 INCREMENT BY 1;
    CREATE SEQUENCE TonoPiel_SEQ START WITH 1 INCREMENT BY 1;
    CREATE SEQUENCE Transporte_SEQ START WITH 1 INCREMENT BY 1;
    CREATE SEQUENCE Turno_SEQ START WITH 1 INCREMENT BY 1;
    CREATE SEQUENCE TurnoEmpleado_SEQ START WITH 1 INCREMENT BY 1;
    CREATE SEQUENCE TurnoHorario_SEQ START WITH 1 INCREMENT BY 1;
    CREATE SEQUENCE UnidadProducida_SEQ START WITH 1 INCREMENT BY 1;
    CREATE SEQUENCE Usuario_SEQ START WITH 1 INCREMENT BY 1;
    CREATE SEQUENCE ValoracionMercado_SEQ START WITH 1 INCREMENT BY 1;

    /* ///////////////////////////////////////////////////////////////////////////////////////////////////////////////////////// */

    /* GESTION DE USUARIOS */

    CREATE FUNCTION registrar_onboarding_completo(
        p_cedula NUMERIC,
        p_pnombre VARCHAR,
        p_snombre VARCHAR,
        p_papellido VARCHAR,
        p_sapellido VARCHAR,
        p_fechanacimiento DATE,
        p_direccion VARCHAR,
        p_id_lugar_empleado NUMERIC,
        
        p_username VARCHAR,
        p_correo VARCHAR,
        p_password VARCHAR,
        p_id_rol NUMERIC,
        
        p_id_departamento NUMERIC,
        p_id_puesto NUMERIC,
        p_salario NUMERIC,
        
        p_id_turno NUMERIC,
        p_id_tipo_ubicacion NUMERIC -- Requerido por HistoricoEmpleado
    ) RETURNS json AS $$
    DECLARE
        v_id_empleado NUMERIC;
        v_id_usuario NUMERIC;
        v_id_historico NUMERIC;
        v_id_turno_emp NUMERIC;
    BEGIN
        -- 1. Generación manual de IDs (Se recomienda usar secuencias como Empleado_SEQ.nextval)
        SELECT COALESCE(MAX(idEmpleado), 0) + 1 INTO v_id_empleado FROM Empleado;
        SELECT COALESCE(MAX(idUsuario), 0) + 1 INTO v_id_usuario FROM Usuario;
        SELECT COALESCE(MAX(idHistoricoEmpleado), 0) + 1 INTO v_id_historico FROM HistoricoEmpleado;
        SELECT COALESCE(MAX(idTurnoEmpleado), 0) + 1 INTO v_id_turno_emp FROM TurnoEmpleado;

        -- 2. Insertar Empleado Físico
        INSERT INTO Empleado (idEmpleado, cedula, pNombre, sNombre, pApellido, sApellido, fechaNacimiento, direccion, Lugar_idLugar)
        VALUES (v_id_empleado, p_cedula, p_pnombre, p_snombre, p_papellido, p_sapellido, p_fechanacimiento, p_direccion, p_id_lugar_empleado);

        -- 3. Insertar Histórico Laboral Inicial
        INSERT INTO HistoricoEmpleado (idHistoricoEmpleado, fechaInicio, salarioBase, Empleado_idEmpleado, Departamento_idDepartamento, PuestoTrabajo_id, TipoUbicacionStock_idTipoUbicacionStock)
        VALUES (v_id_historico, CURRENT_DATE, p_salario, v_id_empleado, p_id_departamento, p_id_puesto, p_id_tipo_ubicacion);

        -- 4. Asignar Turno
        INSERT INTO TurnoEmpleado (idTurnoEmpleado, fecha, feriado, Empleado_idEmpleado, Turno_idTurno)
        VALUES (v_id_turno_emp, CURRENT_DATE, 'N', v_id_empleado, p_id_turno);

        -- 5. Crear Credenciales (Usuario) con PGCrypto
        INSERT INTO Usuario (idUsuario, nombreUsuario, correoElectronico, contraseña, estado, fechaRegistro, Empleado_idEmpleado, Rol_idRol)
        VALUES (v_id_usuario, p_username, p_correo, crypt(p_password, gen_salt('bf')), 'Activo', CURRENT_DATE, v_id_empleado, p_id_rol);

        -- 6. Retorno de éxito
        RETURN json_build_object('success', true, 'mensaje', 'Onboarding completado exitosamente.');

    EXCEPTION WHEN OTHERS THEN
        -- Ante cualquier error de FK, Check o nulos, se activa el ROLLBACK automático de PostgreSQL
        RETURN json_build_object('success', false, 'mensaje', SQLERRM);
    END;
    $$ LANGUAGE plpgsql;

    /* ///////////////////////////////////////////////////////////////////////////////////////////////////////////////////////// */

    /* GESTION DE ROLES */

    CREATE FUNCTION actualizar_permisos_rol(
    p_idrol NUMERIC,     
    p_permisos JSON      
    ) RETURNS json AS $$
    DECLARE
        v_permiso_name VARCHAR;
        v_id_permiso NUMERIC;
        v_id_rolpermiso NUMERIC;
    BEGIN
        -- 1. Limpieza absoluta de la matriz vieja
        DELETE FROM RolPermiso WHERE Rol_idRol = p_idrol;

        -- 2. Inserción de la nueva matriz
        FOR v_permiso_name IN SELECT json_array_elements_text(p_permisos)
        LOOP
            SELECT idPermiso INTO v_id_permiso FROM Permiso WHERE nombre = v_permiso_name LIMIT 1;

            IF v_id_permiso IS NOT NULL THEN
                SELECT COALESCE(MAX(idRolPermiso), 0) + 1 INTO v_id_rolpermiso FROM RolPermiso;
                INSERT INTO RolPermiso (idRolPermiso, Rol_idRol, Permisos_idPermiso)
                VALUES (v_id_rolpermiso, p_idrol, v_id_permiso);
            END IF;
        END LOOP;

        RETURN json_build_object('success', true, 'mensaje', 'Matriz actualizada correctamente.');

    EXCEPTION WHEN OTHERS THEN
        RETURN json_build_object('success', false, 'mensaje', 'Fallo de integridad: ' || SQLERRM);
    END;
    $$ LANGUAGE plpgsql;

    CREATE OR REPLACE FUNCTION eliminar_rol_seguridad(
        p_idrol_a_borrar NUMERIC,
        p_idrol_destino NUMERIC -- El rol de salvavidas al que moveremos los usuarios
    ) RETURNS json AS $$
    BEGIN
        -- 1. Mudamos a todos los usuarios afectados al rol de destino
        UPDATE Usuario 
        SET Rol_idRol = p_idrol_destino 
        WHERE Rol_idRol = p_idrol_a_borrar;

        -- 2. Borramos las asociaciones de la matriz de permisos
        DELETE FROM RolPermiso WHERE Rol_idRol = p_idrol_a_borrar;

        -- 3. Ahora que el rol está huérfano de relaciones, lo eliminamos físicamente
        DELETE FROM Rol WHERE idRol = p_idrol_a_borrar;

        RETURN json_build_object('success', true, 'mensaje', 'Usuarios reasignados y rol eliminado con éxito.');
    END;
    $$ LANGUAGE plpgsql;

    CREATE OR REPLACE FUNCTION registrar_rol_seguridad(
        p_nombre TEXT,
        p_descripcion TEXT,
        p_permisos JSONB
    ) RETURNS json AS $$
    DECLARE
    v_id_rol NUMERIC;
    v_permiso_name TEXT;
        v_id_permiso NUMERIC;
        v_id_rolpermiso NUMERIC;
    BEGIN
        SELECT COALESCE(MAX(idRol), 0) + 1 INTO v_id_rol FROM Rol;

        INSERT INTO Rol (idRol, nombre, descripcion)
        VALUES (v_id_rol, p_nombre, p_descripcion);

        FOR v_permiso_name IN SELECT jsonb_array_elements_text(p_permisos)
        LOOP
            SELECT idPermiso INTO v_id_permiso 
            FROM Permiso 
            WHERE nombre = UPPER(v_permiso_name) 
            LIMIT 1;

            IF v_id_permiso IS NOT NULL THEN
                SELECT COALESCE(MAX(idRolPermiso), 0) + 1 INTO v_id_rolpermiso FROM RolPermiso;
                INSERT INTO RolPermiso (idRolPermiso, Rol_idRol, Permisos_idPermiso)
                VALUES (v_id_rolpermiso, v_id_rol, v_id_permiso);
            END IF;
        END LOOP;

        RETURN json_build_object('success', true, 'mensaje', 'Rol maestro creado exitosamente.');
    EXCEPTION WHEN OTHERS THEN
        RETURN json_build_object('success', false, 'mensaje', 'Error en BD: ' || SQLERRM);
    END;
    $$ LANGUAGE plpgsql;

    /* ////////////////////////////////////////////////////////////////////////////////////////////////////////////// */

    -- PARTE DEL DASHBOARD Y MONITOR DE SEGURIDAD EN EL FRONTEND

-- 1. Actualización del Monitor de Seguridad (Nombres Reales)
CREATE OR REPLACE FUNCTION obtener_alertas_seguridad()
RETURNS TABLE (
    id_alerta NUMERIC,
    id_usuario VARCHAR,
    accion_detectada VARCHAR,
    nivel_riesgo VARCHAR,
    tiempo_respuesta VARCHAR
) LANGUAGE plpgsql SECURITY DEFINER AS $$
BEGIN
    RETURN QUERY
    SELECT 
        m.idMonitorActividadSopechosa,
        -- Prioriza el nombre de usuario web, si no existe, concatena el nombre real del cliente
        COALESCE(u.nombreUsuario, c.pNombre || ' ' || c.pApellido)::VARCHAR AS id_usuario,
        'Patrón de Acaparamiento'::VARCHAR AS accion_detectada,
        'Crítico'::VARCHAR AS nivel_riesgo,
        '< 1s'::VARCHAR AS tiempo_respuesta
    FROM MonitorActividadSopechosa m
    JOIN ClienteNatural c ON m.ClienteNatural_idClienteNatural = c.idClienteNatural
    LEFT JOIN Usuario u ON u.ClienteNatural_idClienteNatural = c.idClienteNatural
    ORDER BY m.fechaHora DESC;
END;
$$;

-- 2. Nuevo RPC para Moldes de Rostro Rentables
CREATE PROCEDURE obtener_moldes_rentables()
RETURNS TABLE (
    nombre_molde VARCHAR,
    porcentaje_rentabilidad NUMERIC
) LANGUAGE plpgsql SECURITY DEFINER AS $$
BEGIN
    RETURN QUERY
    -- Lógica base: Contamos cuántos diseños usan el molde y simulamos su % de impacto actual.
    -- (Ver nota al final sobre la fórmula financiera exacta).
    SELECT 
        mr.nombre::VARCHAR AS nombre_molde,
        -- Cálculo simulado basado en el conteo de diseños activos asociados a ese molde.
        -- En un entorno real puro, esto cruzaría con Compra/OrdenCompra para evaluar ganancia neta.
        ROUND((COUNT(d.idDiseño) * 100.0) / (SELECT GREATEST(COUNT(*), 1) FROM Diseño))::NUMERIC AS porcentaje_rentabilidad
    FROM MoldeRostro mr
    JOIN Diseño d ON d.MoldeRostro_idMoldeRostro = mr.idMoldeRostro
    GROUP BY mr.idMoldeRostro, mr.nombre
    ORDER BY porcentaje_rentabilidad DESC
    LIMIT 4;
END;
$$;

CREATE PROCEDURE obtener_distribucion_tipos_cuerpo()
RETURNS TABLE (
    nombre_tipo VARCHAR,
    porcentaje NUMERIC,
    color_hex VARCHAR
) LANGUAGE plpgsql SECURITY DEFINER AS $$
DECLARE
    v_total_productos NUMERIC;
BEGIN
    -- Obtenemos el total de productos en catálogo para calcular la cuota del 100%
    SELECT GREATEST(COUNT(*), 1) INTO v_total_productos FROM Producto;

    RETURN QUERY
    SELECT 
        tc.nombre::VARCHAR AS nombre_tipo,
        -- Calculamos la distribución en base a los Productos creados
        ROUND((COUNT(p.idProducto) * 100.0) / v_total_productos)::NUMERIC AS porcentaje,
        -- Asignamos los colores institucionales
        CASE 
            WHEN tc.nombre ILIKE '%Curvy%' THEN '#8B1D54'::VARCHAR
            WHEN tc.nombre ILIKE '%Original%' THEN '#E0218A'::VARCHAR
            WHEN tc.nombre ILIKE '%Tall%' THEN '#94a3b8'::VARCHAR
            WHEN tc.nombre ILIKE '%Petite%' THEN '#cbd5e1'::VARCHAR
            ELSE '#f1f5f9'::VARCHAR
        END AS color_hex
    FROM TipoCuerpo tc
    -- Camino relacional estricto hacia el Producto
    JOIN RestriccionDiseño rd ON tc.idTipoCuerpo = rd.TipoCuerpo_idTipoCuerpo
    JOIN Diseño d ON rd.Diseño_idDiseño = d.idDiseño
    JOIN Producto p ON d.idDiseño = p.Diseño_idDiseño
    GROUP BY tc.idTipoCuerpo, tc.nombre
    ORDER BY porcentaje DESC;
END;
$$;

/* //////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////// */

/* MODULO DE CREAR DISEÑO */

-- PASO 1: Obtener catálogos de Tipos, Clasificaciones Históricas y Clasificaciones de Exclusividad

CREATE OR REPLACE FUNCTION obtener_catalogos_diseno_paso1()
RETURNS json LANGUAGE plpgsql SECURITY DEFINER AS $$
DECLARE
    v_tipos json;
    v_historicas json;
    v_exclusividad json;
BEGIN
    -- Extraemos los Tipos de Diseño (Ej: Muñeca, Accesorio)
    SELECT COALESCE(json_agg(row_to_json(t)), '[]'::json) INTO v_tipos 
    FROM TipoDiseño t;
    
    -- Extraemos las Clasificaciones Históricas (Ej: Mod Era, Vintage Era)
    SELECT COALESCE(json_agg(row_to_json(ch)), '[]'::json) INTO v_historicas 
    FROM ClasificacionHistorica ch;
    
    -- Extraemos las Clasificaciones de Exclusividad (Ej: Pink Label, Gold Label)
    SELECT COALESCE(json_agg(row_to_json(ce)), '[]'::json) INTO v_exclusividad 
    FROM ClasificacionExclusividad ce;

    -- Devolvemos un payload unificado
    RETURN json_build_object(
        'tipos', v_tipos,
        'historicas', v_historicas,
        'exclusividad', v_exclusividad
    );
END;
$$;

-- PASO 2: Obtener catálogos de Tonos de Piel, Moldes de Rostro y Diseños Base

CREATE OR REPLACE FUNCTION obtener_catalogos_diseno_paso2()
RETURNS json LANGUAGE plpgsql SECURITY DEFINER AS $$
DECLARE
    v_tonos json;
    v_moldes json;
    v_disenos_base json;
BEGIN
    -- Catálogo de Tonos de Piel
    SELECT COALESCE(json_agg(row_to_json(t)), '[]'::json) INTO v_tonos 
    FROM TonoPiel t;
    
    -- Catálogo de Moldes de Rostro
    SELECT COALESCE(json_agg(row_to_json(m)), '[]'::json) INTO v_moldes 
    FROM MoldeRostro m;

    -- Catálogo de Diseños (Para usar como Diseño Padre / Base)
    SELECT COALESCE(json_agg(row_to_json(d)), '[]'::json) INTO v_disenos_base 
    FROM Diseño d;

    -- Retornamos el payload consolidado
    RETURN json_build_object(
        'tonos', v_tonos,
        'moldes', v_moldes,
        'disenos_base', v_disenos_base
    );
END;
$$;

-- PASO 3: Obtener catálogos de Tipos de Cuerpo, Profesiones, Restricciones, Piezas y Materiales

CREATE OR REPLACE FUNCTION obtener_catalogos_diseno_paso3()
RETURNS json LANGUAGE plpgsql SECURITY DEFINER AS $$
DECLARE
    v_cuerpos json;
    v_profesiones json;
    v_restricciones json;
    v_piezas json;
    v_materiales json;
    v_empleados json;
BEGIN
    SELECT COALESCE(json_agg(row_to_json(t)), '[]'::json) INTO v_cuerpos FROM TipoCuerpo t;
    SELECT COALESCE(json_agg(row_to_json(p)), '[]'::json) INTO v_profesiones FROM Profesion p;
    SELECT COALESCE(json_agg(row_to_json(r)), '[]'::json) INTO v_restricciones FROM Restriccion r;
    SELECT COALESCE(json_agg(row_to_json(pz)), '[]'::json) INTO v_piezas FROM Pieza pz;
    SELECT COALESCE(json_agg(row_to_json(m)), '[]'::json) INTO v_materiales FROM Material m;
    
    -- Extraemos empleados con su nombre concatenado
    SELECT COALESCE(json_agg(row_to_json(e)), '[]'::json) INTO v_empleados 
    FROM (
        SELECT idEmpleado, pNombre || ' ' || pApellido AS nombre_completo 
        FROM Empleado
    ) e;

    RETURN json_build_object(
        'cuerpos', v_cuerpos,
        'profesiones', v_profesiones,
        'restricciones', v_restricciones,
        'piezas', v_piezas,
        'materiales', v_materiales,
        'empleados', v_empleados
    );
END;
$$;

-- PASO 4: Registrar el Diseño con todos sus componentes (Diseño, Profesiones, Restricciones, BOM, Fases y Pruebas)

CREATE OR REPLACE FUNCTION registrar_genoma_barbie_maestro(p_payload JSON)
RETURNS JSON LANGUAGE plpgsql SECURITY DEFINER AS $$
DECLARE
    v_id_diseno NUMERIC;
    v_id_fase NUMERIC;
    v_id_prueba NUMERIC;
    v_profesion NUMERIC;
    v_restriccion NUMERIC;
    v_bom JSON;
    v_fase JSON;
    v_prueba JSON;
BEGIN
    SELECT COALESCE(MAX(idDiseño), 0) + 1 INTO v_id_diseno FROM Diseño;

    INSERT INTO Diseño (
        idDiseño, nombre, descripcion, TipoDiseño_idTipoDiseño, ClasificacionHistorica_idClasificacionHistorica,
        ClasificacionExclusividad_idClasificacionExclusividad, TonoPiel_idTonoPiel, MoldeRostro_idMoldeRostro, Diseño_idDiseño
    ) VALUES (
        v_id_diseno, p_payload->>'nombre', p_payload->>'descripcion',
        (p_payload->>'idTipoDiseno')::NUMERIC, (p_payload->>'idClasificacionHistorica')::NUMERIC,
        (p_payload->>'idClasificacionExclusividad')::NUMERIC, (p_payload->>'idTonoPiel')::NUMERIC,
        (p_payload->>'idMoldeRostro')::NUMERIC, NULLIF(p_payload->>'idDisenoBase', '')::NUMERIC
    );

    IF p_payload->'profesiones' IS NOT NULL THEN
        FOR v_profesion IN SELECT value::NUMERIC FROM json_array_elements_text(p_payload->'profesiones') LOOP
            INSERT INTO CurriculumVitae (idCurriculumVitae, añoDeAsignacion, Profesion_idProfesion, Diseño_idDiseño)
            VALUES (COALESCE((SELECT MAX(idCurriculumVitae) FROM CurriculumVitae), 0) + 1, EXTRACT(YEAR FROM CURRENT_DATE), v_profesion, v_id_diseno);
        END LOOP;
    END IF;

    IF p_payload->'restricciones' IS NOT NULL THEN
        FOR v_restriccion IN SELECT value::NUMERIC FROM json_array_elements_text(p_payload->'restricciones') LOOP
            INSERT INTO RestriccionDiseño (idRestriccionDiseño, nombre, descripcion, Diseño_idDiseño, Restriccion_idRestriccion, TipoCuerpo_idTipoCuerpo)
            VALUES (COALESCE((SELECT MAX(idRestriccionDiseño) FROM RestriccionDiseño), 0) + 1, 'Restricción de Fit', 'Automática', v_id_diseno, v_restriccion, (p_payload->>'idTipoCuerpo')::NUMERIC);
        END LOOP;
    END IF;

    IF p_payload->'bom' IS NOT NULL THEN
        FOR v_bom IN SELECT * FROM json_array_elements(p_payload->'bom') LOOP
            INSERT INTO MaterialDiseño (idMaterialDiseño, cantidad, Diseño_idDiseño, Pieza_idPieza, Material_idMaterial)
            VALUES (COALESCE((SELECT MAX(idMaterialDiseño) FROM MaterialDiseño), 0) + 1, (v_bom->>'cantidad')::NUMERIC, v_id_diseno, (v_bom->>'idPieza')::NUMERIC, (v_bom->>'idMaterial')::NUMERIC);
        END LOOP;
    END IF;

    IF p_payload->'fases' IS NOT NULL THEN
        FOR v_fase IN SELECT * FROM json_array_elements(p_payload->'fases') LOOP
            SELECT COALESCE(MAX(idFase), 0) + 1 INTO v_id_fase FROM Fase;
            INSERT INTO Fase (idFase, nombreFase, descripcionFase, Diseño_idDiseño)
            VALUES (v_id_fase, v_fase->>'nombre', v_fase->>'descripcion', v_id_diseno);

            INSERT INTO FaseEmpleado (idFaseEmpleado, fechaInicio, fechaFin, Empleado_idEmpleado, Fase_idFase)
            VALUES (COALESCE((SELECT MAX(idFaseEmpleado) FROM FaseEmpleado), 0) + 1, CURRENT_DATE, NULL, (v_fase->>'idEmpleado')::NUMERIC, v_id_fase);
        END LOOP;
    END IF;

    IF p_payload->'pruebas' IS NOT NULL THEN
        FOR v_prueba IN SELECT * FROM json_array_elements(p_payload->'pruebas') LOOP
            SELECT COALESCE(MAX(idPrueba), 0) + 1 INTO v_id_prueba FROM Prueba;
            INSERT INTO Prueba (idPrueba, nombrePrueba, descripcionPrueba, resultado, tipoPrueba, Diseño_idDiseño)
            VALUES (v_id_prueba, v_prueba->>'nombre', v_prueba->>'descripcion', v_prueba->>'resultado', v_prueba->>'tipo', v_id_diseno);

            INSERT INTO PruebaEmpleado (idPruebaEmpleado, fechaInicio, fechaFin, Prueba_idPrueba, Empleado_idEmpleado)
            VALUES (COALESCE((SELECT MAX(idPruebaEmpleado) FROM PruebaEmpleado), 0) + 1, CURRENT_DATE, NULL, v_id_prueba, (v_prueba->>'idEmpleado')::NUMERIC);
        END LOOP;
    END IF;

    RETURN json_build_object('success', true, 'idGenerado', v_id_diseno);
EXCEPTION WHEN OTHERS THEN
    RETURN json_build_object('success', false, 'mensaje', SQLERRM);
END;
$$;

-- 2. OTORGAR PERMISOS EXPLÍCITOS A LOS ROLES DE LA API
GRANT EXECUTE ON FUNCTION registrar_genoma_barbie_maestro(JSON) TO anon, authenticated, service_role;

-- 3. JUGADA MAESTRA: NOTIFICAR A POSTGREST QUE DEBE RECARGAR EL CACHÉ
NOTIFY pgrst, 'reload schema';

-- /////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////

-- NUEVO RPC PARA OBTENER EL CATÁLOGO DE DISEÑOS CON ESTADÍSTICAS REALES

CREATE OR REPLACE FUNCTION obtener_catalogo_disenos()
RETURNS TABLE (
    sku VARCHAR,
    nombre VARCHAR,
    categoria VARCHAR,
    label_exclusividad VARCHAR,
    molde_rostro VARCHAR,
    stats_totales JSON
) LANGUAGE plpgsql SECURITY DEFINER AS $$
DECLARE
    v_total_disenos INT;
    v_eras_unicas INT;
    v_moldes_unicos INT;
    v_total_restricciones INT;
    v_stats_json JSON;
BEGIN
    -- 1. Calculamos las métricas reales UNA sola vez (Optimización de rendimiento)
    SELECT COUNT(*)::INT INTO v_total_disenos FROM Diseño;
    SELECT COUNT(DISTINCT ClasificacionHistorica_idClasificacionHistorica)::INT INTO v_eras_unicas FROM Diseño;
    SELECT COUNT(DISTINCT MoldeRostro_idMoldeRostro)::INT INTO v_moldes_unicos FROM Diseño;
    SELECT COUNT(*)::INT INTO v_total_restricciones FROM RestriccionDiseño;

    -- 2. Construimos el payload JSON con las variables correctas
    v_stats_json := json_build_object(
        'total_disenos', v_total_disenos,
        'eras_activas', v_eras_unicas,
        'moldes_uso', v_moldes_unicos,
        'restricciones', v_total_restricciones
    );

    -- 3. Retornamos la tabla plana inyectando la variable JSON ya calculada
    RETURN QUERY
    SELECT 
        ('PRD-' || d.idDiseño)::VARCHAR AS sku,
        d.nombre::VARCHAR AS nombre,
        td.nombre::VARCHAR AS categoria,
        ce.nombre::VARCHAR AS label_exclusividad,
        mr.nombre::VARCHAR AS molde_rostro,
        v_stats_json AS stats_totales
    FROM Diseño d
    JOIN TipoDiseño td ON d.TipoDiseño_idTipoDiseño = td.idTipoDiseño
    JOIN ClasificacionExclusividad ce ON d.ClasificacionExclusividad_idClasificacionExclusividad = ce.idClasificacionExclusividad
    JOIN MoldeRostro mr ON d.MoldeRostro_idMoldeRostro = mr.idMoldeRostro
    ORDER BY d.idDiseño DESC;
END;
$$;