
-- Generated by Oracle SQL Developer Data Modeler 24.3.1.351.0831
--   at:        2026-06-15 23:10:57 VET
--   site:      Oracle Database 11g
--   type:      Oracle Database 11g

-- predefined type, no DDL - MDSYS.SDO_GEOMETRY

-- predefined type, no DDL - XMLTYPE

/* CREATE DE LAS TABLAS */

CREATE TABLE Ambiente (
    idAmbiente  NUMERIC(1000)  NOT NULL UNIQUE,
    nombre      VARCHAR(150)  NOT NULL,
    descripcion VARCHAR(600)  NOT NULL,

    CONSTRAINT pk_ambiente_01 PRIMARY KEY (idAmbiente)
);

CREATE TABLE AsignacionMeta (
    idAsignacionMeta              NUMERIC  NOT NULL UNIQUE,
    metaCumplida                  CHAR(1)  NOT NULL ,
    MetaMensual_idMetaMensual     NUMERIC  NOT NULL ,
    Empleado_idEmpleado                 NUMERIC  NOT NULL ,
    ComisionVenta_idComisionVenta NUMERIC  NOT NULL,

    CONSTRAINT pk_asignacion_meta_01 PRIMARY KEY (idAsignacionMeta, MetaMensual_idMetaMensual, Empleado_idEmpleado)
);

CREATE TABLE Asistencia (
     idAsistencia        NUMERIC NOT NULL ,
     fecha               DATE NOT NULL ,
     horaEntrada         TIME NOT NULL ,
     horaSalida          TIME NOT NULL ,
     Empleado_idEmpleado NUMERIC NOT NULL,

     CONSTRAINT pk_asistencia_01 PRIMARY KEY ( idAsistencia )
);

CREATE TABLE AutorDiseño (
     idAutorDiseño                   NUMERIC  NOT NULL UNIQUE,
     Diseño_idDiseño                 NUMERIC  NOT NULL,
     Empleado_id                     NUMERIC  NOT NULL,
     Regalia_idRegalia               NUMERIC  NOT NULL,
     ObjetivoGlobal_idObjetivoGlobal NUMERIC  NOT NULL,

    CONSTRAINT pk_autor_diseño_01 PRIMARY KEY (idAutorDiseño, Diseño_idDiseño, Empleado_id)
);

CREATE TABLE BackOrder(
     idBackOrder           NUMERIC  NOT NULL UNIQUE,
     cantidadPendiente     NUMERIC  NOT NULL,
     precioOriginalPactado NUMERIC  NOT NULL,
     fechaGeneracion       DATE  NOT NULL,
     estatus               NUMERIC NOT NULL,

    CONSTRAINT pk_backorder_01 PRIMARY KEY (idBackOrder)
);

CREATE TABLE ChequeCorporativo (
     idMetodoPago            NUMERIC  NOT NULL UNIQUE,
     numeroCheque        NUMERIC  NOT NULL,
     numeroCuentaEmisora NUMERIC  NOT NULL,
     bancoEmisor         NUMERIC  NOT NULL,

    CONSTRAINT pk_cheque_corporativo_01 PRIMARY KEY (idMetodoPago)
);

CREATE TABLE ClasificacionExclusividad (
     idClasificacionExclusividad NUMERIC  NOT NULL UNIQUE,
     nombre VARCHAR(150)  NOT NULL ,
     descripcion VARCHAR(600)  NOT NULL,

    CONSTRAINT pk_clasificacion_exclusividad_01 PRIMARY KEY (idClasificacionExclusividad)
);

CREATE TABLE ClasificacionHistorica (
     idClasificacionHistorica NUMERIC  NOT NULL ,
     nombre                   VARCHAR(150)  NOT NULL ,
     descripcion              VARCHAR(600)  NOT NULL,

    CONSTRAINT pk_clasificacion_historica_01 PRIMARY KEY (idClasificacionHistorica)
);

CREATE TABLE ClienteJuridico (
     idClienteJuridico NUMERIC  NOT NULL ,
     rif               NUMERIC  NOT NULL ,
     razonSocial       VARCHAR(150)  NOT NULL ,
     nombre            VARCHAR(150)  NOT NULL ,
     direccionJuridica VARCHAR(150)  NOT NULL ,
     limiteCredito     NUMERIC  NOT NULL,
     Lugar_idLugar NUMERIC NOT NULL,

    CONSTRAINT pk_cliente_juridico_01 PRIMARY KEY (idClienteJuridico)
);

CREATE TABLE ClienteNatural (
     idClienteNatural                                      NUMERIC  NOT NULL,
     cedula                                                NUMERIC  NOT NULL,
     pNombre                                               VARCHAR(150)  NOT NULL,
     sNombre                                               VARCHAR(150),
     pApellido                                             VARCHAR(150)  NOT NULL,
     sApellido                                             VARCHAR(150),
     direccion                                             VARCHAR(150)  NOT NULL,
     MonitorActividadSopechosa_idMonitorActividadSopechosa NUMERIC  NOT NULL,
     Lugar_idLugar NUMERIC NOT NULL,

    CONSTRAINT pk_cliente_natural_01 PRIMARY KEY (idClienteNatural)
);

CREATE TABLE Color (
     idColor           NUMERIC  NOT NULL UNIQUE,
     codigoHexadecimal VARCHAR(150)  NOT NULL ,
     nombre            VARCHAR(150)  NOT NULL,

    CONSTRAINT pk_color_01 PRIMARY KEY (idColor)
);

CREATE TABLE ComisionVenta (
     idComisionVenta           NUMERIC  NOT NULL UNIQUE,
     montoComision             NUMERIC  NOT NULL,
     fecha                     DATE  NOT NULL,
     OrdenCompra_idOrdenCompra NUMERIC  NOT NULL,

    CONSTRAINT pk_comision_venta_01 PRIMARY KEY (idComisionVenta)
);

CREATE TABLE Compra (
     idCompra                                NUMERIC  NOT NULL ,
     fechaHora                               DATE  NOT NULL ,
     numeroCompra                            NUMERIC  NOT NULL ,
     totalPagar                              NUMERIC  NOT NULL ,
     subTotal                                NUMERIC  NOT NULL ,
     ClienteNatural_idClienteNatural         NUMERIC  NOT NULL ,
     TipoUbicacionStock_idTipoUbicacionStock NUMERIC  NOT NULL,

    CONSTRAINT pk_compra_01 PRIMARY KEY (idCompra)
);

CREATE TABLE CompraDescuento (
     idCompraDescuento     NUMERIC  NOT NULL ,
     monto NUMERIC NOT NULL,
     Compra_idCompra       NUMERIC  NOT NULL ,
     Descuento_idDescuento NUMERIC  NOT NULL,

    CONSTRAINT pk_compra_descuento_01 PRIMARY KEY (idCompraDescuento, Compra_idCompra, Descuento_idDescuento)
);

CREATE TABLE Conciliacion (
    idConciliacion            NUMERIC NOT NULL,
    montoAplicado             NUMERIC NOT NULL,
    fechaAplicacion           DATE NOT NULL,
    OrdenCompra_idOrdenCompra NUMERIC NOT NULL,
    PagoJuridico_idPago       NUMERIC NOT NULL,

    CONSTRAINT pk_conciliacion_01 PRIMARY KEY (idConciliacion, OrdenCompra_idOrdenCompra, PagoJuridico_idPago)
);

CREATE TABLE CondicionFisica (
     idCondicionFisica NUMERIC  NOT NULL ,
     nombre            VARCHAR(150)  NOT NULL ,
     descripcion       VARCHAR(600)  NOT NULL,

    CONSTRAINT pk_condicion_fisica_01 PRIMARY KEY (idCondicionFisica)
);

CREATE TABLE Courier (
     idCourier NUMERIC  NOT NULL ,
     nombre    VARCHAR(150)  NOT NULL,

    CONSTRAINT pk_courier_01 PRIMARY KEY (idCourier)
);

CREATE TABLE CriptoActivo (
     idMetodoPago  NUMERIC  NOT NULL UNIQUE,
     hashTransaccion VARCHAR(200)  NOT NULL ,
     redBlockchain   VARCHAR(200)  NOT NULL ,
     billeteraOrigen VARCHAR(200)  NOT NULL,

    CONSTRAINT pk_cripto_activo_01 PRIMARY KEY (idMetodoPago)
);

CREATE TABLE CurriculumVitae (
    idCurriculumVitae     NUMERIC  NOT NULL UNIQUE,
    añoDeAsignacion       NUMERIC  NOT NULL ,
    Profesion_idProfesion NUMERIC  NOT NULL ,
    Diseño_idDiseño       NUMERIC  NOT NULL,

    CONSTRAINT pk_curriculum_vitae_01 PRIMARY KEY (idCurriculumVitae, Profesion_idProfesion, Diseño_idDiseño)
);

CREATE TABLE Departamento (
     idDepartamento NUMERIC  NOT NULL ,
     nombre         VARCHAR(150)  NOT NULL ,
     direccion      VARCHAR(150)  NOT NULL,

    CONSTRAINT pk_departamento_01 PRIMARY KEY (idDepartamento)
);

CREATE TABLE Descuento (
     idDescuento       NUMERIC  NOT NULL ,
     nombre            VARCHAR(150)  NOT NULL ,
     descripcion       VARCHAR(600)  NOT NULL ,
     porcentaje        NUMERIC  NOT NULL ,

    CONSTRAINT pk_descuento_01 PRIMARY KEY (idDescuento)
);

CREATE TABLE DespachoNatural (
    idDespachoNatural NUMERIC  NOT NULL ,
    numeroTracking    NUMERIC  NOT NULL ,
    alto              NUMERIC  NOT NULL ,
    ancho             NUMERIC  NOT NULL ,
    largo             NUMERIC  NOT NULL ,
    costoEnvio        NUMERIC  NOT NULL ,
    Compra_idCompra   NUMERIC  NOT NULL ,
    Courier_idCourier NUMERIC  NOT NULL,

    CONSTRAINT pk_despacho_natural_01 PRIMARY KEY (idDespachoNatural)
);

CREATE TABLE DetalleCompraJuridico (
     idDetalleCompraJuridico     NUMERIC  NOT NULL,
     precioUnitario              NUMERIC  NOT NULL,
     cantidad                    NUMERIC  NOT NULL,
     estado                      VARCHAR(150)  NOT NULL,
     Departamento_idDepartamento NUMERIC  NOT NULL,
     OrdenCompra_idOrdenCompra   NUMERIC  NOT NULL,
     Caja_idCaja                 NUMERIC  NOT NULL,
     BackOrder_idBackOrder       NUMERIC  NOT NULL,

    CONSTRAINT pk_detalle_compra_juridico_01 PRIMARY KEY (idDetalleCompraJuridico, OrdenCompra_idOrdenCompra)
);

CREATE UNIQUE INDEX DetalleCompraJuridico__IDX ON DetalleCompraJuridico ( BackOrder_idBackOrder ASC );

CREATE TABLE DetalleCompraNatural (
     idDetalleCompraNatural             NUMERIC  NOT NULL UNIQUE ,
     precioUnitario                     NUMERIC  NOT NULL,
     UnidadProducida_idUnidadProducidad NUMERIC  NOT NULL,
     Compra_idCompra                    NUMERIC  NOT NULL,

    CONSTRAINT pk_detalle_compra_natural_01 PRIMARY KEY (idDetalleCompraNatural, UnidadProducida_idUnidadProducidad, Compra_idCompra)
);

CREATE TABLE DevolucionJuridica (
    idDevolucionJuridica      NUMERIC  NOT NULL UNIQUE,
    fechaDevolucion           DATE  NOT NULL ,
    motivo                    VARCHAR(600)  NOT NULL ,
    OrdenCompra_idOrdenCompra NUMERIC  NOT NULL,

    CONSTRAINT pk_devolucion_juridica_01 PRIMARY KEY (idDevolucionJuridica)
);

CREATE TABLE DevolucionNatural (
     idDevolucionNatural NUMERIC  NOT NULL ,
     fechaDevolucion     DATE  NOT NULL ,
     motivo              VARCHAR(600)  NOT NULL ,
     Compra_idCompra     NUMERIC  NOT NULL,

    CONSTRAINT pk_devolucion_natural_01 PRIMARY KEY (idDevolucionNatural)
);

CREATE TABLE Diseño (
    idDiseño                                              NUMERIC  NOT NULL ,
    nombre                                                VARCHAR(150)  NOT NULL ,
    descripcion                                           VARCHAR(600)  NOT NULL ,
    ClasificacionHistorica_idClasificacionHistorica       NUMERIC  NOT NULL,
    ClasificacionExclusividad_idClasificacionExclusividad NUMERIC  NOT NULL,
    TonoPiel_idTonoPiel                                   NUMERIC  NOT NULL,
    MoldeRostro_idMoldeRostro                             NUMERIC  NOT NULL,
    Diseño_idDiseño                                       NUMERIC,
    TipoDiseño_idTipoDiseño                               NUMERIC  NOT NULL,

    CONSTRAINT pk_diseño_01 PRIMARY KEY (idDiseño)
);

CREATE TABLE DiseñoAmbiente (
     idDiseñoAmbiente    NUMERIC  NOT NULL UNIQUE,
     interactivo         CHAR(1),
     Diseño_idDiseño     NUMERIC  NOT NULL,
     Ambiente_idAmbiente NUMERIC  NOT NULL,

    CONSTRAINT pk_diseño_ambiente_01 PRIMARY KEY (idDiseñoAmbiente, Diseño_idDiseño, Ambiente_idAmbiente)
);

CREATE TABLE Efectivo (
    idMetodoPago                 NUMERIC  NOT NULL UNIQUE,
    numeroSerie                VARCHAR(200)  NOT NULL,
    letraNumeroReservaFederal1 VARCHAR(200)  NOT NULL,

    CONSTRAINT pk_efectivo_01 PRIMARY KEY (idMetodoPago)
);

CREATE TABLE Empleado (
     idEmpleado              NUMERIC  NOT NULL UNIQUE ,
     cedula          NUMERIC  NOT NULL ,
     pNombre         VARCHAR(150)  NOT NULL ,
     sNombre         VARCHAR(150) ,
     pApellido       VARCHAR(150)  NOT NULL ,
     sApellido       VARCHAR(150) ,
     fechaNacimiento DATE  NOT NULL ,
     direccion       VARCHAR(200)  NOT NULL ,
     Lugar_idLugar   NUMERIC  NOT NULL,

    CONSTRAINT pk_empleado_01 PRIMARY KEY (idEmpleado)
);

CREATE TABLE EstadoOrden (
     idEstadoOrden NUMERIC  NOT NULL UNIQUE,
     nombre        VARCHAR(150)  NOT NULL ,
     descripcion   VARCHAR(600)  NOT NULL,

    CONSTRAINT pk_estado_orden_01 PRIMARY KEY (idEstadoOrden)
);

CREATE TABLE Estatus (
     idEstatus   NUMERIC NOT NULL ,
     nombre      VARCHAR(150) NOT NULL ,
     tipoEstatus VARCHAR(150) NOT NULL,
     CONSTRAINT pk_estatus_01 PRIMARY KEY ( idEstatus )
);

CREATE TABLE Fase (
     idFase          NUMERIC NOT NULL ,
     nombreFase      VARCHAR(150) NOT NULL ,
     descripcionFase VARCHAR(600) ,
     Diseño_idDiseño NUMERIC NOT NULL,

    CONSTRAINT pk_fase_01 PRIMARY KEY ( idFase )
);

CREATE TABLE FaseEmpleado (
     idFaseEmpleado      NUMERIC NOT NULL ,
     fechaInicio         DATE NOT NULL ,
     fechaFin            DATE ,
     Empleado_idEmpleado NUMERIC NOT NULL ,
     Fase_idFase         NUMERIC NOT NULL,

    CONSTRAINT pk_fase_empleado_01 PRIMARY KEY (idFaseEmpleado, Empleado_idEmpleado, Fase_idFase)
);

CREATE TABLE HistoricoEmpleado (
     idHistoricoEmpleado                     NUMERIC  NOT NULL UNIQUE,
     fechaInicio                             DATE  NOT NULL ,
     fechaFin                                DATE,
     salarioBase                             NUMERIC  NOT NULL ,
     Empleado_idEmpleado                             NUMERIC  NOT NULL ,
     Departamento_idDepartamento             NUMERIC  NOT NULL ,
     PuestoTrabajo_id                        NUMERIC  NOT NULL ,
     TipoUbicacionStock_idTipoUbicacionStock NUMERIC  NOT NULL,

    CONSTRAINT pk_historico_empleado_01 PRIMARY KEY (idHistoricoEmpleado, Empleado_idEmpleado, Departamento_idDepartamento)
);

CREATE TABLE HistoricoEstado (
    idHistoricoEstado         NUMERIC  NOT NULL,
    fechaHora                 TIMESTAMP  NOT NULL,
    OrdenCompra_idOrdenCompra NUMERIC,          -- Permite NULL (CHECK exige que una de las dos sea NULL)
    EstadoOrden_idEstadoOrden NUMERIC  NOT NULL,
    Compra_idCompra           NUMERIC,          -- Permite NULL (CHECK exige que una de las dos sea NULL)

    CONSTRAINT arc_historico_estado_01 CHECK ( ( (OrdenCompra_idOrdenCompra IS NOT NULL) AND (Compra_idCompra IS NULL) ) OR ( (Compra_idCompra IS NOT NULL) AND (OrdenCompra_idOrdenCompra IS NULL) ) ),
    CONSTRAINT pk_historico_estado_01 PRIMARY KEY (idHistoricoEstado, EstadoOrden_idEstadoOrden)
);

CREATE TABLE HistoricoEstatus (
     idHistoricoEstatus      NUMERIC NOT NULL ,
     fechaHoraInicio         DATE NOT NULL ,
     Estatus_idEstatus       NUMERIC NOT NULL ,
     fechaHoraFin            DATE ,
     Subasta_idSubasta       NUMERIC ,
     Puja_idPuja             NUMERIC ,
     Puja_idClienteNatural   NUMERIC ,
     Puja_idSubasta          NUMERIC ,
     OrdenVenta_idOrdenVenta NUMERIC ,
     Compra_idCompra         NUMERIC,

    CONSTRAINT arc_historico_estatus_01 CHECK ( (  (Compra_idCompra IS NOT NULL) AND
         (Puja_idPuja IS NULL)  AND
         (Puja_idClienteNatural IS NULL)  AND
         (Puja_idSubasta IS NULL)  AND
         (Subasta_idSubasta IS NULL)  AND
         (OrdenVenta_idOrdenVenta IS NULL) ) OR
         ( (Puja_idPuja IS NOT NULL) AND
         (Puja_idClienteNatural IS NOT NULL) AND
         (Puja_idSubasta IS NOT NULL) AND
         (Compra_idCompra IS NULL)  AND
         (Subasta_idSubasta IS NULL)  AND
         (OrdenVenta_idOrdenVenta IS NULL) ) OR
         ( (Subasta_idSubasta IS NOT NULL) AND
         (Compra_idCompra IS NULL)  AND
         (Puja_idPuja IS NULL)  AND
         (Puja_idClienteNatural IS NULL)  AND
         (Puja_idSubasta IS NULL)  AND
         (OrdenVenta_idOrdenVenta IS NULL) ) OR
         ( (OrdenVenta_idOrdenVenta IS NOT NULL) AND
         (Compra_idCompra IS NULL)  AND
         (Puja_idPuja IS NULL)  AND
         (Puja_idClienteNatural IS NULL)  AND
         (Puja_idSubasta IS NULL)  AND
         (Subasta_idSubasta IS NULL) ) ),

    CONSTRAINT pk_historico_estatus_01 PRIMARY KEY ( idHistoricoEstatus, Estatus_idEstatus )
);

CREATE TABLE Horario (
    idHorario  NUMERIC  NOT NULL UNIQUE,
    dia        VARCHAR(150) NOT NULL,
    horaInicio TIME  NOT NULL,
    horaFin    TIME  NOT NULL,

    CONSTRAINT pk_horario_01 PRIMARY KEY (idHorario)
);

CREATE TABLE InsumoProduccion (
    idInsumoProduccion                  NUMERIC  NOT NULL UNIQUE,
    cantidad                            NUMERIC  NOT NULL,
    LoteMateriaPrima_idLoteMateriaPrima NUMERIC  NOT NULL,
    LoteProduccion_idLote               NUMERIC  NOT NULL,

    CONSTRAINT pk_insumo_produccion_01 PRIMARY KEY (idInsumoProduccion, LoteMateriaPrima_idLoteMateriaPrima, LoteProduccion_idLote)
);

CREATE TABLE ListaPrecioMayorista (
    idListaPrecioMayorista             NUMERIC  NOT NULL,
    precioUnitario                     NUMERIC  NOT NULL,
    fecha                              DATE  NOT NULL,
    ClienteJuridico_idClienteJuridico  NUMERIC  NOT NULL,
    UnidadProducida_idUnidadProducidad NUMERIC  NOT NULL,

    CONSTRAINT pk_lista_precio_mayorista_01 PRIMARY KEY (idListaPrecioMayorista, ClienteJuridico_idClienteJuridico, UnidadProducida_idUnidadProducidad)
);

CREATE TABLE LoteMateriaPrima (
     idLoteMateriaPrima  NUMERIC  NOT NULL UNIQUE,
     costoAdquisicion    NUMERIC  NOT NULL,
     nombre              VARCHAR(150)  NOT NULL,
     descripcion         VARCHAR(600)  NOT NULL,
     Material_idMaterial NUMERIC  NOT NULL,

    CONSTRAINT pk_lote_materia_prima_01 PRIMARY KEY (idLoteMateriaPrima)
);

CREATE TABLE LoteProduccion (
    idLote      NUMERIC  NOT NULL,
    fechaInicio DATE  NOT NULL,
    fechaFin    DATE  NOT NULL,

    CONSTRAINT pk_lote_produccion_01 PRIMARY KEY (idLote)
);

CREATE TABLE Lugar (
     idLugar       NUMERIC  NOT NULL UNIQUE,
     nombre        VARCHAR(150)  NOT NULL,
     tipo          VARCHAR(150)  NOT NULL,
     codigoPostal  NUMERIC  NOT NULL,
     Lugar_idLugar NUMERIC,

    CONSTRAINT pk_lugar_01 PRIMARY KEY (idLugar)
);

CREATE TABLE ManifiestoCarga (
     idManifiestoCarga         NUMERIC  NOT NULL UNIQUE,
     cantidadPaletas           NUMERIC  NOT NULL,
     cantidadCajasMaster       NUMERIC  NOT NULL,
     OrdenCompra_idOrdenCompra NUMERIC  NOT NULL,
     Transporte_idTransporte   NUMERIC  NOT NULL,

    CONSTRAINT pk_manifiesto_carga_01 PRIMARY KEY (idManifiestoCarga)
);

CREATE TABLE Material (
     idMaterial  NUMERIC  NOT NULL UNIQUE,
     nombre      VARCHAR(150)  NOT NULL,
     descripcion VARCHAR(600)  NOT NULL,

    CONSTRAINT pk_material_01 PRIMARY KEY (idMaterial)
);

CREATE TABLE MaterialDiseño (
    idMaterialDiseño    NUMERIC  NOT NULL UNIQUE,
    cantidad            NUMERIC  NOT NULL,
    Diseño_idDiseño     NUMERIC  NOT NULL,
    Pieza_idPieza       NUMERIC  NOT NULL,
    Material_idMaterial NUMERIC  NOT NULL,

    CONSTRAINT pk_material_diseño_01 PRIMARY KEY (idMaterialDiseño, Diseño_idDiseño)
);

CREATE TABLE Membresia (
    idMembresia                     NUMERIC  NOT NULL UNIQUE,
    nombre                          VARCHAR(150)  NOT NULL,
    descripcion                     VARCHAR(600)  NOT NULL,
    ClienteNatural_idClienteNatural NUMERIC  NOT NULL,

    CONSTRAINT pk_membresia_01 PRIMARY KEY (idMembresia)
);

CREATE TABLE MetaMensual (
     idMetaMensual      NUMERIC  NOT NULL UNIQUE,
     fechaInicio        DATE  NOT NULL,
     fechaFin           DATE  NOT NULL,
     porcentajeComision NUMERIC  NOT NULL,

    CONSTRAINT pk_meta_mensual_01 PRIMARY KEY (idMetaMensual)
);

CREATE TABLE MoldeRostro (
     idMoldeRostro NUMERIC  NOT NULL UNIQUE,
     nombre        VARCHAR(150)  NOT NULL,
     descripcion   VARCHAR(600)  NOT NULL,
     añoPatente    DATE  NOT NULL,

    CONSTRAINT pk_molde_rostro_01 PRIMARY KEY (idMoldeRostro)
);

CREATE TABLE MonitorActividadSopechosa (
     idMonitorActividadSopechosa NUMERIC  NOT NULL UNIQUE,
     fechaHora                   DATE  NOT NULL,
     ClienteNatural_idClienteNatural NUMERIC NOT NULL,

    CONSTRAINT pk_monitor_actividad_sospechosa_01 PRIMARY KEY (idMonitorActividadSopechosa)
);

CREATE TABLE ObjetivoGlobal (
     idObjetivoGlobal  NUMERIC  NOT NULL UNIQUE,
     volumenVentas     NUMERIC  NOT NULL,
     porcentajeRegalia NUMERIC  NOT NULL,

    CONSTRAINT pk_objetivo_global_01 PRIMARY KEY (idObjetivoGlobal)
);

CREATE TABLE ObjetivoGlobalProducto (
     idObjetivoGlobalProducto        NUMERIC  NOT NULL UNIQUE,
     objetivoSuperado                CHAR(1)  NOT NULL ,
     Producto_idProducto             NUMERIC  NOT NULL ,
     ObjetivoGlobal_idObjetivoGlobal NUMERIC  NOT NULL,

    CONSTRAINT pk_objetivo_global_producto_01 PRIMARY KEY (idObjetivoGlobalProducto, Producto_idProducto, ObjetivoGlobal_idObjetivoGlobal)
);

CREATE TABLE OrdenCompra (
     idOrdenCompra                     NUMERIC  NOT NULL UNIQUE,
     fechaEmision                      DATE  NOT NULL ,
     fechaVencimiento                  DATE  NOT NULL ,
     especificacionesTecnicas          VARCHAR(600)  NOT NULL ,
     precioUnitario                    NUMERIC  NOT NULL ,
     subTotal                          NUMERIC  NOT NULL ,
     impuestos                         NUMERIC  NOT NULL ,
     ClienteJuridico_idClienteJuridico NUMERIC  NOT NULL ,
     BackOrder_idBackOrder             NUMERIC  NOT NULL,

    CONSTRAINT pk_orden_compra_01 PRIMARY KEY (idOrdenCompra)
);
CREATE UNIQUE INDEX OrdenCompra__IDX ON OrdenCompra (
     BackOrder_idBackOrder ASC
);

CREATE TABLE OrdenCompraDescuento (
     idOrdenCompraDescuento    NUMERIC  NOT NULL UNIQUE,
     monto                     NUMERIC NOT NULL,
     OrdenCompra_idOrdenCompra NUMERIC  NOT NULL ,
     Descuento_idDescuento     NUMERIC  NOT NULL,

    CONSTRAINT pk_orden_compra_descuento_01 PRIMARY KEY (idOrdenCompraDescuento, OrdenCompra_idOrdenCompra, Descuento_idDescuento)
);

CREATE TABLE OrdenVenta (
     idOrdenVenta         NUMERIC  NOT NULL UNIQUE,
     fechaHoraEmision     DATE  NOT NULL ,
     fechaHoraVencimiento DATE  NOT NULL ,
     estatusPendientePago CHAR (1)  NOT NULL,

    CONSTRAINT pk_orden_venta_01 PRIMARY KEY (idOrdenVenta)
);

CREATE TABLE Pack (
     idPack               NUMERIC  NOT NULL UNIQUE,
     Producto_idProducto  NUMERIC  NOT NULL ,
     Producto_idProducto2 NUMERIC  NOT NULL,

    CONSTRAINT pk_pack_01 PRIMARY KEY (idPack, Producto_idProducto, Producto_idProducto2)
);

CREATE TABLE PagoJuridico (
    idPago      NUMERIC NOT NULL UNIQUE,
    monto       NUMERIC NOT NULL,
    fechaHora   DATE NOT NULL,

    Cheque_id   NUMERIC,
    Cripto_id   NUMERIC,
    Efectivo_id NUMERIC,
    PayPal_id   NUMERIC,
    Swift_id    NUMERIC,
    TarjCred_id NUMERIC,
    TarjDeb_id  NUMERIC,

    CONSTRAINT pk_pago_juridico_01 PRIMARY KEY (idPago),

    CONSTRAINT arc_pago_juridico_metodo CHECK (
      (Cheque_id IS NOT NULL AND Cripto_id IS NULL AND Efectivo_id IS NULL AND PayPal_id IS NULL AND Swift_id IS NULL AND TarjCred_id IS NULL AND TarjDeb_id IS NULL) OR
      (Cripto_id IS NOT NULL AND Cheque_id IS NULL AND Efectivo_id IS NULL AND PayPal_id IS NULL AND Swift_id IS NULL AND TarjCred_id IS NULL AND TarjDeb_id IS NULL) OR
      (Efectivo_id IS NOT NULL AND Cheque_id IS NULL AND Cripto_id IS NULL AND PayPal_id IS NULL AND Swift_id IS NULL AND TarjCred_id IS NULL AND TarjDeb_id IS NULL) OR
      (PayPal_id IS NOT NULL AND Cheque_id IS NULL AND Cripto_id IS NULL AND Efectivo_id IS NULL AND Swift_id IS NULL AND TarjCred_id IS NULL AND TarjDeb_id IS NULL) OR
      (Swift_id IS NOT NULL AND Cheque_id IS NULL AND Cripto_id IS NULL AND Efectivo_id IS NULL AND PayPal_id IS NULL AND TarjCred_id IS NULL AND TarjDeb_id IS NULL) OR
      (TarjCred_id IS NOT NULL AND Cheque_id IS NULL AND Cripto_id IS NULL AND Efectivo_id IS NULL AND PayPal_id IS NULL AND Swift_id IS NULL AND TarjDeb_id IS NULL) OR
      (TarjDeb_id IS NOT NULL AND Cheque_id IS NULL AND Cripto_id IS NULL AND Efectivo_id IS NULL AND PayPal_id IS NULL AND Swift_id IS NULL AND TarjCred_id IS NULL)
      )
);

CREATE TABLE PagoNatural (
    idPagoNatural   NUMERIC NOT NULL UNIQUE,
    Compra_idCompra NUMERIC NOT NULL,

    Cheque_id       NUMERIC,
    Cripto_id       NUMERIC,
    Efectivo_id     NUMERIC,
    PayPal_id       NUMERIC,
    Swift_id        NUMERIC,
    TarjCred_id     NUMERIC,
    TarjDeb_id      NUMERIC,

    CONSTRAINT pk_pago_natural_01 PRIMARY KEY (idPagoNatural, Compra_idCompra),

    CONSTRAINT arc_pago_natural_metodo CHECK (
     (Cheque_id IS NOT NULL AND Cripto_id IS NULL AND Efectivo_id IS NULL AND PayPal_id IS NULL AND Swift_id IS NULL AND TarjCred_id IS NULL AND TarjDeb_id IS NULL) OR
     (Cripto_id IS NOT NULL AND Cheque_id IS NULL AND Efectivo_id IS NULL AND PayPal_id IS NULL AND Swift_id IS NULL AND TarjCred_id IS NULL AND TarjDeb_id IS NULL) OR
     (Efectivo_id IS NOT NULL AND Cheque_id IS NULL AND Cripto_id IS NULL AND PayPal_id IS NULL AND Swift_id IS NULL AND TarjCred_id IS NULL AND TarjDeb_id IS NULL) OR
     (PayPal_id IS NOT NULL AND Cheque_id IS NULL AND Cripto_id IS NULL AND Efectivo_id IS NULL AND Swift_id IS NULL AND TarjCred_id IS NULL AND TarjDeb_id IS NULL) OR
     (Swift_id IS NOT NULL AND Cheque_id IS NULL AND Cripto_id IS NULL AND Efectivo_id IS NULL AND PayPal_id IS NULL AND TarjCred_id IS NULL AND TarjDeb_id IS NULL) OR
     (TarjCred_id IS NOT NULL AND Cheque_id IS NULL AND Cripto_id IS NULL AND Efectivo_id IS NULL AND PayPal_id IS NULL AND Swift_id IS NULL AND TarjDeb_id IS NULL) OR
     (TarjDeb_id IS NOT NULL AND Cheque_id IS NULL AND Cripto_id IS NULL AND Efectivo_id IS NULL AND PayPal_id IS NULL AND Swift_id IS NULL AND TarjCred_id IS NULL)
     )
);

CREATE TABLE PayPal (
     idMetodoPago        NUMERIC  NOT NULL UNIQUE,
     comisionRetenida  NUMERIC  NOT NULL ,
     codigoTransaccion VARCHAR(200)  NOT NULL ,
     correoAsociado    VARCHAR(200)  NOT NULL,

    CONSTRAINT pk_paypal_01 PRIMARY KEY (idMetodoPago)
);

CREATE TABLE Permiso (
     idPermiso NUMERIC  NOT NULL UNIQUE,
     nombre    VARCHAR(150)  NOT NULL,
    CONSTRAINT pk_permiso_01 PRIMARY KEY (idPermiso)
);

CREATE TABLE Pieza (
     idPieza               NUMERIC  NOT NULL UNIQUE,
     nombre                VARCHAR(150)  NOT NULL ,
     descripcion           VARCHAR(600)  NOT NULL ,
     Color_idColor         NUMERIC  NOT NULL ,
     TipoPieza_idTipoPieza NUMERIC  NOT NULL,

    CONSTRAINT pk_pieza_01 PRIMARY KEY (idPieza)
);

CREATE TABLE PiezaProducto (
     idPiezaProducto     NUMERIC  NOT NULL UNIQUE,
     Pieza_idPieza       NUMERIC  NOT NULL ,
     Producto_idProducto NUMERIC  NOT NULL,

    CONSTRAINT pk_pieza_producto_01 PRIMARY KEY (idPiezaProducto, Pieza_idPieza, Producto_idProducto)
);

CREATE TABLE Producto (
     idProducto                      NUMERIC  NOT NULL UNIQUE,
     nombre                          VARCHAR(150)  NOT NULL ,
     descripcion                     VARCHAR(600)  NOT NULL ,
     fechaSalida                     DATE  NOT NULL ,
     Diseño_idDiseño                 NUMERIC  NOT NULL ,
     LoteProduccion_idLote           NUMERIC  NOT NULL ,
     precioLanzamiento               NUMERIC  NOT NULL ,
     limiteCompraPorUsuario          NUMERIC  NOT NULL ,
     BackOrder_idBackOrder           NUMERIC,

    CONSTRAINT pk_producto_01 PRIMARY KEY (idProducto)
);

CREATE TABLE Profesion (
     idProfesion NUMERIC  NOT NULL UNIQUE,
     nombre      VARCHAR(150)  NOT NULL ,
     descripcion VARCHAR(600)  NOT NULL,

    CONSTRAINT pk_profesion_01 PRIMARY KEY (idProfesion)
);

CREATE TABLE Prueba (
     idPrueba          NUMERIC NOT NULL ,
     nombrePrueba      VARCHAR(150) NOT NULL ,
     descripcionPrueba VARCHAR(600) NOT NULL ,
     resultado         VARCHAR(150) ,
     tipoPrueba        VARCHAR(150) NOT NULL ,
     Diseño_idDiseño   NUMERIC NOT NULL,

    CONSTRAINT pk_prueba_01 PRIMARY KEY (idPrueba)
) ;

CREATE TABLE PruebaEmpleado (
     idPruebaEmpleado    NUMERIC NOT NULL ,
     fechaInicio         DATE NOT NULL ,
     fechaFin            DATE ,
     Prueba_idPrueba     NUMERIC NOT NULL ,
     Empleado_idEmpleado NUMERIC NOT NULL,

    CONSTRAINT pk_prueba_empleado_01 PRIMARY KEY (idPruebaEmpleado, Prueba_idPrueba, Empleado_idEmpleado)
);

CREATE TABLE PuestoTrabajo (
     id          NUMERIC  NOT NULL UNIQUE,
     nombre      VARCHAR(150)  NOT NULL ,
     descripcion VARCHAR(600)  NOT NULL,

    CONSTRAINT pk_puesto_trabajo_01 PRIMARY KEY (id)
);

CREATE TABLE Puja (
     idPuja                          NUMERIC  NOT NULL UNIQUE,
     fechaHora                       DATE  NOT NULL ,
     monto                           NUMERIC  NOT NULL ,
     ClienteNatural_idClienteNatural NUMERIC  NOT NULL ,
     Subasta_idSubasta               NUMERIC  NOT NULL ,

    CONSTRAINT pk_puja_01 PRIMARY KEY (idPuja, ClienteNatural_idClienteNatural, Subasta_idSubasta)
);

CREATE TABLE Regalia (
     idRegalia NUMERIC  NOT NULL UNIQUE,
     monto     NUMERIC  NOT NULL ,
     fechaHora DATE  NOT NULL,

    CONSTRAINT pk_regalia_01 PRIMARY KEY (idRegalia)
);

CREATE TABLE Restriccion (
     idRestriccion NUMERIC  NOT NULL UNIQUE,
     nombre        VARCHAR(150)  NOT NULL ,
     descripcion   VARCHAR(600)  NOT NULL,

    CONSTRAINT pk_restriccion_01 PRIMARY KEY (idRestriccion)
);

CREATE TABLE RestriccionDiseño (
     idRestriccionDiseño       NUMERIC  NOT NULL UNIQUE,
     nombre                    VARCHAR(150)  NOT NULL ,
     descripcion               VARCHAR(600)  NOT NULL ,
     Diseño_idDiseño           NUMERIC  NOT NULL ,
     Restriccion_idRestriccion NUMERIC  NOT NULL ,
     TipoCuerpo_idTipoCuerpo   NUMERIC  NOT NULL,

    CONSTRAINT pk_restriccion_diseño_01 PRIMARY KEY (idRestriccionDiseño, Diseño_idDiseño)
);

CREATE TABLE Rol (
     idRol       NUMERIC  NOT NULL UNIQUE,
     nombre      VARCHAR(150)  NOT NULL ,
     descripcion VARCHAR(150)  NOT NULL ,

    CONSTRAINT pk_rol_01 PRIMARY KEY (idRol)
);

CREATE TABLE RolPermiso (
     idRolPermiso       NUMERIC  NOT NULL UNIQUE,
     Rol_idRol          NUMERIC  NOT NULL ,
     Permisos_idPermiso NUMERIC  NOT NULL,

    CONSTRAINT pk_rol_permiso_01 PRIMARY KEY (idRolPermiso, Rol_idRol, Permisos_idPermiso)
);

CREATE TABLE Sancion (
     idSancion                       NUMERIC  NOT NULL UNIQUE,
     fechaHoraInicio                 DATE  NOT NULL ,
     fechaHoraDin                    DATE  NOT NULL ,
     nombre                          VARCHAR(150)  NOT NULL ,
     descripcion                     VARCHAR(600)  NOT NULL ,
     ClienteNatural_idClienteNatural NUMERIC  NOT NULL,

    CONSTRAINT pk_sancion_01 PRIMARY KEY (idSancion)
);

CREATE TABLE StockClienteNatural (
     idStockClienteNatural              NUMERIC  NOT NULL UNIQUE,
     UnidadProducida_idUnidadProducidad NUMERIC  NOT NULL ,
     ClienteNatural_idClienteNatural    NUMERIC  NOT NULL ,
     condicionFisica_idCondicionFisica  NUMERIC  NOT NULL ,
     Subasta_idSubasta                  NUMERIC  NOT NULL ,

    CONSTRAINT pk_stock_cliente_natural_01 PRIMARY KEY (idStockClienteNatural, UnidadProducida_idUnidadProducidad, ClienteNatural_idClienteNatural)
);

CREATE TABLE Subasta (
     idSubasta               NUMERIC  NOT NULL UNIQUE,
     fechaHoraInicio         DATE  NOT NULL ,
     fechaHoraFin            DATE  NOT NULL ,
     precioBase              NUMERIC  NOT NULL ,
     incrementoMinimo        NUMERIC  NOT NULL ,
     OrdenVenta_idOrdenVenta NUMERIC  NOT NULL ,

    CONSTRAINT pk_subasta_01 PRIMARY KEY (idSubasta)
);

CREATE TABLE SubEnsamblaje (
     idSubEnsamblaje NUMERIC  NOT NULL UNIQUE,
     cantidad        NUMERIC  NOT NULL ,
     Pieza_idPieza   NUMERIC  NOT NULL ,
     Pieza_idPieza2  NUMERIC  NOT NULL,

    CONSTRAINT pk_sub_ensamblaje_01 PRIMARY KEY (idSubEnsamblaje, Pieza_idPieza, Pieza_idPieza2)
);

CREATE TABLE Swift (
     idMetodoPago           NUMERIC  NOT NULL UNIQUE,
     codigoReferencia  VARCHAR(200)  NOT NULL ,
     codigoSwiftOrigen VARCHAR(200)  NOT NULL,

    CONSTRAINT pk_swift_01 PRIMARY KEY (idMetodoPago)
);

CREATE TABLE TarjetaCredito (
     idMetodoPago     NUMERIC  NOT NULL UNIQUE,
     numeroTarjeta        NUMERIC  NOT NULL ,
     hashTarjeta          VARCHAR(200)  NOT NULL ,
     ultimosCuatroDigitos NUMERIC  NOT NULL ,
     franquicia           VARCHAR(200)  NOT NULL ,
     nombreTitular        VARCHAR(200)  NOT NULL,

    CONSTRAINT pk_tarjeta_credito_01 PRIMARY KEY (idMetodoPago)
);

CREATE TABLE TarjetaDebito (
     idMetodoPago NUMERIC  NOT NULL UNIQUE ,
     numeroTarjeta    NUMERIC  NOT NULL ,
     hashTarjeta      VARCHAR(200)  NOT NULL ,
     nombreTitular    VARCHAR(200)  NOT NULL,

    CONSTRAINT pk_tarjeta_debito_01 PRIMARY KEY (idMetodoPago)
);

CREATE TABLE Telefono (
     idTelefono                        NUMERIC  NOT NULL UNIQUE,
     codigoPais                        NUMERIC  NOT NULL ,
     codigoOperadora                   NUMERIC  NOT NULL ,
     numeroAbonado                     NUMERIC  NOT NULL ,
     ClienteJuridico_idClienteJuridico NUMERIC,
     ClienteNatural_idClienteNatural   NUMERIC,

    CONSTRAINT arc_telefono_01 CHECK ( (  (ClienteNatural_idClienteNatural IS NOT NULL
                               AND (ClienteJuridico_idClienteJuridico IS NULL) ) OR (  (ClienteJuridico_idClienteJuridico IS NOT NULL)
                               AND (ClienteNatural_idClienteNatural IS NULL) ) ) ),
    CONSTRAINT pk_telefono_01 PRIMARY KEY (idTelefono)
);

CREATE TABLE TipoCuerpo (
     idTipoCuerpo NUMERIC  NOT NULL UNIQUE,
     nombre       VARCHAR(150)  NOT NULL ,
     descripcion  VARCHAR(600)  NOT NULL,

    CONSTRAINT pk_tipo_cuerpo_01 PRIMARY KEY (idTipoCuerpo)
);

CREATE TABLE TipoDiseño (
     idTipoDiseño NUMERIC  NOT NULL UNIQUE,
     nombre       VARCHAR(150)  NOT NULL,

    CONSTRAINT pk_tipo_diseño_01 PRIMARY KEY (idTipoDiseño)
);

CREATE TABLE TipoPieza (
     idTipoPieza NUMERIC  NOT NULL UNIQUE,
     nombre      VARCHAR(150)  NOT NULL,

    CONSTRAINT pk_tipo_pieza_01 PRIMARY KEY (idTipoPieza)
);

CREATE TABLE TipoRelacion (
     idTipoRelacion   NUMERIC  NOT NULL UNIQUE,
     nombreRelacion   VARCHAR(150)  NOT NULL ,
     Diseño_idDiseño  NUMERIC  NOT NULL ,
     Diseño_idDiseño2 NUMERIC  NOT NULL,

    CONSTRAINT pk_tipo_relacion_01 PRIMARY KEY (idTipoRelacion, Diseño_idDiseño, Diseño_idDiseño2)
);

CREATE TABLE TipoUbicacionStock (
     idTipoUbicacionStock NUMERIC  NOT NULL UNIQUE,
     nombre               VARCHAR(150)  NOT NULL,
     direccion            VARCHAR(150)  NOT NULL,
     Lugar_idLugar        NUMERIC  NOT NULL,
     UnidadProducida_idUnidadProducidad NUMERIC NOT NULL,

    CONSTRAINT pk_tipo_ubicacion_stock_01 PRIMARY KEY (idTipoUbicacionStock)
);

CREATE TABLE TonoPiel (
     idTonoPiel        NUMERIC  NOT NULL UNIQUE,
     nombre            VARCHAR(150)  NOT NULL ,
     escalaFitzpatrick DATE  NOT NULL ,
     valorClaridad     VARCHAR(50)  NOT NULL ,
     luminosidad       NUMERIC  NOT NULL,

    CONSTRAINT pk_tono_piel_01 PRIMARY KEY (idTonoPiel)
);

CREATE TABLE Transporte (
     idTransporte      NUMERIC  NOT NULL UNIQUE,
     matricula         VARCHAR(150)  NOT NULL ,
     nombreConductor   VARCHAR(150)  NOT NULL ,
     apellidoConductor VARCHAR(150)  NOT NULL ,

    CONSTRAINT pk_transporte_01 PRIMARY KEY (idTransporte)
);

CREATE TABLE Turno (
     idTurno           NUMERIC  NOT NULL UNIQUE,
     porcentajeRecargo NUMERIC  NOT NULL ,
     nombre            VARCHAR(150)  NOT NULL ,

    CONSTRAINT pk_turno_01 PRIMARY KEY (idTurno)
);

CREATE TABLE TurnoEmpleado (
     idTurnoEmpleado NUMERIC  NOT NULL UNIQUE,
     fecha           DATE  NOT NULL ,
     feriado         CHAR(1)  NOT NULL ,
     Empleado_idEmpleado     NUMERIC  NOT NULL ,
     Turno_idTurno   NUMERIC  NOT NULL,

    CONSTRAINT pk_turno_empleado_01 PRIMARY KEY (idTurnoEmpleado, Empleado_idEmpleado, Turno_idTurno)
);

CREATE TABLE TurnoHorario (
     idTurnoHorario    NUMERIC NOT NULL ,
     Horario_idHorario NUMERIC NOT NULL ,
     Turno_idTurno     NUMERIC NOT NULL,

    CONSTRAINT pk_turno_horario_01 PRIMARY KEY (idTurnoHorario, Horario_idHorario, Turno_idTurno)
);

CREATE TABLE UnidadProducida (
     idUnidadProducidad                 NUMERIC  NOT NULL UNIQUE,
     fechaSalida                        DATE  NOT NULL ,
     nombre                             VARCHAR(150)  NOT NULL ,
     LoteProduccion_idLote              NUMERIC  NOT NULL ,

    CONSTRAINT pk_unidad_producida_01 PRIMARY KEY (idUnidadProducidad)
);

CREATE TABLE Usuario (
     idUsuario                       NUMERIC  NOT NULL UNIQUE,
     nombreUsuario                   VARCHAR(50)  NOT NULL ,
     correoElectronico               VARCHAR(100)  NOT NULL ,
     contraseña                      VARCHAR(255)  NOT NULL ,
     estado                          VARCHAR(20)  NOT NULL ,
     fechaRegistro                   DATE  NOT NULL ,
     Empleado_idEmpleado             NUMERIC NOT NULL,
     Rol_idRol NUMERIC NOT NULL,
     ClienteNatural_idClienteNatural NUMERIC,

    CONSTRAINT pk_usuario_01 PRIMARY KEY (idUsuario)
);

CREATE TABLE ValoracionMercado (
     idValoracionMercado                NUMERIC  NOT NULL UNIQUE,
     fechaValoracion                    DATE  NOT NULL ,
     precioDelMercado                   NUMERIC  NOT NULL ,
     UnidadProducida_idUnidadProducidad NUMERIC  NOT NULL,

    CONSTRAINT pk_valoracion_mercado_01 PRIMARY KEY (idValoracionMercado)
);

CREATE TABLE Caja (
    idCaja    NUMERIC  NOT NULL,
    nombre    VARCHAR(150)  NOT NULL,
    capacidad NUMERIC  NOT NULL,

    CONSTRAINT pk_caja_01 PRIMARY KEY (idCaja)
);

/* CREATE DE LAS SECUENCIAS */

CREATE SEQUENCE Caja_SEQ START WITH 1 INCREMENT BY 1;
CREATE SEQUENCE Ambiente_SEQ START WITH 1 INCREMENT BY 1;
CREATE SEQUENCE AsignacionMeta_SEQ START WITH 1 INCREMENT BY 1;
CREATE SEQUENCE Asistencia_SEQ START WITH 1 INCREMENT BY 1;
CREATE SEQUENCE AutorDiseño_SEQ START WITH 1 INCREMENT BY 1;
CREATE SEQUENCE BackOrder_SEQ START WITH 1 INCREMENT BY 1;
CREATE SEQUENCE ChequeCorporativo_SEQ START WITH 1 INCREMENT BY 1;
CREATE SEQUENCE ClasificacionExclusividad_SEQ START WITH 1 INCREMENT BY 1;
CREATE SEQUENCE ClasificacionHistorica_SEQ START WITH 1 INCREMENT BY 1;
CREATE SEQUENCE ClienteJuridico_SEQ START WITH 1 INCREMENT BY 1;
CREATE SEQUENCE ClienteNatural_SEQ START WITH 1 INCREMENT BY 1;
CREATE SEQUENCE Color_SEQ START WITH 1 INCREMENT BY 1;
CREATE SEQUENCE ComisionVenta_SEQ START WITH 1 INCREMENT BY 1;
CREATE SEQUENCE Compra_SEQ START WITH 1 INCREMENT BY 1;
CREATE SEQUENCE CompraDescuento_SEQ START WITH 1 INCREMENT BY 1;
CREATE SEQUENCE Conciliacion_SEQ START WITH 1 INCREMENT BY 1;
CREATE SEQUENCE CondicionFisica_SEQ START WITH 1 INCREMENT BY 1;
CREATE SEQUENCE Courier_SEQ START WITH 1 INCREMENT BY 1;
CREATE SEQUENCE CriptoActivo_SEQ START WITH 1 INCREMENT BY 1;
CREATE SEQUENCE CurriculumVitae_SEQ START WITH 1 INCREMENT BY 1;
CREATE SEQUENCE Departamento_SEQ START WITH 1 INCREMENT BY 1;
CREATE SEQUENCE Descuento_SEQ START WITH 1 INCREMENT BY 1;
CREATE SEQUENCE DespachoNatural_SEQ START WITH 1 INCREMENT BY 1;
CREATE SEQUENCE DetalleCompraJuridico_SEQ START WITH 1 INCREMENT BY 1;
CREATE SEQUENCE DetalleCompraNatural_SEQ START WITH 1 INCREMENT BY 1;
CREATE SEQUENCE DevolucionJuridica_SEQ START WITH 1 INCREMENT BY 1;
CREATE SEQUENCE DevolucionNatural_SEQ START WITH 1 INCREMENT BY 1;
CREATE SEQUENCE Diseño_SEQ START WITH 1 INCREMENT BY 1;
CREATE SEQUENCE DiseñoAmbiente_SEQ START WITH 1 INCREMENT BY 1;
CREATE SEQUENCE Efectivo_SEQ START WITH 1 INCREMENT BY 1;
CREATE SEQUENCE Empleado_SEQ START WITH 1 INCREMENT BY 1;
CREATE SEQUENCE EstadoOrden_SEQ START WITH 1 INCREMENT BY 1;
CREATE SEQUENCE Estatus_SEQ START WITH 1 INCREMENT BY 1;
CREATE SEQUENCE Fase_SEQ START WITH 1 INCREMENT BY 1;
CREATE SEQUENCE FaseEmpleado_SEQ START WITH 1 INCREMENT BY 1;
CREATE SEQUENCE HistoricoEmpleado_SEQ START WITH 1 INCREMENT BY 1;
CREATE SEQUENCE HistoricoEstado_SEQ START WITH 1 INCREMENT BY 1;
CREATE SEQUENCE HistoricoEstatus_SEQ START WITH 1 INCREMENT BY 1;
CREATE SEQUENCE Horario_SEQ START WITH 1 INCREMENT BY 1;
CREATE SEQUENCE InsumoProduccion_SEQ START WITH 1 INCREMENT BY 1;
CREATE SEQUENCE ListaPrecioMayorista_SEQ START WITH 1 INCREMENT BY 1;
CREATE SEQUENCE LoteMateriaPrima_SEQ START WITH 1 INCREMENT BY 1;
CREATE SEQUENCE LoteProduccion_SEQ START WITH 1 INCREMENT BY 1;
CREATE SEQUENCE Lugar_SEQ START WITH 1 INCREMENT BY 1;
CREATE SEQUENCE ManifiestoCarga_SEQ START WITH 1 INCREMENT BY 1;
CREATE SEQUENCE Material_SEQ START WITH 1 INCREMENT BY 1;
CREATE SEQUENCE MaterialDiseño_SEQ START WITH 1 INCREMENT BY 1;
CREATE SEQUENCE Membresia_SEQ START WITH 1 INCREMENT BY 1;
CREATE SEQUENCE MetaMensual_SEQ START WITH 1 INCREMENT BY 1;
CREATE SEQUENCE MoldeRostro_SEQ START WITH 1 INCREMENT BY 1;
CREATE SEQUENCE MonitorActividadSopechosa_SEQ START WITH 1 INCREMENT BY 1;
CREATE SEQUENCE ObjetivoGlobal_SEQ START WITH 1 INCREMENT BY 1;
CREATE SEQUENCE ObjetivoGlobalProducto_SEQ START WITH 1 INCREMENT BY 1;
CREATE SEQUENCE OrdenCompra_SEQ START WITH 1 INCREMENT BY 1;
CREATE SEQUENCE OrdenCompraDescuento_SEQ START WITH 1 INCREMENT BY 1;
CREATE SEQUENCE OrdenVenta_SEQ START WITH 1 INCREMENT BY 1;
CREATE SEQUENCE Pack_SEQ START WITH 1 INCREMENT BY 1;
CREATE SEQUENCE PagoJuridico_SEQ START WITH 1 INCREMENT BY 1;
CREATE SEQUENCE PagoNatural_SEQ START WITH 1 INCREMENT BY 1;
CREATE SEQUENCE PayPal_SEQ START WITH 1 INCREMENT BY 1;
CREATE SEQUENCE Permiso_SEQ START WITH 1 INCREMENT BY 1;
CREATE SEQUENCE Pieza_SEQ START WITH 1 INCREMENT BY 1;
CREATE SEQUENCE PiezaProducto_SEQ START WITH 1 INCREMENT BY 1;
CREATE SEQUENCE Producto_SEQ START WITH 1 INCREMENT BY 1;
CREATE SEQUENCE Profesion_SEQ START WITH 1 INCREMENT BY 1;
CREATE SEQUENCE Prueba_SEQ START WITH 1 INCREMENT BY 1;
CREATE SEQUENCE PruebaEmpleado_SEQ START WITH 1 INCREMENT BY 1;
CREATE SEQUENCE PuestoTrabajo_SEQ START WITH 1 INCREMENT BY 1;
CREATE SEQUENCE Puja_SEQ START WITH 1 INCREMENT BY 1;
CREATE SEQUENCE Regalia_SEQ START WITH 1 INCREMENT BY 1;
CREATE SEQUENCE Restriccion_SEQ START WITH 1 INCREMENT BY 1;
CREATE SEQUENCE RestriccionDiseño_SEQ START WITH 1 INCREMENT BY 1;
CREATE SEQUENCE Rol_SEQ START WITH 1 INCREMENT BY 1;
CREATE SEQUENCE RolPermiso_SEQ START WITH 1 INCREMENT BY 1;
CREATE SEQUENCE Sancion_SEQ START WITH 1 INCREMENT BY 1;
CREATE SEQUENCE StockClienteNatural_SEQ START WITH 1 INCREMENT BY 1;
CREATE SEQUENCE Subasta_SEQ START WITH 1 INCREMENT BY 1;
CREATE SEQUENCE SubEnsamblaje_SEQ START WITH 1 INCREMENT BY 1;
CREATE SEQUENCE Swift_SEQ START WITH 1 INCREMENT BY 1;
CREATE SEQUENCE TarjetaCredito_SEQ START WITH 1 INCREMENT BY 1;
CREATE SEQUENCE TarjetaDebito_SEQ START WITH 1 INCREMENT BY 1;
CREATE SEQUENCE Telefono_SEQ START WITH 1 INCREMENT BY 1;
CREATE SEQUENCE TipoCuerpo_SEQ START WITH 1 INCREMENT BY 1;
CREATE SEQUENCE TipoDiseño_SEQ START WITH 1 INCREMENT BY 1;
CREATE SEQUENCE TipoPieza_SEQ START WITH 1 INCREMENT BY 1;
CREATE SEQUENCE TipoRelacion_SEQ START WITH 1 INCREMENT BY 1;
CREATE SEQUENCE TipoUbicacionStock_SEQ START WITH 1 INCREMENT BY 1;
CREATE SEQUENCE TonoPiel_SEQ START WITH 1 INCREMENT BY 1;
CREATE SEQUENCE Transporte_SEQ START WITH 1 INCREMENT BY 1;
CREATE SEQUENCE Turno_SEQ START WITH 1 INCREMENT BY 1;
CREATE SEQUENCE TurnoEmpleado_SEQ START WITH 1 INCREMENT BY 1;
CREATE SEQUENCE TurnoHorario_SEQ START WITH 1 INCREMENT BY 1;
CREATE SEQUENCE UnidadProducida_SEQ START WITH 1 INCREMENT BY 1;
CREATE SEQUENCE Usuario_SEQ START WITH 1 INCREMENT BY 1;
CREATE SEQUENCE ValoracionMercado_SEQ START WITH 1 INCREMENT BY 1;

-- Oracle SQL Developer Data Modeler Summary Report:
--
-- CREATE TABLE                            95
-- CREATE INDEX                             5
-- ALTER TABLE                            226
-- CREATE VIEW                              0
-- ALTER VIEW                               0
-- CREATE PACKAGE                           0
-- CREATE PACKAGE BODY                      0
-- CREATE PROCEDURE                         0
-- CREATE FUNCTION                          0
-- CREATE TRIGGER                           0
-- ALTER TRIGGER                            0
-- CREATE COLLECTION TYPE                   0
-- CREATE STRUCTURED TYPE                   0
-- CREATE STRUCTURED TYPE BODY              0
-- CREATE CLUSTER                           0
-- CREATE CONTEXT                           0
-- CREATE DATABASE                          0
-- CREATE DIMENSION                         0
-- CREATE DIRECTORY                         0
-- CREATE DISK GROUP                        0
-- CREATE ROLE                              0
-- CREATE ROLLBACK SEGMENT                  0
-- CREATE SEQUENCE                          0
-- CREATE MATERIALIZED VIEW                 0
-- CREATE MATERIALIZED VIEW LOG             0
-- CREATE SYNONYM                           0
-- CREATE TABLESPACE                        0
-- CREATE USER                              0
--
-- DROP TABLESPACE                          0
-- DROP DATABASE                            0
--
-- REDACTION POLICY                         0
--
-- ORDS DROP SCHEMA                         0
-- ORDS ENABLE SCHEMA                       0
-- ORDS ENABLE OBJECT                       0
--
-- ERRORS                                  83
-- WARNINGS                                 0
