-- Generated by Oracle SQL Developer Data Modeler 24.3.1.351.0831
--   at:        2026-06-15 23:10:57 VET
--   site:      Oracle Database 11g
--   type:      Oracle Database 11g



-- predefined type, no DDL - MDSYS.SDO_GEOMETRY

-- predefined type, no DDL - XMLTYPE

CREATE TABLE Ambiente (
    idAmbiente  NUMERIC(1000)  NOT NULL UNIQUE,
    nombre      VARCHAR(150)  NOT NULL,
    descripcion VARCHAR(600)  NOT NULL,

    CONSTRAINT pk_ambiente_01 PRIMARY KEY (idAmbiente)
);

CREATE TABLE AsignacionMeta (
    idAsignacionMeta              NUMERIC  NOT NULL UNIQUE,
    metaCumplida                  CHAR(1)  NOT NULL ,
    MetaMensual_idMetaMensual     NUMERIC  NOT NULL ,
    Empleado_idEmpleado                 NUMERIC  NOT NULL ,
    ComisionVenta_idComisionVenta NUMERIC  NOT NULL,

    CONSTRAINT pk_asignacion_meta_01 PRIMARY KEY (idAsignacionMeta, MetaMensual_idMetaMensual, Empleado_idEmpleado)
);

CREATE TABLE Asistencia (
     idAsistencia        NUMERIC NOT NULL ,
     fecha               DATE NOT NULL ,
     horaEntrada         TIME NOT NULL ,
     horaSalida          TIME NOT NULL ,
     Empleado_idEmpleado NUMERIC NOT NULL,

     CONSTRAINT pk_asistencia_01 PRIMARY KEY ( idAsistencia )
);

CREATE TABLE AutorDiseño (
     idAutorDiseño                   NUMERIC  NOT NULL UNIQUE,
     Diseño_idDiseño                 NUMERIC  NOT NULL,
     Empleado_id                     NUMERIC  NOT NULL,
     Regalia_idRegalia               NUMERIC  NOT NULL,
     ObjetivoGlobal_idObjetivoGlobal NUMERIC  NOT NULL,

    CONSTRAINT pk_autor_diseño_01 PRIMARY KEY (idAutorDiseño, Diseño_idDiseño, Empleado_id)
);

CREATE TABLE BackOrder(
     idBackOrder           NUMERIC  NOT NULL UNIQUE,
     cantidadPendiente     NUMERIC  NOT NULL,
     precioOriginalPactado NUMERIC  NOT NULL,
     fechaGeneracion       DATE  NOT NULL,
     estatus               NUMERIC NOT NULL,

    CONSTRAINT pk_backorder_01 PRIMARY KEY (idBackOrder)
);

CREATE TABLE ChequeCorporativo (
     idMetodoPago            NUMERIC  NOT NULL UNIQUE,
     numeroCheque        NUMERIC  NOT NULL,
     numeroCuentaEmisora NUMERIC  NOT NULL,
     bancoEmisor         NUMERIC  NOT NULL,

    CONSTRAINT pk_cheque_corporativo_01 PRIMARY KEY (idMetodoPago)
);

CREATE TABLE ClasificacionExclusividad (
     idClasificacionExclusividad NUMERIC  NOT NULL UNIQUE,
     nombre VARCHAR(150)  NOT NULL ,
     descripcion VARCHAR(600)  NOT NULL,

    CONSTRAINT pk_clasificacion_exclusividad_01 PRIMARY KEY (idClasificacionExclusividad)
);

CREATE TABLE ClasificacionHistorica (
     idClasificacionHistorica NUMERIC  NOT NULL ,
     nombre                   VARCHAR(150)  NOT NULL ,
     descripcion              VARCHAR(600)  NOT NULL,

    CONSTRAINT pk_clasificacion_historica_01 PRIMARY KEY (idClasificacionHistorica)
);

CREATE TABLE ClienteJuridico (
     idClienteJuridico NUMERIC  NOT NULL ,
     rif               VARCHAR(15) NOT NULL,
     razonSocial       VARCHAR(150)  NOT NULL ,
     nombre            VARCHAR(150)  NOT NULL ,
     direccionJuridica VARCHAR(150)  NOT NULL ,
     limiteCredito     NUMERIC  NOT NULL,
     Lugar_idLugar NUMERIC NOT NULL,

    CONSTRAINT pk_cliente_juridico_01 PRIMARY KEY (idClienteJuridico)
);

CREATE TABLE ClienteNatural (
     idClienteNatural                                      NUMERIC  NOT NULL,
     cedula                                                NUMERIC  NOT NULL,
     pNombre                                               VARCHAR(150)  NOT NULL,
     sNombre                                               VARCHAR(150),
     pApellido                                             VARCHAR(150)  NOT NULL,
     sApellido                                             VARCHAR(150),
     direccion                                             VARCHAR(150)  NOT NULL,
     MonitorActividadSopechosa_idMonitorActividadSopechosa NUMERIC  NOT NULL,
     Lugar_idLugar NUMERIC NOT NULL,

    CONSTRAINT pk_cliente_natural_01 PRIMARY KEY (idClienteNatural)
);

CREATE TABLE Color (
     idColor           NUMERIC  NOT NULL UNIQUE,
     codigoHexadecimal VARCHAR(150)  NOT NULL ,
     nombre            VARCHAR(150)  NOT NULL,

    CONSTRAINT pk_color_01 PRIMARY KEY (idColor)
);

CREATE TABLE ComisionVenta (
     idComisionVenta           NUMERIC  NOT NULL UNIQUE,
     montoComision             NUMERIC  NOT NULL,
     fecha                     DATE  NOT NULL,
     OrdenCompra_idOrdenCompra NUMERIC  NOT NULL,

    CONSTRAINT pk_comision_venta_01 PRIMARY KEY (idComisionVenta)
);

CREATE TABLE Compra (
     idCompra                                NUMERIC  NOT NULL ,
     fechaHora                               DATE  NOT NULL ,
     numeroCompra                            NUMERIC  NOT NULL ,
     totalPagar                              NUMERIC  NOT NULL ,
     subTotal                                NUMERIC  NOT NULL ,
     ClienteNatural_idClienteNatural         NUMERIC  NOT NULL ,
     TipoUbicacionStock_idTipoUbicacionStock NUMERIC  NOT NULL,

    CONSTRAINT pk_compra_01 PRIMARY KEY (idCompra)
);

CREATE TABLE CompraDescuento (
     idCompraDescuento     NUMERIC  NOT NULL ,
     monto NUMERIC NOT NULL,
     Compra_idCompra       NUMERIC  NOT NULL ,
     Descuento_idDescuento NUMERIC  NOT NULL,

    CONSTRAINT pk_compra_descuento_01 PRIMARY KEY (idCompraDescuento, Compra_idCompra, Descuento_idDescuento)
);

CREATE TABLE Conciliacion (
    idConciliacion            NUMERIC NOT NULL,
    montoAplicado             NUMERIC NOT NULL,
    fechaAplicacion           DATE NOT NULL,
    OrdenCompra_idOrdenCompra NUMERIC NOT NULL,
    PagoJuridico_idPago       NUMERIC NOT NULL,

    CONSTRAINT pk_conciliacion_01 PRIMARY KEY (idConciliacion, OrdenCompra_idOrdenCompra, PagoJuridico_idPago)
);

CREATE TABLE CondicionFisica (
     idCondicionFisica NUMERIC  NOT NULL ,
     nombre            VARCHAR(150)  NOT NULL ,
     descripcion       VARCHAR(600)  NOT NULL,

    CONSTRAINT pk_condicion_fisica_01 PRIMARY KEY (idCondicionFisica)
);

CREATE TABLE Courier (
     idCourier NUMERIC  NOT NULL ,
     nombre    VARCHAR(150)  NOT NULL,

    CONSTRAINT pk_courier_01 PRIMARY KEY (idCourier)
);

CREATE TABLE CriptoActivo (
     idMetodoPago  NUMERIC  NOT NULL UNIQUE,
     hashTransaccion VARCHAR(200)  NOT NULL ,
     redBlockchain   VARCHAR(200)  NOT NULL ,
     billeteraOrigen VARCHAR(200)  NOT NULL,

    CONSTRAINT pk_cripto_activo_01 PRIMARY KEY (idMetodoPago)
);

CREATE TABLE CurriculumVitae (
    idCurriculumVitae     NUMERIC  NOT NULL UNIQUE,
    añoDeAsignacion       NUMERIC  NOT NULL ,
    Profesion_idProfesion NUMERIC  NOT NULL ,
    Diseño_idDiseño       NUMERIC  NOT NULL,

    CONSTRAINT pk_curriculum_vitae_01 PRIMARY KEY (idCurriculumVitae, Profesion_idProfesion, Diseño_idDiseño)
);

CREATE TABLE Departamento (
     idDepartamento NUMERIC  NOT NULL ,
     nombre         VARCHAR(150)  NOT NULL ,
     direccion      VARCHAR(150)  NOT NULL,

    CONSTRAINT pk_departamento_01 PRIMARY KEY (idDepartamento)
);

CREATE TABLE Descuento (
     idDescuento       NUMERIC  NOT NULL ,
     nombre            VARCHAR(150)  NOT NULL ,
     descripcion       VARCHAR(600)  NOT NULL ,
     porcentaje        NUMERIC  NOT NULL ,

    CONSTRAINT pk_descuento_01 PRIMARY KEY (idDescuento)
);

CREATE TABLE DespachoNatural (
    idDespachoNatural NUMERIC  NOT NULL ,
    numeroTracking    NUMERIC  NOT NULL ,
    alto              NUMERIC  NOT NULL ,
    ancho             NUMERIC  NOT NULL ,
    largo             NUMERIC  NOT NULL ,
    costoEnvio        NUMERIC  NOT NULL ,
    Compra_idCompra   NUMERIC  NOT NULL ,
    Courier_idCourier NUMERIC  NOT NULL,

    CONSTRAINT pk_despacho_natural_01 PRIMARY KEY (idDespachoNatural)
);

CREATE TABLE DetalleCompraJuridico (
     idDetalleCompraJuridico     NUMERIC  NOT NULL,
     precioUnitario              NUMERIC  NOT NULL,
     cantidad                    NUMERIC  NOT NULL,
     estado                      VARCHAR(150)  NOT NULL,
     OrdenCompra_idOrdenCompra   NUMERIC  NOT NULL,
     BackOrder_idBackOrder       NUMERIC  NOT NULL,

    CONSTRAINT pk_detalle_compra_juridico_01 PRIMARY KEY (idDetalleCompraJuridico, OrdenCompra_idOrdenCompra)
);

CREATE UNIQUE INDEX DetalleCompraJuridico__IDX ON DetalleCompraJuridico ( BackOrder_idBackOrder ASC );

CREATE TABLE DetalleCompraNatural (
     idDetalleCompraNatural             NUMERIC  NOT NULL UNIQUE ,
     precioUnitario                     NUMERIC  NOT NULL,
     UnidadProducida_idUnidadProducidad NUMERIC  NOT NULL,
     Compra_idCompra                    NUMERIC  NOT NULL,

    CONSTRAINT pk_detalle_compra_natural_01 PRIMARY KEY (idDetalleCompraNatural, UnidadProducida_idUnidadProducidad, Compra_idCompra)
);

CREATE TABLE DevolucionJuridica (
    idDevolucionJuridica      NUMERIC  NOT NULL UNIQUE,
    fechaDevolucion           DATE  NOT NULL ,
    motivo                    VARCHAR(600)  NOT NULL ,
    OrdenCompra_idOrdenCompra NUMERIC  NOT NULL,

    CONSTRAINT pk_devolucion_juridica_01 PRIMARY KEY (idDevolucionJuridica)
);

CREATE TABLE DevolucionNatural (
     idDevolucionNatural NUMERIC  NOT NULL ,
     fechaDevolucion     DATE  NOT NULL ,
     motivo              VARCHAR(600)  NOT NULL ,
     Compra_idCompra     NUMERIC  NOT NULL,

    CONSTRAINT pk_devolucion_natural_01 PRIMARY KEY (idDevolucionNatural)
);

CREATE TABLE Diseño (
    idDiseño                                              NUMERIC  NOT NULL ,
    nombre                                                VARCHAR(150)  NOT NULL ,
    descripcion                                           VARCHAR(600)  NOT NULL ,
    ClasificacionHistorica_idClasificacionHistorica       NUMERIC  NOT NULL,
    ClasificacionExclusividad_idClasificacionExclusividad NUMERIC  NOT NULL,
    TonoPiel_idTonoPiel                                   NUMERIC  NOT NULL,
    MoldeRostro_idMoldeRostro                             NUMERIC  NOT NULL,
    Diseño_idDiseño                                       NUMERIC,
    TipoDiseño_idTipoDiseño                               NUMERIC  NOT NULL,

    CONSTRAINT pk_diseño_01 PRIMARY KEY (idDiseño)
);

CREATE TABLE DiseñoAmbiente (
     idDiseñoAmbiente    NUMERIC  NOT NULL UNIQUE,
     interactivo         CHAR(1),
     Diseño_idDiseño     NUMERIC  NOT NULL,
     Ambiente_idAmbiente NUMERIC  NOT NULL,

    CONSTRAINT pk_diseño_ambiente_01 PRIMARY KEY (idDiseñoAmbiente, Diseño_idDiseño, Ambiente_idAmbiente)
);

CREATE TABLE Efectivo (
    idMetodoPago                 NUMERIC  NOT NULL UNIQUE,
    numeroSerie                VARCHAR(200)  NOT NULL,
    letraNumeroReservaFederal1 VARCHAR(200)  NOT NULL,

    CONSTRAINT pk_efectivo_01 PRIMARY KEY (idMetodoPago)
);

CREATE TABLE Empleado (
     idEmpleado              NUMERIC  NOT NULL UNIQUE ,
     cedula          NUMERIC  NOT NULL ,
     pNombre         VARCHAR(150)  NOT NULL ,
     sNombre         VARCHAR(150) ,
     pApellido       VARCHAR(150)  NOT NULL ,
     sApellido       VARCHAR(150) ,
     fechaNacimiento DATE  NOT NULL ,
     direccion       VARCHAR(200)  NOT NULL ,
     Lugar_idLugar   NUMERIC  NOT NULL,

    CONSTRAINT pk_empleado_01 PRIMARY KEY (idEmpleado)
);

CREATE TABLE EstadoOrden (
     idEstadoOrden NUMERIC  NOT NULL UNIQUE,
     nombre        VARCHAR(150)  NOT NULL ,
     descripcion   VARCHAR(600)  NOT NULL,

    CONSTRAINT pk_estado_orden_01 PRIMARY KEY (idEstadoOrden)
);

CREATE TABLE Estatus (
     idEstatus   NUMERIC NOT NULL ,
     nombre      VARCHAR(150) NOT NULL ,
     tipoEstatus VARCHAR(150) NOT NULL,
     CONSTRAINT pk_estatus_01 PRIMARY KEY ( idEstatus )
);

CREATE TABLE Fase (
     idFase          NUMERIC NOT NULL ,
     nombreFase      VARCHAR(150) NOT NULL ,
     descripcionFase VARCHAR(600) ,
     Diseño_idDiseño NUMERIC NOT NULL,

    CONSTRAINT pk_fase_01 PRIMARY KEY ( idFase )
);

CREATE TABLE FaseEmpleado (
     idFaseEmpleado      NUMERIC NOT NULL ,
     fechaInicio         DATE NOT NULL ,
     fechaFin            DATE ,
     Empleado_idEmpleado NUMERIC NOT NULL ,
     Fase_idFase         NUMERIC NOT NULL,

    CONSTRAINT pk_fase_empleado_01 PRIMARY KEY (idFaseEmpleado, Empleado_idEmpleado, Fase_idFase)
);

CREATE TABLE HistoricoEmpleado (
     idHistoricoEmpleado                     NUMERIC  NOT NULL UNIQUE,
     fechaInicio                             DATE  NOT NULL ,
     fechaFin                                DATE,
     salarioBase                             NUMERIC  NOT NULL ,
     Empleado_idEmpleado                             NUMERIC  NOT NULL ,
     Departamento_idDepartamento             NUMERIC  NOT NULL ,
     PuestoTrabajo_id                        NUMERIC  NOT NULL ,
     TipoUbicacionStock_idTipoUbicacionStock NUMERIC  NOT NULL,

    CONSTRAINT pk_historico_empleado_01 PRIMARY KEY (idHistoricoEmpleado, Empleado_idEmpleado, Departamento_idDepartamento)
);

CREATE TABLE HistoricoEstado (
    idHistoricoEstado         NUMERIC  NOT NULL,
    fechaHora                 DATE  NOT NULL,
    OrdenCompra_idOrdenCompra NUMERIC  NOT NULL,
    EstadoOrden_idEstadoOrden NUMERIC  NOT NULL,
    Compra_idCompra           NUMERIC  NOT NULL,

    CONSTRAINT arc_historico_estado_01 CHECK ( (  (OrdenCompra_idOrdenCompra IS NOT NULL) AND (Compra_idCompra IS NULL) ) OR (  (Compra_idCompra IS NOT NULL) AND (OrdenCompra_idOrdenCompra IS NULL) ) ),
    CONSTRAINT pk_historico_estado_01 PRIMARY KEY (idHistoricoEstado, EstadoOrden_idEstadoOrden)
);

CREATE TABLE HistoricoEstatus (
     idHistoricoEstatus      NUMERIC NOT NULL ,
     fechaHoraInicio         DATE NOT NULL ,
     Estatus_idEstatus       NUMERIC NOT NULL ,
     fechaHoraFin            DATE ,
     Subasta_idSubasta       NUMERIC ,
     Puja_idPuja             NUMERIC ,
     Puja_idClienteNatural   NUMERIC ,
     Puja_idSubasta          NUMERIC ,
     OrdenVenta_idOrdenVenta NUMERIC ,
     Compra_idCompra         NUMERIC,

    CONSTRAINT arc_historico_estatus_01 CHECK ( (  (Compra_idCompra IS NOT NULL) AND
         (Puja_idPuja IS NULL)  AND
         (Puja_idClienteNatural IS NULL)  AND
         (Puja_idSubasta IS NULL)  AND
         (Subasta_idSubasta IS NULL)  AND
         (OrdenVenta_idOrdenVenta IS NULL) ) OR
         ( (Puja_idPuja IS NOT NULL) AND
         (Puja_idClienteNatural IS NOT NULL) AND
         (Puja_idSubasta IS NOT NULL) AND
         (Compra_idCompra IS NULL)  AND
         (Subasta_idSubasta IS NULL)  AND
         (OrdenVenta_idOrdenVenta IS NULL) ) OR
         ( (Subasta_idSubasta IS NOT NULL) AND
         (Compra_idCompra IS NULL)  AND
         (Puja_idPuja IS NULL)  AND
         (Puja_idClienteNatural IS NULL)  AND
         (Puja_idSubasta IS NULL)  AND
         (OrdenVenta_idOrdenVenta IS NULL) ) OR
         ( (OrdenVenta_idOrdenVenta IS NOT NULL) AND
         (Compra_idCompra IS NULL)  AND
         (Puja_idPuja IS NULL)  AND
         (Puja_idClienteNatural IS NULL)  AND
         (Puja_idSubasta IS NULL)  AND
         (Subasta_idSubasta IS NULL) ) ),

    CONSTRAINT pk_historico_estatus_01 PRIMARY KEY ( idHistoricoEstatus, Estatus_idEstatus )
);

CREATE TABLE Horario (
    idHorario  NUMERIC  NOT NULL UNIQUE,
    dia        VARCHAR(150) NOT NULL,
    horaInicio TIME  NOT NULL,
    horaFin    TIME  NOT NULL,

    CONSTRAINT pk_horario_01 PRIMARY KEY (idHorario)
);

CREATE TABLE InsumoProduccion (
    idInsumoProduccion                  NUMERIC  NOT NULL UNIQUE,
    cantidad                            NUMERIC  NOT NULL,
    LoteMateriaPrima_idLoteMateriaPrima NUMERIC  NOT NULL,
    LoteProduccion_idLote               NUMERIC  NOT NULL,

    CONSTRAINT pk_insumo_produccion_01 PRIMARY KEY (idInsumoProduccion, LoteMateriaPrima_idLoteMateriaPrima, LoteProduccion_idLote)
);

CREATE TABLE ListaPrecioMayorista (
    idListaPrecioMayorista             NUMERIC  NOT NULL,
    precioUnitario                     NUMERIC  NOT NULL,
    fecha                              DATE  NOT NULL,
    ClienteJuridico_idClienteJuridico  NUMERIC  NOT NULL,
    UnidadProducida_idUnidadProducidad NUMERIC  NOT NULL,

    CONSTRAINT pk_lista_precio_mayorista_01 PRIMARY KEY (idListaPrecioMayorista, ClienteJuridico_idClienteJuridico, UnidadProducida_idUnidadProducidad)
);

CREATE TABLE LoteMateriaPrima (
     idLoteMateriaPrima  NUMERIC  NOT NULL UNIQUE,
     costoAdquisicion    NUMERIC  NOT NULL,
     nombre              VARCHAR(150)  NOT NULL,
     descripcion         VARCHAR(600)  NOT NULL,
     Material_idMaterial NUMERIC  NOT NULL,

    CONSTRAINT pk_lote_materia_prima_01 PRIMARY KEY (idLoteMateriaPrima)
);

CREATE TABLE LoteProduccion (
    idLote      NUMERIC  NOT NULL,
    fechaInicio DATE  NOT NULL,
    fechaFin    DATE  NOT NULL,

    CONSTRAINT pk_lote_produccion_01 PRIMARY KEY (idLote)
);

CREATE TABLE Lugar (
     idLugar       NUMERIC  NOT NULL UNIQUE,
     nombre        VARCHAR(150)  NOT NULL,
     tipo          VARCHAR(150)  NOT NULL,
     codigoPostal  NUMERIC  NOT NULL,
     Lugar_idLugar NUMERIC,

    CONSTRAINT pk_lugar_01 PRIMARY KEY (idLugar)
);

CREATE TABLE ManifiestoCarga (
     idManifiestoCarga         NUMERIC  NOT NULL UNIQUE,
     cantidadPaletas           NUMERIC  NOT NULL,
     cantidadCajasMaster       NUMERIC  NOT NULL,
     OrdenCompra_idOrdenCompra NUMERIC  NOT NULL,
     Transporte_idTransporte   NUMERIC  NOT NULL,

    CONSTRAINT pk_manifiesto_carga_01 PRIMARY KEY (idManifiestoCarga)
);

CREATE TABLE Material (
     idMaterial  NUMERIC  NOT NULL UNIQUE,
     nombre      VARCHAR(150)  NOT NULL,
     descripcion VARCHAR(600)  NOT NULL,

    CONSTRAINT pk_material_01 PRIMARY KEY (idMaterial)
);

CREATE TABLE MaterialDiseño (
    idMaterialDiseño    NUMERIC  NOT NULL UNIQUE,
    cantidad            NUMERIC  NOT NULL,
    Diseño_idDiseño     NUMERIC  NOT NULL,
    Pieza_idPieza       NUMERIC  NOT NULL,
    Material_idMaterial NUMERIC  NOT NULL,

    CONSTRAINT pk_material_diseño_01 PRIMARY KEY (idMaterialDiseño, Diseño_idDiseño)
);

CREATE TABLE Membresia (
    idMembresia                     NUMERIC  NOT NULL UNIQUE,
    nombre                          VARCHAR(150)  NOT NULL,
    descripcion                     VARCHAR(600)  NOT NULL,
    ClienteNatural_idClienteNatural NUMERIC  NOT NULL,

    CONSTRAINT pk_membresia_01 PRIMARY KEY (idMembresia)
);

CREATE TABLE MetaMensual (
     idMetaMensual      NUMERIC  NOT NULL UNIQUE,
     fechaInicio        DATE  NOT NULL,
     fechaFin           DATE  NOT NULL,
     porcentajeComision NUMERIC  NOT NULL,

    CONSTRAINT pk_meta_mensual_01 PRIMARY KEY (idMetaMensual)
);

CREATE TABLE MoldeRostro (
     idMoldeRostro NUMERIC  NOT NULL UNIQUE,
     nombre        VARCHAR(150)  NOT NULL,
     descripcion   VARCHAR(600)  NOT NULL,
     añoPatente    DATE  NOT NULL,

    CONSTRAINT pk_molde_rostro_01 PRIMARY KEY (idMoldeRostro)
);

CREATE TABLE MonitorActividadSopechosa (
     idMonitorActividadSopechosa NUMERIC  NOT NULL UNIQUE,
     fechaHora                   DATE  NOT NULL,
     ClienteNatural_idClienteNatural NUMERIC NOT NULL,

    CONSTRAINT pk_monitor_actividad_sospechosa_01 PRIMARY KEY (idMonitorActividadSopechosa)
);

CREATE TABLE ObjetivoGlobal (
     idObjetivoGlobal  NUMERIC  NOT NULL UNIQUE,
     volumenVentas     NUMERIC  NOT NULL,
     porcentajeRegalia NUMERIC  NOT NULL,

    CONSTRAINT pk_objetivo_global_01 PRIMARY KEY (idObjetivoGlobal)
);

CREATE TABLE ObjetivoGlobalProducto (
     idObjetivoGlobalProducto        NUMERIC  NOT NULL UNIQUE,
     objetivoSuperado                CHAR(1)  NOT NULL ,
     Producto_idProducto             NUMERIC  NOT NULL ,
     ObjetivoGlobal_idObjetivoGlobal NUMERIC  NOT NULL,

    CONSTRAINT pk_objetivo_global_producto_01 PRIMARY KEY (idObjetivoGlobalProducto, Producto_idProducto, ObjetivoGlobal_idObjetivoGlobal)
);

CREATE TABLE OrdenCompra (
     idOrdenCompra                     NUMERIC  NOT NULL UNIQUE,
     fechaEmision                      DATE  NOT NULL ,
     fechaVencimiento                  DATE  NOT NULL ,
     especificacionesTecnicas          VARCHAR(600)  NOT NULL ,
     precioUnitario                    NUMERIC  NOT NULL ,
     subTotal                          NUMERIC  NOT NULL ,
     impuestos                         NUMERIC  NOT NULL ,
     ClienteJuridico_idClienteJuridico NUMERIC  NOT NULL ,
     BackOrder_idBackOrder             NUMERIC  NOT NULL,

    CONSTRAINT pk_orden_compra_01 PRIMARY KEY (idOrdenCompra)
);
CREATE UNIQUE INDEX OrdenCompra__IDX ON OrdenCompra (
     BackOrder_idBackOrder ASC
);

CREATE TABLE OrdenCompraDescuento (
     idOrdenCompraDescuento    NUMERIC  NOT NULL UNIQUE,
     monto                     NUMERIC NOT NULL,
     OrdenCompra_idOrdenCompra NUMERIC  NOT NULL ,
     Descuento_idDescuento     NUMERIC  NOT NULL,

    CONSTRAINT pk_orden_compra_descuento_01 PRIMARY KEY (idOrdenCompraDescuento, OrdenCompra_idOrdenCompra, Descuento_idDescuento)
);

CREATE TABLE OrdenVenta (
     idOrdenVenta         NUMERIC  NOT NULL UNIQUE,
     fechaHoraEmision     DATE  NOT NULL ,
     fechaHoraVencimiento DATE  NOT NULL ,
     estatusPendientePago CHAR (1)  NOT NULL,

    CONSTRAINT pk_orden_venta_01 PRIMARY KEY (idOrdenVenta)
);

CREATE TABLE Pack (
     idPack               NUMERIC  NOT NULL UNIQUE,
     Producto_idProducto  NUMERIC  NOT NULL ,
     Producto_idProducto2 NUMERIC  NOT NULL,

    CONSTRAINT pk_pack_01 PRIMARY KEY (idPack, Producto_idProducto, Producto_idProducto2)
);

CREATE TABLE PagoJuridico (
    idPago      NUMERIC NOT NULL UNIQUE,
    monto       NUMERIC NOT NULL,
    fechaHora   DATE NOT NULL,

    Cheque_id   NUMERIC,
    Cripto_id   NUMERIC,
    Efectivo_id NUMERIC,
    PayPal_id   NUMERIC,
    Swift_id    NUMERIC,
    TarjCred_id NUMERIC,
    TarjDeb_id  NUMERIC,

    CONSTRAINT pk_pago_juridico_01 PRIMARY KEY (idPago),

    CONSTRAINT arc_pago_juridico_metodo CHECK (
      (Cheque_id IS NOT NULL AND Cripto_id IS NULL AND Efectivo_id IS NULL AND PayPal_id IS NULL AND Swift_id IS NULL AND TarjCred_id IS NULL AND TarjDeb_id IS NULL) OR
      (Cripto_id IS NOT NULL AND Cheque_id IS NULL AND Efectivo_id IS NULL AND PayPal_id IS NULL AND Swift_id IS NULL AND TarjCred_id IS NULL AND TarjDeb_id IS NULL) OR
      (Efectivo_id IS NOT NULL AND Cheque_id IS NULL AND Cripto_id IS NULL AND PayPal_id IS NULL AND Swift_id IS NULL AND TarjCred_id IS NULL AND TarjDeb_id IS NULL) OR
      (PayPal_id IS NOT NULL AND Cheque_id IS NULL AND Cripto_id IS NULL AND Efectivo_id IS NULL AND Swift_id IS NULL AND TarjCred_id IS NULL AND TarjDeb_id IS NULL) OR
      (Swift_id IS NOT NULL AND Cheque_id IS NULL AND Cripto_id IS NULL AND Efectivo_id IS NULL AND PayPal_id IS NULL AND TarjCred_id IS NULL AND TarjDeb_id IS NULL) OR
      (TarjCred_id IS NOT NULL AND Cheque_id IS NULL AND Cripto_id IS NULL AND Efectivo_id IS NULL AND PayPal_id IS NULL AND Swift_id IS NULL AND TarjDeb_id IS NULL) OR
      (TarjDeb_id IS NOT NULL AND Cheque_id IS NULL AND Cripto_id IS NULL AND Efectivo_id IS NULL AND PayPal_id IS NULL AND Swift_id IS NULL AND TarjCred_id IS NULL)
      )
);

CREATE TABLE PagoNatural (
    idPagoNatural   NUMERIC NOT NULL UNIQUE,
    Compra_idCompra NUMERIC NOT NULL,

    Cheque_id       NUMERIC,
    Cripto_id       NUMERIC,
    Efectivo_id     NUMERIC,
    PayPal_id       NUMERIC,
    Swift_id        NUMERIC,
    TarjCred_id     NUMERIC,
    TarjDeb_id      NUMERIC,

    CONSTRAINT pk_pago_natural_01 PRIMARY KEY (idPagoNatural, Compra_idCompra),

    CONSTRAINT arc_pago_natural_metodo CHECK (
     (Cheque_id IS NOT NULL AND Cripto_id IS NULL AND Efectivo_id IS NULL AND PayPal_id IS NULL AND Swift_id IS NULL AND TarjCred_id IS NULL AND TarjDeb_id IS NULL) OR
     (Cripto_id IS NOT NULL AND Cheque_id IS NULL AND Efectivo_id IS NULL AND PayPal_id IS NULL AND Swift_id IS NULL AND TarjCred_id IS NULL AND TarjDeb_id IS NULL) OR
     (Efectivo_id IS NOT NULL AND Cheque_id IS NULL AND Cripto_id IS NULL AND PayPal_id IS NULL AND Swift_id IS NULL AND TarjCred_id IS NULL AND TarjDeb_id IS NULL) OR
     (PayPal_id IS NOT NULL AND Cheque_id IS NULL AND Cripto_id IS NULL AND Efectivo_id IS NULL AND Swift_id IS NULL AND TarjCred_id IS NULL AND TarjDeb_id IS NULL) OR
     (Swift_id IS NOT NULL AND Cheque_id IS NULL AND Cripto_id IS NULL AND Efectivo_id IS NULL AND PayPal_id IS NULL AND TarjCred_id IS NULL AND TarjDeb_id IS NULL) OR
     (TarjCred_id IS NOT NULL AND Cheque_id IS NULL AND Cripto_id IS NULL AND Efectivo_id IS NULL AND PayPal_id IS NULL AND Swift_id IS NULL AND TarjDeb_id IS NULL) OR
     (TarjDeb_id IS NOT NULL AND Cheque_id IS NULL AND Cripto_id IS NULL AND Efectivo_id IS NULL AND PayPal_id IS NULL AND Swift_id IS NULL AND TarjCred_id IS NULL)
     )
);

CREATE TABLE PayPal (
     idMetodoPago        NUMERIC  NOT NULL UNIQUE,
     comisionRetenida  NUMERIC  NOT NULL ,
     codigoTransaccion VARCHAR(200)  NOT NULL ,
     correoAsociado    VARCHAR(200)  NOT NULL,

    CONSTRAINT pk_paypal_01 PRIMARY KEY (idMetodoPago)
);

CREATE TABLE Permiso (
     idPermiso NUMERIC  NOT NULL UNIQUE,
     nombre    VARCHAR(150)  NOT NULL,
    CONSTRAINT pk_permiso_01 PRIMARY KEY (idPermiso)
);

CREATE TABLE Pieza (
     idPieza               NUMERIC  NOT NULL UNIQUE,
     nombre                VARCHAR(150)  NOT NULL ,
     descripcion           VARCHAR(600)  NOT NULL ,
     Color_idColor         NUMERIC  NOT NULL ,
     TipoPieza_idTipoPieza NUMERIC  NOT NULL,

    CONSTRAINT pk_pieza_01 PRIMARY KEY (idPieza)
);

CREATE TABLE PiezaProducto (
     idPiezaProducto     NUMERIC  NOT NULL UNIQUE,
     Pieza_idPieza       NUMERIC  NOT NULL ,
     Producto_idProducto NUMERIC  NOT NULL,

    CONSTRAINT pk_pieza_producto_01 PRIMARY KEY (idPiezaProducto, Pieza_idPieza, Producto_idProducto)
);

CREATE TABLE Producto (
     idProducto                      NUMERIC  NOT NULL UNIQUE,
     nombre                          VARCHAR(150)  NOT NULL ,
     descripcion                     VARCHAR(600)  NOT NULL ,
     fechaSalida                     DATE  NOT NULL ,
     Diseño_idDiseño                 NUMERIC  NOT NULL ,
     LoteProduccion_idLote           NUMERIC  NOT NULL ,
     precioLanzamiento               NUMERIC  NOT NULL ,
     limiteCompraPorUsuario          NUMERIC  NOT NULL ,
     BackOrder_idBackOrder           NUMERIC  NOT NULL,

    CONSTRAINT pk_producto_01 PRIMARY KEY (idProducto)
);

CREATE TABLE Profesion (
     idProfesion NUMERIC  NOT NULL UNIQUE,
     nombre      VARCHAR(150)  NOT NULL ,
     descripcion VARCHAR(600)  NOT NULL,

    CONSTRAINT pk_profesion_01 PRIMARY KEY (idProfesion)
);

CREATE TABLE Prueba (
     idPrueba          NUMERIC NOT NULL ,
     nombrePrueba      VARCHAR(150) NOT NULL ,
     descripcionPrueba VARCHAR(600) NOT NULL ,
     resultado         VARCHAR(150) ,
     tipoPrueba        VARCHAR(150) NOT NULL ,
     Diseño_idDiseño   NUMERIC NOT NULL,

    CONSTRAINT pk_prueba_01 PRIMARY KEY (idPrueba)
) ;

CREATE TABLE PruebaEmpleado (
     idPruebaEmpleado    NUMERIC NOT NULL ,
     fechaInicio         DATE NOT NULL ,
     fechaFin            DATE ,
     Prueba_idPrueba     NUMERIC NOT NULL ,
     Empleado_idEmpleado NUMERIC NOT NULL,

    CONSTRAINT pk_prueba_empleado_01 PRIMARY KEY (idPruebaEmpleado, Prueba_idPrueba, Empleado_idEmpleado)
);

CREATE TABLE PuestoTrabajo (
     id          NUMERIC  NOT NULL UNIQUE,
     nombre      VARCHAR(150)  NOT NULL ,
     descripcion VARCHAR(600)  NOT NULL,

    CONSTRAINT pk_puesto_trabajo_01 PRIMARY KEY (id)
);

CREATE TABLE Puja (
     idPuja                          NUMERIC  NOT NULL UNIQUE,
     fechaHora                       DATE  NOT NULL ,
     monto                           NUMERIC  NOT NULL ,
     ClienteNatural_idClienteNatural NUMERIC  NOT NULL ,
     Subasta_idSubasta               NUMERIC  NOT NULL ,

    CONSTRAINT pk_puja_01 PRIMARY KEY (idPuja, ClienteNatural_idClienteNatural, Subasta_idSubasta)
);

CREATE TABLE Regalia (
     idRegalia NUMERIC  NOT NULL UNIQUE,
     monto     NUMERIC  NOT NULL ,
     fechaHora DATE  NOT NULL,

    CONSTRAINT pk_regalia_01 PRIMARY KEY (idRegalia)
);

CREATE TABLE Restriccion (
     idRestriccion NUMERIC  NOT NULL UNIQUE,
     nombre        VARCHAR(150)  NOT NULL ,
     descripcion   VARCHAR(600)  NOT NULL,

    CONSTRAINT pk_restriccion_01 PRIMARY KEY (idRestriccion)
);

CREATE TABLE RestriccionDiseño (
     idRestriccion             NUMERIC  NOT NULL UNIQUE,
     nombre                    VARCHAR(150)  NOT NULL ,
     descripcion               VARCHAR(600)  NOT NULL ,
     Diseño_idDiseño           NUMERIC  NOT NULL ,
     Restriccion_idRestriccion NUMERIC  NOT NULL ,
     TipoCuerpo_idTipoCuerpo   NUMERIC  NOT NULL,
     RestriccionDiseño_idRestriccion NUMERIC NOT NULL,
     RestriccionDiseño_idDiseño NUMERIC NOT NULL,

    CONSTRAINT pk_restriccion_diseño_01 PRIMARY KEY (idRestriccion, Diseño_idDiseño)
);

CREATE TABLE Rol (
     idRol       NUMERIC  NOT NULL UNIQUE,
     nombre      VARCHAR(150)  NOT NULL ,
     descripcion VARCHAR(150)  NOT NULL ,

    CONSTRAINT pk_rol_01 PRIMARY KEY (idRol)
);

CREATE TABLE RolPermiso (
     idRolPermiso       NUMERIC  NOT NULL UNIQUE,
     Rol_idRol          NUMERIC  NOT NULL ,
     Permisos_idPermiso NUMERIC  NOT NULL,

    CONSTRAINT pk_rol_permiso_01 PRIMARY KEY (idRolPermiso, Rol_idRol, Permisos_idPermiso)
);

CREATE TABLE Sancion (
     idSancion                       NUMERIC  NOT NULL UNIQUE,
     fechaHoraInicio                 DATE  NOT NULL ,
     fechaHoraDin                    DATE  NOT NULL ,
     nombre                          VARCHAR(150)  NOT NULL ,
     descripcion                     VARCHAR(600)  NOT NULL ,
     ClienteNatural_idClienteNatural NUMERIC  NOT NULL,

    CONSTRAINT pk_sancion_01 PRIMARY KEY (idSancion)
);

CREATE TABLE StockClienteNatural (
     idStockClienteNatural              NUMERIC  NOT NULL UNIQUE,
     UnidadProducida_idUnidadProducidad NUMERIC  NOT NULL ,
     ClienteNatural_idClienteNatural    NUMERIC  NOT NULL ,
     condicionFisica_idCondicionFisica  NUMERIC  NOT NULL ,
     Subasta_idSubasta                  NUMERIC  NOT NULL ,

    CONSTRAINT pk_stock_cliente_natural_01 PRIMARY KEY (idStockClienteNatural, UnidadProducida_idUnidadProducidad, ClienteNatural_idClienteNatural)
);

CREATE TABLE Subasta (
     idSubasta               NUMERIC  NOT NULL UNIQUE,
     fechaHoraInicio         DATE  NOT NULL ,
     fechaHoraFin            DATE  NOT NULL ,
     precioBase              NUMERIC  NOT NULL ,
     incrementoMinimo        NUMERIC  NOT NULL ,
     OrdenVenta_idOrdenVenta NUMERIC  NOT NULL ,

    CONSTRAINT pk_subasta_01 PRIMARY KEY (idSubasta)
);

CREATE TABLE SubEnsamblaje (
     idSubEnsamblaje NUMERIC  NOT NULL UNIQUE,
     cantidad        NUMERIC  NOT NULL ,
     Pieza_idPieza   NUMERIC  NOT NULL ,
     Pieza_idPieza2  NUMERIC  NOT NULL,

    CONSTRAINT pk_sub_ensamblaje_01 PRIMARY KEY (idSubEnsamblaje, Pieza_idPieza, Pieza_idPieza2)
);

CREATE TABLE Swift (
     idMetodoPago           NUMERIC  NOT NULL UNIQUE,
     codigoReferencia  VARCHAR(200)  NOT NULL ,
     codigoSwiftOrigen VARCHAR(200)  NOT NULL,

    CONSTRAINT pk_swift_01 PRIMARY KEY (idMetodoPago)
);

CREATE TABLE TarjetaCredito (
     idMetodoPago     NUMERIC  NOT NULL UNIQUE,
     numeroTarjeta        NUMERIC  NOT NULL ,
     hashTarjeta          VARCHAR(200)  NOT NULL ,
     ultimosCuatroDigitos NUMERIC  NOT NULL ,
     franquicia           VARCHAR(200)  NOT NULL ,
     nombreTitular        VARCHAR(200)  NOT NULL,

    CONSTRAINT pk_tarjeta_credito_01 PRIMARY KEY (idMetodoPago)
);

CREATE TABLE TarjetaDebito (
     idMetodoPago NUMERIC  NOT NULL UNIQUE ,
     numeroTarjeta    NUMERIC  NOT NULL ,
     hashTarjeta      VARCHAR(200)  NOT NULL ,
     nombreTitular    VARCHAR(200)  NOT NULL,

    CONSTRAINT pk_tarjeta_debito_01 PRIMARY KEY (idMetodoPago)
);

CREATE TABLE Telefono (
     idTelefono                        NUMERIC  NOT NULL UNIQUE,
     codigoPais                        NUMERIC  NOT NULL ,
     codigoOperadora                   NUMERIC  NOT NULL ,
     numeroAbonado                     NUMERIC  NOT NULL ,
     ClienteJuridico_idClienteJuridico NUMERIC  NOT NULL ,
     ClienteNatural_idClienteNatural   NUMERIC  NOT NULL,

    CONSTRAINT arc_telefono_01 CHECK ( (  (ClienteNatural_idClienteNatural IS NOT NULL
                               AND (ClienteJuridico_idClienteJuridico IS NULL) ) OR (  (ClienteJuridico_idClienteJuridico IS NOT NULL)
                               AND (ClienteNatural_idClienteNatural IS NULL) ) ) ),
    CONSTRAINT pk_telefono_01 PRIMARY KEY (idTelefono)
);

CREATE TABLE TipoCuerpo (
     idTipoCuerpo NUMERIC  NOT NULL UNIQUE,
     nombre       VARCHAR(150)  NOT NULL ,
     descripcion  VARCHAR(600)  NOT NULL,

    CONSTRAINT pk_tipo_cuerpo_01 PRIMARY KEY (idTipoCuerpo)
);

CREATE TABLE TipoDiseño (
     idTipoDiseño NUMERIC  NOT NULL UNIQUE,
     nombre       VARCHAR(150)  NOT NULL,

    CONSTRAINT pk_tipo_diseño_01 PRIMARY KEY (idTipoDiseño)
);

CREATE TABLE TipoPieza (
     idTipoPieza NUMERIC  NOT NULL UNIQUE,
     nombre      VARCHAR(150)  NOT NULL,

    CONSTRAINT pk_tipo_pieza_01 PRIMARY KEY (idTipoPieza)
);

CREATE TABLE TipoRelacion (
     idTipoRelacion   NUMERIC  NOT NULL UNIQUE,
     nombreRelacion   VARCHAR(150)  NOT NULL ,
     Diseño_idDiseño  NUMERIC  NOT NULL ,
     Diseño_idDiseño2 NUMERIC  NOT NULL,

    CONSTRAINT pk_tipo_relacion_01 PRIMARY KEY (idTipoRelacion, Diseño_idDiseño, Diseño_idDiseño2)
);

CREATE TABLE TipoUbicacionStock (
     idTipoUbicacionStock NUMERIC  NOT NULL UNIQUE,
     nombre               VARCHAR(150)  NOT NULL,
     direccion            VARCHAR(150)  NOT NULL,
     Lugar_idLugar        NUMERIC  NOT NULL,
     UnidadProducida_idUnidadProducidad NUMERIC NOT NULL,

    CONSTRAINT pk_tipo_ubicacion_stock_01 PRIMARY KEY (idTipoUbicacionStock)
);

CREATE TABLE TonoPiel (
     idTonoPiel        NUMERIC  NOT NULL UNIQUE,
     nombre            VARCHAR(150)  NOT NULL ,
     escalaFitzpatrick DATE  NOT NULL ,
     valorClaridad     VARCHAR(50)  NOT NULL ,
     luminosidad       NUMERIC  NOT NULL,

    CONSTRAINT pk_tono_piel_01 PRIMARY KEY (idTonoPiel)
);

CREATE TABLE Transporte (
     idTransporte      NUMERIC  NOT NULL UNIQUE,
     matricula         VARCHAR(150)  NOT NULL ,
     nombreConductor   VARCHAR(150)  NOT NULL ,
     apellidoConductor VARCHAR(150)  NOT NULL ,

    CONSTRAINT pk_transporte_01 PRIMARY KEY (idTransporte)
);

CREATE TABLE Turno (
     idTurno           NUMERIC  NOT NULL UNIQUE,
     porcentajeRecargo NUMERIC  NOT NULL ,
     nombre            VARCHAR(150)  NOT NULL ,

    CONSTRAINT pk_turno_01 PRIMARY KEY (idTurno)
);

CREATE TABLE TurnoEmpleado (
     idTurnoEmpleado NUMERIC  NOT NULL UNIQUE,
     fecha           DATE  NOT NULL ,
     feriado         CHAR(1)  NOT NULL ,
     Empleado_idEmpleado     NUMERIC  NOT NULL ,
     Turno_idTurno   NUMERIC  NOT NULL,

    CONSTRAINT pk_turno_empleado_01 PRIMARY KEY (idTurnoEmpleado, Empleado_idEmpleado, Turno_idTurno)
);

CREATE TABLE TurnoHorario (
     idTurnoHorario    NUMERIC NOT NULL ,
     Horario_idHorario NUMERIC NOT NULL ,
     Turno_idTurno     NUMERIC NOT NULL,

    CONSTRAINT pk_turno_horario_01 PRIMARY KEY (idTurnoHorario, Horario_idHorario, Turno_idTurno)
);

CREATE TABLE UnidadProducida (
     idUnidadProducidad                 NUMERIC  NOT NULL UNIQUE,
     fechaSalida                        DATE  NOT NULL ,
     nombre                             VARCHAR(150)  NOT NULL ,
     LoteProduccion_idLote              NUMERIC  NOT NULL ,

    CONSTRAINT pk_unidad_producida_01 PRIMARY KEY (idUnidadProducidad)
);

CREATE TABLE Usuario (
     idUsuario                       NUMERIC  NOT NULL UNIQUE,
     nombreUsuario                   VARCHAR(50)  NOT NULL ,
     correoElectronico               VARCHAR(100)  NOT NULL ,
     contraseña                      VARCHAR(255)  NOT NULL ,
     estado                          VARCHAR(20)  NOT NULL ,
     fechaRegistro                   DATE  NOT NULL ,
     Empleado_idEmpleado             NUMERIC NOT NULL,
     Rol_idRol NUMERIC NOT NULL,
     ClienteNatural_idClienteNatural NUMERIC,

    CONSTRAINT pk_usuario_01 PRIMARY KEY (idUsuario)
);

CREATE TABLE ValoracionMercado (
     idValoracionMercado                NUMERIC  NOT NULL UNIQUE,
     fechaValoracion                    DATE  NOT NULL ,
     precioDelMercado                   NUMERIC  NOT NULL ,
     UnidadProducida_idUnidadProducidad NUMERIC  NOT NULL,

    CONSTRAINT pk_valoracion_mercado_01 PRIMARY KEY (idValoracionMercado)
);

/*  /////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////// */

ALTER TABLE AsignacionMeta ADD CONSTRAINT AsignacionMeta_ComisionVenta_FK FOREIGN KEY ( ComisionVenta_idComisionVenta ) REFERENCES ComisionVenta ( idComisionVenta );
ALTER TABLE AsignacionMeta ADD CONSTRAINT AsignacionMeta_Empleado_FK FOREIGN KEY ( Empleado_idEmpleado ) REFERENCES Empleado ( idEmpleado );
ALTER TABLE AsignacionMeta ADD CONSTRAINT AsignacionMeta_MetaMensual_FK FOREIGN KEY ( MetaMensual_idMetaMensual) REFERENCES MetaMensual ( idMetaMensual);

ALTER TABLE Asistencia ADD CONSTRAINT Asistencia_Empleado_FK FOREIGN KEY ( Empleado_idEmpleado ) REFERENCES Empleado ( idEmpleado );
ALTER TABLE AutorDiseño ADD CONSTRAINT AutorDiseño_Diseño_FK FOREIGN KEY ( Diseño_idDiseño ) REFERENCES Diseño ( idDiseño );
ALTER TABLE AutorDiseño ADD CONSTRAINT AutorDiseño_Empleado_FK FOREIGN KEY ( Empleado_id ) REFERENCES Empleado ( idEmpleado );
ALTER TABLE AutorDiseño ADD CONSTRAINT AutorDiseño_ObjetivoGlobal_FK FOREIGN KEY ( ObjetivoGlobal_idObjetivoGlobal ) REFERENCES ObjetivoGlobal ( idObjetivoGlobal );
ALTER TABLE AutorDiseño ADD CONSTRAINT AutorDiseño_Regalia_FK FOREIGN KEY ( Regalia_idRegalia ) REFERENCES Regalia ( idRegalia );

ALTER TABLE ClienteJuridico ADD CONSTRAINT ClienteJuridico_Lugar_FK FOREIGN KEY ( Lugar_idLugar ) REFERENCES Lugar ( idLugar );

ALTER TABLE ClienteNatural ADD CONSTRAINT ClienteNatural_Lugar_FK FOREIGN KEY ( Lugar_idLugar ) REFERENCES Lugar ( idLugar );

ALTER TABLE ComisionVenta ADD CONSTRAINT ComisionVenta_OrdenCompra_FK FOREIGN KEY ( OrdenCompra_idOrdenCompra ) REFERENCES OrdenCompra ( idOrdenCompra );

ALTER TABLE Compra ADD CONSTRAINT Compra_ClienteNatural_FK FOREIGN KEY ( ClienteNatural_idClienteNatural ) REFERENCES ClienteNatural ( idClienteNatural );
ALTER TABLE Compra ADD CONSTRAINT Compra_TipoUbicacionStock_FK FOREIGN KEY ( TipoUbicacionStock_idTipoUbicacionStock ) REFERENCES TipoUbicacionStock ( idTipoUbicacionStock );

ALTER TABLE CompraDescuento ADD CONSTRAINT CompraDescuento_Compra_FK FOREIGN KEY ( Compra_idCompra ) REFERENCES Compra ( idCompra );
ALTER TABLE CompraDescuento ADD CONSTRAINT CompraDescuento_Descuento_FK FOREIGN KEY ( Descuento_idDescuento ) REFERENCES Descuento ( idDescuento );

ALTER TABLE Conciliacion ADD CONSTRAINT Conciliacion_OrdenCompra_FK FOREIGN KEY ( OrdenCompra_idOrdenCompra ) REFERENCES OrdenCompra ( idOrdenCompra );
ALTER TABLE Conciliacion ADD CONSTRAINT Conciliacion_PagoJuridico_FK FOREIGN KEY ( PagoJuridico_idPago ) REFERENCES PagoJuridico ( idPago );

ALTER TABLE CurriculumVitae ADD CONSTRAINT CurriculumVitae_Diseño_FK FOREIGN KEY ( Diseño_idDiseño ) REFERENCES Diseño ( idDiseño );
ALTER TABLE CurriculumVitae ADD CONSTRAINT CurriculumVitae_Profesion_FK FOREIGN KEY ( Profesion_idProfesion ) REFERENCES Profesion ( idProfesion );

ALTER TABLE DespachoNatural ADD CONSTRAINT DespachoNatural_Compra_FK FOREIGN KEY ( Compra_idCompra ) REFERENCES Compra ( idCompra );
ALTER TABLE DespachoNatural ADD CONSTRAINT DespachoNatural_Courier_FK FOREIGN KEY ( Courier_idCourier ) REFERENCES Courier ( idCourier );

--  ERROR: FK name length exceeds maximum allowed length(30)
ALTER TABLE DetalleCompraJuridico ADD CONSTRAINT DetalleCompraJuridico_BackOrder_FK FOREIGN KEY ( BackOrder_idBackOrder ) REFERENCES BackOrder ( idBackOrder );

--  ERROR: FK name length exceeds maximum allowed length(30)
ALTER TABLE DetalleCompraJuridico ADD CONSTRAINT DetalleCompraJuridico_OrdenCompra_FK FOREIGN KEY ( OrdenCompra_idOrdenCompra ) REFERENCES OrdenCompra ( idOrdenCompra );

ALTER TABLE DetalleCompraNatural ADD CONSTRAINT DetalleCompraNatural_Compra_FK FOREIGN KEY ( Compra_idCompra ) REFERENCES Compra ( idCompra );

--  ERROR: FK name length exceeds maximum allowed length(30)
ALTER TABLE DetalleCompraNatural ADD CONSTRAINT DetalleCompraNatural_UnidadProducida_FK FOREIGN KEY ( UnidadProducida_idUnidadProducidad ) REFERENCES UnidadProducida ( idUnidadProducidad );

--  ERROR: FK name length exceeds maximum allowed length(30)
ALTER TABLE DevolucionJuridica ADD CONSTRAINT DevolucionJuridica_OrdenCompra_FK FOREIGN KEY ( OrdenCompra_idOrdenCompra ) REFERENCES OrdenCompra ( idOrdenCompra );

ALTER TABLE DevolucionNatural ADD CONSTRAINT DevolucionNatural_Compra_FK FOREIGN KEY ( Compra_idCompra ) REFERENCES Compra ( idCompra );

ALTER TABLE Diseño ADD CONSTRAINT Diseño_ClasificacionExclusividad_FK FOREIGN KEY ( ClasificacionExclusividad_idClasificacionExclusividad ) REFERENCES ClasificacionExclusividad ( idClasificacionExclusividad );
ALTER TABLE Diseño ADD CONSTRAINT Diseño_ClasificacionHistorica_FK FOREIGN KEY ( ClasificacionHistorica_idClasificacionHistorica ) REFERENCES ClasificacionHistorica ( idClasificacionHistorica );
ALTER TABLE Diseño ADD CONSTRAINT Diseño_Diseño_FK FOREIGN KEY ( Diseño_idDiseño ) REFERENCES Diseño ( idDiseño );
ALTER TABLE Diseño ADD CONSTRAINT Diseño_MoldeRostro_FK FOREIGN KEY ( MoldeRostro_idMoldeRostro ) REFERENCES MoldeRostro ( idMoldeRostro );
ALTER TABLE Diseño ADD CONSTRAINT Diseño_TipoDiseño_FK FOREIGN KEY ( TipoDiseño_idTipoDiseño ) REFERENCES TipoDiseño ( idTipoDiseño );
ALTER TABLE Diseño ADD CONSTRAINT Diseño_TonoPiel_FK FOREIGN KEY ( TonoPiel_idTonoPiel ) REFERENCES TonoPiel ( idTonoPiel );

ALTER TABLE DiseñoAmbiente ADD CONSTRAINT DiseñoAmbiente_Ambiente_FK FOREIGN KEY ( Ambiente_idAmbiente ) REFERENCES Ambiente ( idAmbiente );
ALTER TABLE DiseñoAmbiente ADD CONSTRAINT DiseñoAmbiente_Diseño_FK FOREIGN KEY ( Diseño_idDiseño ) REFERENCES Diseño ( idDiseño );

ALTER TABLE Empleado ADD CONSTRAINT Empleado_Lugar_FK FOREIGN KEY ( Lugar_idLugar ) REFERENCES Lugar ( idLugar );

ALTER TABLE Fase ADD CONSTRAINT Fase_Diseño_FK FOREIGN KEY ( Diseño_idDiseño ) REFERENCES Diseño ( idDiseño );

ALTER TABLE FaseEmpleado ADD CONSTRAINT FaseEmpleado_Empleado_FK FOREIGN KEY ( Empleado_idEmpleado ) REFERENCES Empleado ( idEmpleado );
ALTER TABLE FaseEmpleado ADD CONSTRAINT FaseEmpleado_Fase_FK FOREIGN KEY ( Fase_idFase ) REFERENCES Fase ( idFase );

ALTER TABLE HistoricoEmpleado ADD CONSTRAINT HistoricoEmpleado_Departamento_FK FOREIGN KEY ( Departamento_idDepartamento ) REFERENCES Departamento ( idDepartamento );
ALTER TABLE HistoricoEmpleado ADD CONSTRAINT HistoricoEmpleado_Empleado_FK FOREIGN KEY ( Empleado_idEmpleado ) REFERENCES Empleado ( idEmpleado );
ALTER TABLE HistoricoEmpleado ADD CONSTRAINT HistoricoEmpleado_PuestoTrabajo_FK FOREIGN KEY ( PuestoTrabajo_id ) REFERENCES PuestoTrabajo ( id );
ALTER TABLE HistoricoEmpleado ADD CONSTRAINT HistoricoEmpleado_TipoUbicacionStock_FK FOREIGN KEY ( TipoUbicacionStock_idTipoUbicacionStock ) REFERENCES TipoUbicacionStock ( idTipoUbicacionStock );

ALTER TABLE HistoricoEstado ADD CONSTRAINT HistoricoEstado_Compra_FK FOREIGN KEY ( Compra_idCompra ) REFERENCES Compra ( idCompra );
ALTER TABLE HistoricoEstado ADD CONSTRAINT HistoricoEstado_EstadoOrden_FK FOREIGN KEY ( EstadoOrden_idEstadoOrden ) REFERENCES EstadoOrden ( idEstadoOrden );
ALTER TABLE HistoricoEstado ADD CONSTRAINT HistoricoEstado_OrdenCompra_FK FOREIGN KEY ( OrdenCompra_idOrdenCompra ) REFERENCES OrdenCompra ( idOrdenCompra );

ALTER TABLE HistoricoEstatus ADD CONSTRAINT HistoricoEstatus_Compra_FK FOREIGN KEY ( Compra_idCompra ) REFERENCES Compra ( idCompra );
ALTER TABLE HistoricoEstatus ADD CONSTRAINT HistoricoEstatus_Estatus_FK FOREIGN KEY ( Estatus_idEstatus ) REFERENCES Estatus ( idEstatus );
ALTER TABLE HistoricoEstatus ADD CONSTRAINT HistoricoEstatus_OrdenVenta_FK FOREIGN KEY ( OrdenVenta_idOrdenVenta ) REFERENCES OrdenVenta ( idOrdenVenta );
ALTER TABLE HistoricoEstatus ADD CONSTRAINT HistoricoEstatus_Puja_FK FOREIGN KEY ( Puja_idPuja, Puja_idClienteNatural, Puja_idSubasta ) REFERENCES Puja ( idPuja, ClienteNatural_idClienteNatural, Subasta_idSubasta );
ALTER TABLE HistoricoEstatus ADD CONSTRAINT HistoricoEstatus_Subasta_FK FOREIGN KEY ( Subasta_idSubasta ) REFERENCES Subasta ( idSubasta );

ALTER TABLE InsumoProduccion ADD CONSTRAINT InsumoProduccion_LoteMateriaPrima_FK FOREIGN KEY ( LoteMateriaPrima_idLoteMateriaPrima ) REFERENCES LoteMateriaPrima ( idLoteMateriaPrima );
ALTER TABLE InsumoProduccion ADD CONSTRAINT InsumoProduccion_LoteProduccion_FK FOREIGN KEY ( LoteProduccion_idLote ) REFERENCES LoteProduccion ( idLote );

--  ERROR: FK name length exceeds maximum allowed length(30)
ALTER TABLE ListaPrecioMayorista ADD CONSTRAINT ListaPrecioMayorista_ClienteJuridico_FK FOREIGN KEY ( ClienteJuridico_idClienteJuridico ) REFERENCES ClienteJuridico ( idClienteJuridico );

--  ERROR: FK name length exceeds maximum allowed length(30)
ALTER TABLE ListaPrecioMayorista ADD CONSTRAINT ListaPrecioMayorista_UnidadProducida_FK FOREIGN KEY ( UnidadProducida_idUnidadProducidad ) REFERENCES UnidadProducida ( idUnidadProducidad );

ALTER TABLE LoteMateriaPrima ADD CONSTRAINT LoteMateriaPrima_Material_FK FOREIGN KEY ( Material_idMaterial ) REFERENCES Material ( idMaterial );
ALTER TABLE Lugar ADD CONSTRAINT Lugar_Lugar_FK FOREIGN KEY ( Lugar_idLugar ) REFERENCES Lugar ( idLugar );
ALTER TABLE ManifiestoCarga ADD CONSTRAINT ManifiestoCarga_OrdenCompra_FK FOREIGN KEY ( OrdenCompra_idOrdenCompra ) REFERENCES OrdenCompra ( idOrdenCompra );
ALTER TABLE ManifiestoCarga ADD CONSTRAINT ManifiestoCarga_Transporte_FK FOREIGN KEY ( Transporte_idTransporte ) REFERENCES Transporte ( idTransporte );
ALTER TABLE MaterialDiseño ADD CONSTRAINT MaterialDiseño_Diseño_FK FOREIGN KEY ( Diseño_idDiseño ) REFERENCES Diseño ( idDiseño );
ALTER TABLE MaterialDiseño ADD CONSTRAINT MaterialDiseño_Material_FK FOREIGN KEY ( Material_idMaterial ) REFERENCES Material ( idMaterial );
ALTER TABLE MaterialDiseño ADD CONSTRAINT MaterialDiseño_Pieza_FK FOREIGN KEY ( Pieza_idPieza ) REFERENCES Pieza ( idPieza );
ALTER TABLE Membresia ADD CONSTRAINT Membresia_ClienteNatural_FK FOREIGN KEY ( ClienteNatural_idClienteNatural ) REFERENCES ClienteNatural ( idClienteNatural );

--  ERROR: FK name length exceeds maximum allowed length(30)
ALTER TABLE MonitorActividadSopechosa ADD CONSTRAINT MonitorActividadSopechosa_ClienteNatural_FK FOREIGN KEY ( ClienteNatural_idClienteNatural ) REFERENCES ClienteNatural ( idClienteNatural );

--  ERROR: FK name length exceeds maximum allowed length(30)
ALTER TABLE ObjetivoGlobalProducto ADD CONSTRAINT ObjetivoGlobalProducto_ObjetivoGlobal_FK FOREIGN KEY ( ObjetivoGlobal_idObjetivoGlobal ) REFERENCES ObjetivoGlobal ( idObjetivoGlobal );

--  ERROR: FK name length exceeds maximum allowed length(30)
ALTER TABLE ObjetivoGlobalProducto ADD CONSTRAINT ObjetivoGlobalProducto_Producto_FK FOREIGN KEY ( Producto_idProducto ) REFERENCES Producto ( idProducto );

ALTER TABLE OrdenCompra ADD CONSTRAINT OrdenCompra_BackOrder_FK FOREIGN KEY ( BackOrder_idBackOrder ) REFERENCES BackOrder ( idBackOrder );
ALTER TABLE OrdenCompra ADD CONSTRAINT OrdenCompra_ClienteJuridico_FK FOREIGN KEY ( ClienteJuridico_idClienteJuridico ) REFERENCES ClienteJuridico ( idClienteJuridico );

--  ERROR: FK name length exceeds maximum allowed length(30)
ALTER TABLE OrdenCompraDescuento ADD CONSTRAINT OrdenCompraDescuento_Descuento_FK FOREIGN KEY ( Descuento_idDescuento ) REFERENCES Descuento ( idDescuento );

--  ERROR: FK name length exceeds maximum allowed length(30)
ALTER TABLE OrdenCompraDescuento ADD CONSTRAINT OrdenCompraDescuento_OrdenCompra_FK FOREIGN KEY ( OrdenCompra_idOrdenCompra ) REFERENCES OrdenCompra ( idOrdenCompra );

ALTER TABLE Pack ADD CONSTRAINT Pack_Producto_FK FOREIGN KEY ( Producto_idProducto ) REFERENCES Producto ( idProducto );
ALTER TABLE Pack ADD CONSTRAINT Pack_Producto_FKv2 FOREIGN KEY ( Producto_idProducto2 ) REFERENCES Producto ( idProducto );
ALTER TABLE PagoNatural ADD CONSTRAINT PagoNatural_Compra_FK FOREIGN KEY ( Compra_idCompra ) REFERENCES Compra ( idCompra );
ALTER TABLE Pieza ADD CONSTRAINT Pieza_Color_FK FOREIGN KEY ( Color_idColor ) REFERENCES Color ( idColor );
ALTER TABLE PiezaProducto ADD CONSTRAINT Pieza_Producto_Pieza_FK FOREIGN KEY ( Pieza_idPieza ) REFERENCES Pieza ( idPieza );
ALTER TABLE PiezaProducto ADD CONSTRAINT Pieza_Producto_Producto_FK FOREIGN KEY ( Producto_idProducto ) REFERENCES Producto ( idProducto );
ALTER TABLE Pieza ADD CONSTRAINT Pieza_TipoPieza_FK FOREIGN KEY ( TipoPieza_idTipoPieza ) REFERENCES TipoPieza ( idTipoPieza );
ALTER TABLE Producto ADD CONSTRAINT Producto_BackOrder_FK FOREIGN KEY ( BackOrder_idBackOrder ) REFERENCES BackOrder ( idBackOrder );
ALTER TABLE Producto ADD CONSTRAINT Producto_Diseño_FK FOREIGN KEY ( Diseño_idDiseño ) REFERENCES Diseño ( idDiseño );
ALTER TABLE Producto ADD CONSTRAINT Producto_LoteProduccion_FK FOREIGN KEY ( LoteProduccion_idLote ) REFERENCES LoteProduccion ( idLote );
ALTER TABLE Prueba ADD CONSTRAINT Prueba_Diseño_FK FOREIGN KEY ( Diseño_idDiseño ) REFERENCES Diseño ( idDiseño );
ALTER TABLE PruebaEmpleado ADD CONSTRAINT PruebaEmpleado_Empleado_FK FOREIGN KEY ( Empleado_idEmpleado ) REFERENCES Empleado ( idEmpleado );
ALTER TABLE PruebaEmpleado ADD CONSTRAINT PruebaEmpleado_Prueba_FK FOREIGN KEY ( Prueba_idPrueba ) REFERENCES Prueba ( idPrueba );
ALTER TABLE Puja ADD CONSTRAINT Puja_ClienteNatural_FK FOREIGN KEY ( ClienteNatural_idClienteNatural ) REFERENCES ClienteNatural ( idClienteNatural );
ALTER TABLE Puja ADD CONSTRAINT Puja_Subasta_FK FOREIGN KEY ( Subasta_idSubasta ) REFERENCES Subasta ( idSubasta );
ALTER TABLE RestriccionDiseño ADD CONSTRAINT RestriccionDiseño_Diseño_FK FOREIGN KEY ( Diseño_idDiseño ) REFERENCES Diseño ( idDiseño );

--  ERROR: FK name length exceeds maximum allowed length(30)
ALTER TABLE RestriccionDiseño ADD CONSTRAINT RestriccionDiseño_Restriccion_FK FOREIGN KEY ( Restriccion_idRestriccion ) REFERENCES Restriccion ( idRestriccion );

--  ERROR: FK name length exceeds maximum allowed length(30)
ALTER TABLE RestriccionDiseño ADD CONSTRAINT RestriccionDiseño_RestriccionDiseño_FK FOREIGN KEY ( RestriccionDiseño_idRestriccion, RestriccionDiseño_idDiseño ) REFERENCES RestriccionDiseño ( idRestriccion, Diseño_idDiseño );

--  ERROR: FK name length exceeds maximum allowed length(30)
ALTER TABLE RestriccionDiseño ADD CONSTRAINT RestriccionDiseño_TipoCuerpo_FK FOREIGN KEY ( TipoCuerpo_idTipoCuerpo ) REFERENCES TipoCuerpo ( idTipoCuerpo );

ALTER TABLE RolPermiso ADD CONSTRAINT RolPermiso_Rol_FK FOREIGN KEY ( Rol_idRol ) REFERENCES Rol ( idRol );
ALTER TABLE Sancion ADD CONSTRAINT Sancion_ClienteNatural_FK FOREIGN KEY ( ClienteNatural_idClienteNatural ) REFERENCES ClienteNatural ( idClienteNatural );

--  ERROR: FK name length exceeds maximum allowed length(30)
ALTER TABLE StockClienteNatural ADD CONSTRAINT StockClienteNatural_ClienteNatural_FK FOREIGN KEY ( ClienteNatural_idClienteNatural ) REFERENCES ClienteNatural ( idClienteNatural );

--  ERROR: FK name length exceeds maximum allowed length(30)
ALTER TABLE StockClienteNatural ADD CONSTRAINT StockClienteNatural_condicionFisica_FK FOREIGN KEY ( condicionFisica_idCondicionFisica ) REFERENCES condicionFisica ( idCondicionFisica );

ALTER TABLE StockClienteNatural ADD CONSTRAINT StockClienteNatural_Subasta_FK FOREIGN KEY ( Subasta_idSubasta ) REFERENCES Subasta ( idSubasta );

--  ERROR: FK name length exceeds maximum allowed length(30)
ALTER TABLE StockClienteNatural ADD CONSTRAINT StockClienteNatural_UnidadProducida_FK FOREIGN KEY ( UnidadProducida_idUnidadProducidad ) REFERENCES UnidadProducida ( idUnidadProducidad );

ALTER TABLE Subasta ADD CONSTRAINT Subasta_OrdenVenta_FK FOREIGN KEY ( OrdenVenta_idOrdenVenta ) REFERENCES OrdenVenta ( idOrdenVenta );

ALTER TABLE SubEnsamblaje ADD CONSTRAINT SubEnsamblaje_Pieza_FK FOREIGN KEY ( Pieza_idPieza ) REFERENCES Pieza ( idPieza );
ALTER TABLE SubEnsamblaje ADD CONSTRAINT SubEnsamblaje_Pieza_FKv2 FOREIGN KEY ( Pieza_idPieza2 ) REFERENCES Pieza ( idPieza );

ALTER TABLE Telefono ADD CONSTRAINT Telefono_ClienteJuridico_FK FOREIGN KEY ( ClienteJuridico_idClienteJuridico ) REFERENCES ClienteJuridico ( idClienteJuridico );
ALTER TABLE Telefono ADD CONSTRAINT Telefono_ClienteNatural_FK FOREIGN KEY ( ClienteNatural_idClienteNatural ) REFERENCES ClienteNatural ( idClienteNatural );

ALTER TABLE TipoRelacion ADD CONSTRAINT TipoRelacion_Diseño_FK FOREIGN KEY ( Diseño_idDiseño ) REFERENCES Diseño ( idDiseño );
ALTER TABLE TipoRelacion ADD CONSTRAINT TipoRelacion_Diseño_FKv2 FOREIGN KEY ( Diseño_idDiseño2 ) REFERENCES Diseño ( idDiseño );

ALTER TABLE TipoUbicacionStock ADD CONSTRAINT TipoUbicacionStock_Lugar_FK FOREIGN KEY ( Lugar_idLugar ) REFERENCES Lugar ( idLugar );
ALTER TABLE TipoUbicacionStock ADD CONSTRAINT TipoUbicacionStock_UnidadProducida_FK FOREIGN KEY ( UnidadProducida_idUnidadProducidad ) REFERENCES UnidadProducida ( idUnidadProducidad );

ALTER TABLE TurnoEmpleado ADD CONSTRAINT TurnoEmpleado_Empleado_FK FOREIGN KEY ( Empleado_idEmpleado ) REFERENCES Empleado ( idEmpleado );
ALTER TABLE TurnoEmpleado ADD CONSTRAINT TurnoEmpleado_Turno_FK FOREIGN KEY ( Turno_idTurno ) REFERENCES Turno ( idTurno );
ALTER TABLE TurnoHorario ADD CONSTRAINT TurnoHorario_Horario_FK FOREIGN KEY ( Horario_idHorario ) REFERENCES Horario ( idHorario );
ALTER TABLE TurnoHorario ADD CONSTRAINT TurnoHorario_Turno_FK FOREIGN KEY ( Turno_idTurno ) REFERENCES Turno ( idTurno );

--  ERROR: FK name length exceeds maximum allowed length(30)
ALTER TABLE UnidadProducida ADD CONSTRAINT UnidadProducida_LoteProduccion_FK FOREIGN KEY ( LoteProduccion_idLote ) REFERENCES LoteProduccion ( idLote );

ALTER TABLE Usuario ADD CONSTRAINT Usuario_ClienteNatural_FK FOREIGN KEY ( ClienteNatural_idClienteNatural ) REFERENCES ClienteNatural ( idClienteNatural );
ALTER TABLE Usuario ADD CONSTRAINT Usuario_Empleado_FK FOREIGN KEY ( Empleado_idEmpleado ) REFERENCES Empleado ( idEmpleado );
ALTER TABLE Usuario ADD CONSTRAINT Usuario_Rol_FK FOREIGN KEY ( Rol_idRol ) REFERENCES Rol ( idRol );

--  ERROR: FK name length exceeds maximum allowed length(30)
ALTER TABLE ValoracionMercado ADD CONSTRAINT ValoracionMercado_UnidadProducida_FK FOREIGN KEY ( UnidadProducida_idUnidadProducidad ) REFERENCES UnidadProducida ( idUnidadProducidad );


-- Llaves foráneas para PagoJuridico
ALTER TABLE PagoJuridico ADD CONSTRAINT PJur_Cheque_FK FOREIGN KEY (Cheque_id) REFERENCES ChequeCorporativo(idMetodoPago);
ALTER TABLE PagoJuridico ADD CONSTRAINT PJur_Cripto_FK FOREIGN KEY (Cripto_id) REFERENCES CriptoActivo(idMetodoPago);
ALTER TABLE PagoJuridico ADD CONSTRAINT PJur_Efectivo_FK FOREIGN KEY (Efectivo_id) REFERENCES Efectivo(idMetodoPago);
ALTER TABLE PagoJuridico ADD CONSTRAINT PJur_PayPal_FK FOREIGN KEY (PayPal_id) REFERENCES PayPal(idMetodoPago);
ALTER TABLE PagoJuridico ADD CONSTRAINT PJur_Swift_FK FOREIGN KEY (Swift_id) REFERENCES Swift(idMetodoPago);
ALTER TABLE PagoJuridico ADD CONSTRAINT PJur_TarjCred_FK FOREIGN KEY (TarjCred_id) REFERENCES TarjetaCredito(idMetodoPago);
ALTER TABLE PagoJuridico ADD CONSTRAINT PJur_TarjDeb_FK FOREIGN KEY (TarjDeb_id) REFERENCES TarjetaDebito(idMetodoPago);

-- Llaves foráneas para PagoNatural
ALTER TABLE PagoNatural ADD CONSTRAINT PNat_Cheque_FK FOREIGN KEY (Cheque_id) REFERENCES ChequeCorporativo(idMetodoPago);
ALTER TABLE PagoNatural ADD CONSTRAINT PNat_Cripto_FK FOREIGN KEY (Cripto_id) REFERENCES CriptoActivo(idMetodoPago);
ALTER TABLE PagoNatural ADD CONSTRAINT PNat_Efectivo_FK FOREIGN KEY (Efectivo_id) REFERENCES Efectivo(idMetodoPago);
ALTER TABLE PagoNatural ADD CONSTRAINT PNat_PayPal_FK FOREIGN KEY (PayPal_id) REFERENCES PayPal(idMetodoPago);
ALTER TABLE PagoNatural ADD CONSTRAINT PNat_Swift_FK FOREIGN KEY (Swift_id) REFERENCES Swift(idMetodoPago);
ALTER TABLE PagoNatural ADD CONSTRAINT PNat_TarjCred_FK FOREIGN KEY (TarjCred_id) REFERENCES TarjetaCredito(idMetodoPago);
ALTER TABLE PagoNatural ADD CONSTRAINT PNat_TarjDeb_FK FOREIGN KEY (TarjDeb_id) REFERENCES TarjetaDebito(idMetodoPago);
